### ISSUE TITLE
Step for NULL values is missing!

### ISSUE THREAD

**Issue by PhilipKelley** [MicrosoftDocs/sql-docs#4624] opened 2020-04-23 15:46 UTC
When the statistic's column permits NULL values, the (first) histogram step is for NULL values, as can be confirmed using DBCC SHOW_STATISTICS. However, sys.dm_db_stats_histogram does NOT include this row. This appears to apply to all versions of SQL from 2016 through 2017 CU11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126cee00-6aa6-eaa2-fb98-81d6fc410f46
* Version Independent ID: 7eac0fd9-cfd6-2d9c-3c4c-8f80cd2a7ca5
* Content: [sys.dm_db_stats_histogram (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-stats-histogram-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-db-stats-histogram-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-db-stats-histogram-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment] 2020-04-23 18:17
@PhilipKelley -- Philip, thank you for your feedback.

@stevestein -- Steve, please look into this issue.

**Comment by brettshearer** [comment] 2020-05-01 23:33
I have checked this in SQL 2017 CU20 and the problem is still there.
201 rows of data in the histogram for DBCC, 200 rows of data for sys.dm_db_stats_histogram on a fully loaded table.

Here is a trivial repro

```
create table S (g uniqueidentifier);
insert into S select top 50 newid() from master..spt_Values;
insert into S values (null);
create statistics NullStat on S (g) with fullscan;

declare @Stats_id int = (select Stats_id from sys.stats where object_id = object_id('s') and Name = 'NullStat');
select * from sys.dm_db_stats_histogram(object_id('S'), @Stats_id)
go
dbcc Show_Statistics('S', 'NullStat')
```

**Comment by rothja** [comment] 2020-05-05 10:52
@CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by CarlRabeler** [comment] 2020-05-11 19:57
@pmasl Pedro, could you please take a look at this issue? Thanks, Carl

**Comment by CarlRabeler** [comment] 2020-05-19 18:47
@pmasl Pedro, can you please review this issue? Thanks, Carl

**Comment by pmasl** [comment] 2020-05-20 22:16
This seems to be a bug. We'll get it in the backlog. #please-close

**Closed by pmasl** 2020-05-20 22:16 UTC
Labels: Pri2, assigned-to-author, doc-bug, sql/prod, system-objects/tech
