### ISSUE TITLE
Release 18.12 page download link pointing to 18.11.1 installer

### ISSUE THREAD

**Issue by KerryKilgour** [MicrosoftDocs/sql-docs#7669] opened 2022-06-09 18:45 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver16#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by rwestMSFT** [comment] 2022-06-09 23:39
Thanks for your feedback, @KerryKilgour!

Duplicate of https://github.com/MicrosoftDocs/sql-docs/issues/7670

#please-close

**Closed by rwestMSFT** 2022-06-09 23:39 UTC
Labels: sql/prod, ssms/tech, Pri1
