### ISSUE TITLE
TNS Error

### ISSUE THREAD

**Issue by ynsusanto** [MicrosoftDocs/sql-docs#7302] opened 2022-02-12 13:40 UTC
Hello,

I have a question, could I actually pull an oracle query from Azure Data Studio or just explore the database itself. I installed the extension, setup the connection and able to see all the oracle tables. However, when I tried to pull a query, it gives me an error saying TNS is not registered. What is this error about? And how to troubleshoot it? 

Thank you,
Yessie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5899cc-4757-b131-c36e-a0243b5bad95
* Version Independent ID: 8df879ca-e629-a313-6af9-8a6c3c04eefe
* Content: [Quickstart: Connect and explore Oracle databases - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-oracle?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/quickstart-oracle.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/quickstart-oracle.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @nahk-ivanov
* Microsoft Alias: **alexiva**

**Comment by nahk-ivanov** [comment] 2022-02-12 16:53
Is it a duplicate of https://github.com/microsoft/azuredatastudio/issues/18268 ? As stated in the README:

```
Current limitations
Not all Azure Data Studio features are currently supported when connecting to Oracle database. Below is the list of current limitations:

- Server management and dashboard are not supported
- Packaged objects are not supported
- Table data preview/editing is not supported
- Query execution is not supported
```

**Comment by ynsusanto** [comment] 2022-02-12 17:09
It is not. I did not see the limitation statements. That answers my question. Thank you!On Feb 12, 2022 10:54 AM, Alexander Ivanov ***@***.***> wrote:
Is it a duplicate of microsoft/azuredatastudio#18268 ? As stated in the README:
Current limitations
Not all Azure Data Studio features are currently supported when connecting to Oracle database. Below is the list of current limitations:

- Server management and dashboard are not supported
- Packaged objects are not supported
- Table data preview/editing is not supported
- Query execution is not supported

**Closed** 2022-02-14 23:22 UTC
Labels: azure-data-studio/tech, Pri2, azure-data-studio/prod
