### ISSUE TITLE
typo: wrong information about sql server version

### ISSUE THREAD

**Issue by gmareater** [MicrosoftDocs/sql-docs#3527] opened 2019-11-09 20:52 UTC
this is first line which says "Sql Server 2019"
"Raises an exception and transfers execution to a CATCH block of a TRY...CATCH construct in SQL Server 2019." 

but the time of writing this article is "03/16/2017" which no SQL 2019 existed, so you have bug probably on updating article write time.
and I changed sql server version to 2017 but still the same. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 525698d4-0465-5fe0-f09d-dfad8b8413e6
* Version Independent ID: 2ece841a-2d51-542e-6c2b-9d36ffe54202
* Content: [THROW (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/language-elements/throw-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/throw-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment] 2019-11-11 19:07
@gmareater Thank you for the feedback.

The current version is included in the article's description by design, though this is seemingly in conflict with the article's version selector.

Assigning this to the author for review.

**Comment by gmareater** [comment] 2019-11-11 20:59
thank you, and just to mention it's kinda misleading, at first I thought try-catch  introduced  in 2019.

**Comment by rothja** [comment] 2019-11-12 17:13
@gmareater Thanks for the feedback, and you have definitely found a problem. I am going to fix this and let you know when it is fixed. For this article, it should just say SQL Server with no version. Apologies for the confusion.

**Comment by rothja** [comment] 2019-11-12 17:54
@gmareater We are making a fix today that will make this variable resolve to "SQL Server" to avoid this confusion. Thank you for pointing this out!!

**Closed by rothja** 2019-11-12 17:54 UTC
Labels: Pri1, assigned-to-author, doc-enhancement, sql/prod, t-sql/tech

**Comment by KevinPence** [comment] 2020-04-15 01:14
Looks like the misleading info is still there in the first line of the article (after APPLIES TO)

**Comment by rothja** [comment] 2020-04-17 14:32
@KevinPence Thanks for pointing that out. I'm not sure why the fix was not applied, but I will followup.
