### ISSUE TITLE
ALTER TABLE SWITCH restrictions regarding partitions in nonclustered indexes (error 4907)

### ISSUE THREAD

**Issue by EitanBlumin** [MicrosoftDocs/sql-docs#9167] opened 2023-07-17 06:20 UTC
When trying to perform `SWITCH TO` between two tables, error 4907 is raised:

```
Msg 4907, Level 16, State 1, Line 38
'ALTER TABLE SWITCH' statement failed. The table 'MyDB.dbo.PrtTable1' has 4 partitions while index 'IX1' has 6 partitions.
```

This happens when the source table has a non-clustered index that's partitioned differently from the table itself.

But this error is also raised when:

- Both tables are partitioned identically, including nonclustered indexes.
- Target table doesn't have any non-clustered indexes.

Here's a code snippet to replicate the issue:

```sql
CREATE PARTITION FUNCTION PF1 (int) AS RANGE RIGHT FOR VALUES (0, 100)
GO
CREATE PARTITION FUNCTION PF2 (int) AS RANGE RIGHT FOR VALUES (0, 100, 200)
GO
CREATE PARTITION SCHEME PS1 AS PARTITION PF1 ALL TO ([PRIMARY]);
GO
CREATE PARTITION SCHEME PS2 AS PARTITION PF2 ALL TO ([PRIMARY]);
GO
CREATE TABLE dbo.PrtTable1 (prtCol int NOT NULL PRIMARY KEY CLUSTERED ON PS1(prtCol), otherCol int) ON PS1(prtCol)
CREATE NONCLUSTERED INDEX IX1 ON dbo.PrtTable1 (otherCol) ON PS2(prtCol)
GO
CREATE TABLE dbo.PrtTable2 (prtCol int NOT NULL PRIMARY KEY CLUSTERED ON PS1(prtCol), otherCol int) ON PS1(prtCol)
CREATE NONCLUSTERED INDEX IX2 ON dbo.PrtTable2 (otherCol) ON PS2(prtCol)
GO
CREATE TABLE dbo.PrtTable3 (prtCol int NOT NULL PRIMARY KEY CLUSTERED ON PS1(prtCol), otherCol int) ON PS1(prtCol)
GO
INSERT INTO dbo.PrtTable1 (prtCol, otherCol)
VALUES
(50, 30)
GO
SELECT OBJECT_NAME(object_id), index_id, partition_number, rows
FROM sys.partitions
WHERE object_id IN (OBJECT_ID('PrtTable1'),OBJECT_ID('PrtTable2'),OBJECT_ID('PrtTable3'))
GO
ALTER TABLE dbo.PrtTable1 SWITCH PARTITION 2 TO dbo.PrtTable2 PARTITION 2 -- raises error 4907
GO
ALTER TABLE dbo.PrtTable1 SWITCH PARTITION 2 TO dbo.PrtTable3 PARTITION 2 -- also raises error 4907
GO
-- Cleanup:
DROP TABLE IF EXISTS dbo.PrtTable1
DROP TABLE IF EXISTS dbo.PrtTable2
DROP TABLE IF EXISTS dbo.PrtTable3
DROP PARTITION SCHEME PS2
DROP PARTITION FUNCTION PF2
DROP PARTITION SCHEME PS1
DROP PARTITION FUNCTION PF1
```

This validation, evident by error 4907, does not make logical sense. Since source and target tables are identically partitioned then it shouldn't matter that a non-clustered index is differently partitioned.

Even more so if the same non-clustered index doesn't even exist at the target table at all (see `PrtTable3` in the code snippet above). And even more so when the partition range values are matching regardless.

I can only guess that the reason for this limitation is that when there's a non-clustered index on the table that is differently partitioned than the table itself, then the reference to any partition number in the `SWITCH` command becomes **ambiguous** (partition number based on what? the clustered index? nonclustered index 1? nonclustered index 2?).

I can understand the rationale in this case, even though I believe a solution should be implemented to remove this ambiguity. Such as an optional reference to a specific partition scheme/function in the `SWITCH` command. For example:

```
ALTER TABLE dbo.PrtTable1 SWITCH PARTITION 2 TO dbo.PrtTable2 PARTITION 2 WITH (RANGE BY PARTITION FUNCTION PF1) -- I'm just spitballing here
```

But the worst problem, and that is why I'm creating this issue here, is that **there are absolutely zero references to this limitation in the documentation page**.

If there is indeed such a hard limitation for the `SWITCH` command then it must be specified by the documentation on the `SWITCH` command.

https://github.com/MicrosoftDocs/sql-docs/blob/1e86e51707e934be8b10a60debb5fc34ad98e749/docs/t-sql/statements/alter-table-transact-sql.md?plain=1#L801C1-L801C1

Additionally, error 4907 is stored in `sys.messages` as such:

```
'%ls' statement failed. The %S_MSG '%.*ls' has %d partitions while index '%.*ls' has %d partitions.
```

This also indicates that this issue could potentially happen with other commands, not just `ALTER TABLE SWITCH`. The Microsoft documentation should be updated to reflect this limitation wherever relevant.

Thank you

**Comment by WilliamAntonRohm** [comment] 2023-07-17 07:30
@EitanBlumin -- Eitan, thank you for your thorough feedback.  If you feel this is a product issue, please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

@markingmyname -- Mark, please look into this issue.

**Comment by EitanBlumin** [comment] 2023-07-17 07:33
@WilliamAntonRohm it's both a product issue and a documentation issue... The documentation issue being more urgent/immediate.

**Comment by WilliamAntonRohm** [comment] 2023-07-17 07:56
@EitanBlumin -- Eitan, thank you for your follow-up clarification.

**Comment by EitanBlumin** [comment] 2023-08-05 11:28
Also adding here that the same should similarly be mentioned for error 4912:

```
'%ls' statement failed. The columns set used to partition the %S_MSG '%.*ls' is different from the column set used to partition index '%.*ls'.
```

**Comment by markingmyname** [comment] 2023-08-10 01:22
@EitanBlumin 

We appreciate your patience and would like to inform you that we are actively addressing the Git issue you've reported. Our team is diligently working on resolving this matter to ensure smooth functionality.

We understand the importance of this issue and its impact on your experience. Rest assured, we are committed to delivering a timely solution. We will keep you updated on our progress and notify you as soon as the issue is resolved.

Thank you for bringing this to our attention and for your continued support.  This callout will be addressed.

**Comment by EitanBlumin** [comment] 2023-08-10 04:05
Your response looks like it's AI generated, @markingmyname , but sure, thanks 😁

**Comment by rwestMSFT** [comment] 2023-08-10 04:24
@EitanBlumin Mark means every word 😄.

**Comment by EitanBlumin** [comment] 2023-08-10 04:42
I don't doubt it, @rwestMSFT , I jest 😄

**Comment by markingmyname** [comment] 2023-08-10 15:53
@EitanBlumin 

I guess my response did sound AI-ish. 

But it was from me, as @rwestMSFT mentioned.  

I just wanted to make sure you knew it was received and being looked into.

Again, you do make a strong argument with this submission. 

We also appreciate the time you took to add as much detail as you did.

For these reasons is why we are making this submission a priority.

Thank you.

**Comment by markingmyname** [comment] 2023-08-14 16:44
@EitanBlumin 

We can't thank you enough for bringing this to our attention.

We plan on adding the specific "limitation" for Switch when applied to indexes by the end of teh week.

However, as for the other errors, have you visited the [Error codes article](https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors-4000-to-4999?view=sql-server-ver16)?

**Comment by markingmyname** [comment] 2023-08-14 16:45
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.

Not AI generated. :D

**Closed by markingmyname** 2023-08-14 16:45 UTC
Labels: doc-bug, assigned-to-author, Pri3, sql/svc, t-sql/subsvc
