### ISSUE TITLE
Synapse Dedicated Pool:  sys.allocation_units;

### ISSUE THREAD

**Issue by pwehland** [MicrosoftDocs/sql-docs#7437] opened 2022-03-30 22:10 UTC
select * from sys.allocation_units;

Msg 104385, Level 16, State 1, Line 1
Catalog view 'allocation_units' is not supported in this version.

Can anyone please suggest solution to this
i have searched, but cant able to find right solution

@WilliamAntonRohm 
@Vabby547 
@LuisGonzalezLT

_Originally posted by @ajithkumar-22 in https://github.com/MicrosoftDocs/sql-docs/issues/3749#issuecomment-1057664833_

We need this exposed so we can join to sys.dm_pdw_nodes_os_buffer_descriptors.allocation_unit_id for tuning our workloads.

**Comment by WilliamAntonRohm** [comment] 2022-03-30 23:35
Duplicate of #3749.

**Closed by WilliamAntonRohm** 2022-03-30 23:35 UTC
Labels: duplicate, sql/prod, cba, Pri3
