### ISSUE TITLE
Example provided generates error "Invalid Column Name"  '__$command_id'

### ISSUE THREAD

**Issue by pcand01** [MicrosoftDocs/sql-docs#3792] opened 2019-12-12 21:05 UTC
sys.sp_cdc_generate_wrapper_function generates a bug Invalid column name '__$command_id'
See this for more info. https://stackoverflow.com/questions/49440025/sql-server-cdc-invalid-column-name-command-id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9b8218-779e-0221-20db-7927954f7c62
* Version Independent ID: ae173770-6c50-9d03-0a39-87204e756755
* Content: [sys.sp_cdc_generate_wrapper_function (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-generate-wrapper-function-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sys-sp-cdc-generate-wrapper-function-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sys-sp-cdc-generate-wrapper-function-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment] 2019-12-13 05:57
@pcand01 Thank you for the feedback and for providing a link to the extra info.

Assigning this to author for review.

**Comment by rothja** [comment] 2019-12-20 19:59
@pcand01 Thanks for the feedback. If the function is not documented correctly, we'd like to get it fixed. I'm going to run a test to see if I can reproduce. I also noticed there are [two stackoverflow threads](https://stackoverflow.com/search?q=__%24command_id) on this that might help too. I will look at those as well. Thank you!

**Comment by pcand01** [comment] 2019-12-20 20:47
Thanks, I also note that the wrapper functions generated are incorrect
EXEC sys.sp_cdc_generate_wrapper_function; is not creating the correct code

From lsn  is looking at Largest than instead of lesser than and the IF test often incorrectly return nulls, ending in error.
These wrapper functions needs a review and update

      DECLARE
         @from_lsn BINARY(10), @to_lsn BINARY(10);

      IF (@start_time IS NULL) SELECT @from_lsn=sys.fn_cdc_get_min_lsn('sfdc_Account');
      ELSE
         BEGIN
            IF (sys.fn_cdc_map_lsn_to_time(sys.fn_cdc_get_min_lsn('sfdc_Account'))>@start_time) OR
               (sys.fn_cdc_map_lsn_to_time(sys.fn_cdc_get_max_lsn())<@start_time)
               SELECT @from_lsn=NULL;
            ELSE
               SELECT
                 @from_lsn=sys.fn_cdc_increment_lsn(sys.fn_cdc_map_time_to_lsn(
                                                                                  'largest less than or equal'
                                                                               ,  @start_time
                                                                               )
                                                    );
         END;

      IF (@end_time IS NULL) SELECT @to_lsn=sys.fn_cdc_get_max_lsn();
      ELSE
         BEGIN
            IF sys.fn_cdc_map_lsn_to_time(sys.fn_cdc_get_max_lsn())<@end_time SELECT @to_lsn=NULL; ELSE SELECT @to_lsn=sys.fn_cdc_map_time_to_lsn(
                                                                                'largest less than or equal'
                                                                                , @end_time
                                                                                );
         END;

      IF @from_lsn IS NOT NULL AND @to_lsn IS NOT NULL AND (@from_lsn=sys.fn_cdc_increment_lsn(@to_lsn))
         RETURN;

**Comment by rothja** [comment] 2020-02-13 16:01
@pcand01 I got a chance to try some of these out to see if I could dig into this problem a bit more. When I ran the wrapper functions, they did create a column named __#command_id. Is it possible that this bug has been fixed in a recent cumulative update? Here is the full text for the generated wrapper where you can see __#command_id:

```sql
   create function [fn_net_changes_dbo_SQLTest]   ( @start_time datetime = null,    @end_time datetime = null,    @row_filter_option nvarchar(30) = N'all'   )   returns @resultset table (  [ID] int, [c1] varchar(100), [dt1] datetime, [__$command_id] int,  [__CDC_OPERATION] varchar(2)     ) as   begin    declare @from_lsn binary(10), @to_lsn binary(10)         if (@start_time is null)     select @from_lsn = [sys].[fn_cdc_get_min_lsn]('dbo_SQLTest')    else    begin     if ([sys].[fn_cdc_map_lsn_to_time]([sys].[fn_cdc_get_min_lsn]('dbo_SQLTest')) > @start_time) or        ([sys].[fn_cdc_map_lsn_to_time]([sys].[fn_cdc_get_max_lsn]()) < @start_time)      select @from_lsn = null     else      select @from_lsn = [sys].[fn_cdc_increment_lsn]([sys].[fn_cdc_map_time_to_lsn]('largest less than or equal',@start_time))    end        if (@end_time is null)     select @to_lsn = [sys].[fn_cdc_get_max_lsn]()    else    begin     if [sys].[fn_cdc_map_lsn_to_time]([sys].[fn_cdc_get_max_lsn]()) < @end_time      select @to_lsn = null     else      select @to_lsn = [sys].[fn_cdc_map_time_to_lsn]('largest less than or equal',@end_time)    end        if @from_lsn is not null and @to_lsn is not null and     (@from_lsn = [sys].[fn_cdc_increment_lsn](@to_lsn))     return         insert into @resultset    select  [ID], [c1], [dt1], [__$command_id],      case [__$operation]      when 1 then 'D'      when 2 then 'I'      when 3 then 'UO'      when 4 then 'UN'      when 5 then 'M'      else null     end as [__CDC_OPERATION]       from [cdc].[fn_cdc_get_net_changes_dbo_SQLTest](@from_lsn, @to_lsn, @row_filter_option)          return   end
```

I tried this on SQL Server 2019 and 2017 (latest CUs). Or are you saying that you get the error when you try to use the wrapper functions?

As for whether the CDC wrappers are themselves correct, I would suggest that you enter this as either a bug/suggestion on [user voice](https://feedback.azure.com/forums/908035-sql-server?query=cdc) or open a support case to investigate with our support engineers.

I apologize you ran into problems using CDC and these wrapper functions. Were you able to find your own solution to get the CDC data you needed, or were you eventually blocked completely by this problem?

**Comment by PhilippeCand** [comment] 2020-02-13 17:15
@rothja I created a variant and tested it successfully. I am fine, I just wanted to report a bug to save others some time.

**Comment by rothja** [comment] 2020-02-13 18:09
@PhilippeCand Thanks for letting me know. I'm hoping this is fixed now, but if not, someone else can add more info in this thread and/or the [user voice forum](https://feedback.azure.com/forums/908035-sql-server?query=cdc) to vote for improvements in this area. Thanks for reporting it!

**Comment by saryeHaddadi** [comment] 2020-03-17 14:46
Hello @rothja rothja, I encontered the same issue.
I think that this is a bug and should be repported for correction. The CDC offers APIs / SPs / Functions so that no development are needed. However, the only way to solve this issue is by modifying the automatically generated functions provided by the CDC. This is opposed to the initial purpose of all those SP/Function which needed no modifications to work as a whole.

Below is an explanation of where the compability had been broken:

- A New column [__$command_id] had been created through a cumulative update [1].
- The capture table has column [__$command_id],
- The TFV functions generated by [sys.sp_cdc_enable_table] do **not** return the column [__$command_id], (cdc.fn_cdc_get_net_changes_<capture_Instance> and cdc.fn_cdc_get_all_changes_<capture_Instance>)
- The wrapper functions generated by [sys.sp_cdc_generate_wrapper_function] expect the TFV functions to have the column [__$command_id].
=> The documentation is fine. The bug is in the generation of the TFV functions which does not provide them with column [__$command_id] even if the columns appear in the change table.

[1] See the Remarks sections of the documentation: https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-capture-instance-ct-transact-sql?view=sql-server-ver15#remarks

**Comment by rothja** [comment] 2020-03-17 17:34
@saryeHaddadi Thank you for the very detailed information from your research! I am going to reopen this using your details to reach out to the product team for consideration. Thank you.

**Comment by saryeHaddadi** [comment] 2020-03-18 08:28
@rothja You welcome

**Comment by rothja** [comment] 2020-04-28 12:16
@saryeHaddadi and all, thanks again for reporting this problem. It looks like it has been reported formally in our SQL Server feedback channel [here](https://feedback.azure.com/forums/908035-sql-server/suggestions/33675151-sys-sp-cdc-generate-wrapper-function-does-not-gene). I would recommend that everyone experiencing this issue go to the feedback post and upvote it so that it can get higher priority for a fix. As of now, this appears to be a product bug. I apologize for the inconvenience or block this is causing anyone, but I hope that some of the workarounds in the [stackoverflow posts](https://stackoverflow.com/search?q=__%24command_id) help provide temporary work arounds.

**Closed by rothja** 2020-04-28 12:16 UTC
Labels: Pri2, doc-bug, sql/prod, system-objects/tech

**Comment by fabrizziocht** [comment] 2022-10-17 05:50
Hello, do we have any news about this bug? I was testing recently with Sql Server 2019 15.0.4261.1 and Sql Server 2022 16.0.950.9 but the template still generates the non existing column `__$command_id` using `sys.sp_cdc_generate_wrapper_function`.

**Comment by rothja** [comment] 2022-10-17 14:59
@fabrizziocht I'm sorry you're still seeing this error. I don't have any visibility into where this is at internally. I would recommend continuing to upvote the problem on our feedback site. That site changed since the last time I recommended this. Here is the new link to what I think is the same issue:

[sys.sp_cdc_generate_wrapper_function does not generate valid functions](https://feedback.azure.com/d365community/idea/00888e1f-7d25-ec11-b6e6-000d3a4f0da0)

If you agree this is likely the same problem, you could considering upvoting and adding more detail in the comments section. I seached for $command_id but couldn't find it, because the detail on the error is not in this item. I'm sorry I don't have a better suggestion at this time for adding support for prioritizing this fix in the future.
