### ISSUE TITLE
Specify permissions required for Saving the Classification.

### ISSUE THREAD

**Issue by iSatishYadav** [MicrosoftDocs/sql-docs#2283] opened 2019-06-08 08:55 UTC
Specify what permissions are required to *View* and *Save* Classifications. I tried to Save classification, got the following error:
````
Failed to update tags for columns:

Schema:dbo, Table:XXX, Column:XXX, with exception: System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "XXX" because it does not exist or you do not have permissions.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.SqlServer.Management.ThreatDetection.DataClassification.Model.ColumnEntry.S (Microsoft.SqlServer.Management.ThreatDetection)
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @giladm
* Microsoft Alias: **giladm**

**Comment by MightyPen** [comment] 2019-06-09 02:16
@giladmit Hi Gilad, can you please process this Issue 2283.  If you deem that additional Security-related content is needed in the cited article, ideally you can create a PR to add that content.  In any case, please add a Comment here after you have assess this Issue 2283.

CC: @rothja @VanMSFT

**Comment by giladmit** [comment] 2019-06-10 15:46
adding @TomerWeisberg @salexu @ronitr as I am no longer part of this product group

**Comment by salexu** [comment] 2019-06-11 08:46
+ @Michal Bar<mailto:Michal.Bar@microsoft.com>, our new PM

**Comment by VanMSFT** [comment] 2019-06-11 14:31
Following up with Michal

**Comment by WilliamAntonRohm** [comment] 2019-07-16 20:42
@VanMSFT -- please look into this aging issue 2283.

**Comment by VanMSFT** [comment] 2019-07-18 07:24
Looking into it.

**Comment by VanMSFT** [comment] 2019-09-17 17:16
Hello @iSatishYadav! Thanks for submitting this feedback. I can reproduce your error, and will work with our Product Team on updating the documentation with permissions. Since we are tracking this internally, I will close this GitHub Issue. Please feel free to let us know if you have any concerns. Thanks again!

User Story 1600211

#please-close

**Closed by VanMSFT** 2019-09-17 17:16 UTC
Labels: Pri2, assigned-to-author, doc-enhancement, sql-database/svc
