### ISSUE TITLE
Need update: 

### ISSUE THREAD

**Issue by shahchi1** [MicrosoftDocs/sql-docs#5092] opened 2020-07-02 10:49 UTC
"Encrypted data compresses significantly less than equivalent unencrypted data. If transparent data encryption is used to encrypt an entire database, compressing backups might not reduce their size by much, if at all."

The above is no longer correct staring with SQL 2016 as it supports compression of the TDE enabled databases. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1e777-79fe-b553-8af7-6dbd7083a8a8
* Version Independent ID: 23a4cc37-e0ec-0fad-e206-efc5c88de482
* Content: [Backup Compression (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/backup-compression-sql-server?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/backup-compression-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/backup-compression-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment] 2020-07-02 18:33
@shahchi1 -- Chirag, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by WilliamAntonRohm** [comment] 2020-07-02 18:35
Duplicate of #5093

**Closed by WilliamAntonRohm** 2020-07-02 18:35 UTC
Labels: Pri2, assigned-to-author, backup-restore/tech, doc-bug, duplicate, sql/prod
