### ISSUE TITLE
XACT_ABORT is ON in triggers

### ISSUE THREAD

**Issue by branko-d** [MicrosoftDocs/sql-docs#3107] opened 2019-10-03 07:57 UTC
As far as I have tested, XACT_ABORT is ON in triggers, even when it's OFF in the calling code.

If this is always the case, that should be documented., If there are exceptions, they should be documented. If this is intended (or not) to stay that way in future versions of SQL Server, that should also be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9fdd49-3145-7ae3-bf90-47f002895264
* Version Independent ID: 075116a4-7a22-3816-9782-079952bc0fe7
* Content: [SET XACT_ABORT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-xact-abort-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/set-xact-abort-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/set-xact-abort-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment] 2019-10-03 17:17
@branko-d -- thank you for your feedback.

@CarlRabeler -- please look into this issue 3107.

**Comment by CarlRabeler** [comment] 2019-10-03 17:36
@branko-d Thanks for submitting this issue. Can you please provide some sample code showing your testing / so I can reproduce it? Meanwhile, I am researching.
Carl

**Comment by branko-d** [comment] 2019-10-04 09:12
@CarlRabeler Sure, you can just use the code that detects the current XACT_ABORT value (as documented in the linked doc page itself), and put it inside the trigger:

```
CREATE TABLE A (
    A_ID int PRIMARY KEY
);

GO

CREATE TRIGGER A_INSTEAD_OF_INSERT_UPDATE_DELETE
ON A
AFTER INSERT
AS
    IF ((16384 & @@OPTIONS) = 16384)
        PRINT 'Inside trigger: XACT_ABORT = ON';
    ELSE
        PRINT 'Inside trigger: XACT_ABORT = OFF';

GO

IF ((16384 & @@OPTIONS) = 16384)
    PRINT 'Outside trigger: XACT_ABORT = ON';
ELSE
    PRINT 'Outside trigger: XACT_ABORT = OFF';

INSERT INTO A VALUES (10);
```

Which prints the following under my SQL Server 2017 Developer:

```
Outside trigger: XACT_ABORT = OFF
Inside trigger: XACT_ABORT = ON

(1 row affected)
```

**Comment by rothja** [comment] 2019-10-10 14:05
@branko-d Thanks for the question. @CarlRabeler is out of the office for the next few weeks. @VanMSFT could you please continue to look into this and see if we need a doc change and/or further investigation. Thank you!

**Comment by VanMSFT** [comment] 2019-10-10 14:30
Following up with engineering.

**Comment by mottykohn** [comment] 2019-11-07 15:02
Isn't this clearly documented on this page? 

> OFF is the default setting in a T-SQL statement, while ON is the default setting in a trigger.

**Comment by branko-d** [comment] 2019-11-08 14:52
> 
> 
> Isn't this clearly documented on this page?
> 
> > OFF is the default setting in a T-SQL statement, while ON is the default setting in a trigger.

Ah, sorry, I see it now.

Should be less "buried" though - at least its own paragraph.

**Comment by VanMSFT** [comment] 2019-11-13 12:15
Thanks @mottykohn and @branko-d! Since this has been solved, we'll go ahead and close this issue. If there are any concerns, please let us know.

**Closed by VanMSFT** 2019-11-13 12:15 UTC
Labels: Pri1, assigned-to-author, doc-provided, sql/prod, t-sql/tech
