### ISSUE TITLE
Wrong SQL Server lifecycle informations in the global MS product export

### ISSUE THREAD

**Issue by maaaaz** [MicrosoftDocs/sql-docs#7785] opened 2022-07-12 08:18 UTC
Hello there,

[Here](https://docs.microsoft.com/en-us/lifecycle/products/export/) are some wrong information.

As a single example, this is the policy written for SQL Server 2014 SP2
![image](https://user-images.githubusercontent.com/1863158/178443407-0c9a1ec0-be29-4833-a6f3-b2401556fa59.png)

This is not the same as [here](https://docs.microsoft.com/en-us/lifecycle/products/sql-server-2014), where it is written that the SP2 ends Jan 14, 2020:
Version | Start Date | End Date
-- | -- | --
Service Pack 3 | Oct 30, 2018 | Jul 9, 2024
Service Pack 2 | Jul 14, 2016 | Jan 14, 2020
Service Pack 1 | Apr 14, 2015 | Oct 10, 2017
Original Release | Jun 5, 2014 | Jul 12, 2016

Could you fix information in the lifecycle product export please ?

Best regards.

**Comment by WilliamAntonRohm** [comment] 2022-07-12 19:38
@maaaaz -- Thomas, thank you for your feedback.  I am investigating.

**Comment by WilliamAntonRohm** [comment] 2022-07-26 22:32
@maaaaz -- Thomas, my apologies for the delay.

@v-jasric -- Jason, please look into this issue.

**Comment by v-jasric** [comment] 2022-07-27 01:31
Hi @maaaaz and @WilliamAntonRohm , 

The export is working as intended. Perhaps our documentation needs some work. The Mainstream End Date, Extended End Date, and Retirement Date are dates for the product, not the individual releases. Each record contains the overall product support dates. 

Release dates are found in the Release Start Date and Release End Date columns. For SQL 2014 SP2, these dates show that the SP2 release ended on Jan. 14, 2020.

![image](https://user-images.githubusercontent.com/64614983/181140860-061e47d0-ded1-44ab-8bdc-82ae0fd4012c.png)

**Comment by maaaaz** [comment] 2022-07-27 22:26
Hello @v-jasric and @WilliamAntonRohm,

Thanks for the information. 
It is indeed not intuitive that the overall data is related to the product and not the release, as there are multiple rows for the same product with the "release" field being the difference for the rows.

Cheers !

**Comment by WilliamAntonRohm** [comment] 2022-07-27 23:20
@maaaaz -- Thomas, thank you for your follow-up!

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Closed by WilliamAntonRohm** 2022-07-27 23:20 UTC
Labels: sql/prod, doc-bug, assigned-to-author, Pri3
