### ISSUE TITLE
Block Blob limits

### ISSUE THREAD

**Issue by tschleining** [MicrosoftDocs/sql-docs#2143] opened 2019-05-15 12:54 UTC
The section #blockbloborpageblob state "When you backup to block blob, the maximum block size you can specify is 4MB. The maximum size of a single block blob file is 4MB * 50000 = 195GB. If your database is larger than 195GB, we recommend you:"  As per https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets#azure-blob-storage-scale-targets these maximums have been updated.  Does this document need to be updated to reflect those values or does BackupToURL.exe use a specific API version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc04e819-4cfd-5b23-404b-8d4ed41afd21
* Version Independent ID: d254a232-e05d-0d52-0e25-7e83866f12e6
* Content: [SQL Server Backup to URL - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2017#blockbloborpageblob)
* Content Source: [docs/relational-databases/backup-restore/sql-server-backup-to-url.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-backup-to-url.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment] 2019-05-16 00:09
Hi @tschleining! Thank you for bringing this to our attention. I'm assigning this issue to my colleague, Mike who will help clarify and update the documentation as needed.

**Comment by MikeRayMSFT** [comment] 2019-05-20 21:53
@tschleining checking with some colleagues to confirm. Thank you for the submission.

**Comment by MikeRayMSFT** [comment] 2019-06-05 22:35
@tschleining - SQL Server Backup to Block Blob uses a specific API version by design.

**Closed by MikeRayMSFT** 2019-06-05 22:35 UTC
Labels: assigned-to-author, backup-restore/tech, sql/prod
