### ISSUE TITLE
Ubuntu 20.04 Can't Install msodbcsql17

### ISSUE THREAD

**Issue by calebsyring** [MicrosoftDocs/sql-docs#5277] opened 2020-07-31 23:32 UTC
Under the [Ubuntu instructions](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017#ubuntu17) it says you can download the 20.04 prod.list (`curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list`) and subsequently install msodbcsql17 (`sudo ACCEPT_EULA=Y apt-get install msodbcsql17`), but the 20.04 package repository doesn't have msodbcsql17 yet. Following the Ubuntu 20.04 instructions to the letter will result in `E: Package 'msodbcsql17' has no installation candidate`. It would be helpful to have working instructions on what to do to install the odbc driver on Ubuntu 20.04, even if that is just to say to install the 18.04 package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment] 2020-07-31 23:44
@calebsyring -- Caleb, thank you for your feedback.

@David-Engel -- David, please look into this issue.

**Comment by rsyring** [comment] 2020-07-31 23:56
FWIW, I think this is likely a packaging issue and not a documentation issue.

If you look at the [Packages file](https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages) for the Ubuntu 20.04 release, it is missing a number of packages including msodbcsql17.  Compare that to the Ubuntu 18.04 [Packages file](https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages) for example and you will see a lot of missing packages.

It's interesting though since the msodbcsql17 `.deb` is actually in the pool:

https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msodbcsql17/msodbcsql17_17.6.1.1-1_amd64.deb

**Comment by WilliamAntonRohm** [comment] 2020-08-01 00:11
@rsyring -- thank you for clarifying.  Please raise this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Closed by WilliamAntonRohm** 2020-08-01 00:11 UTC
Labels: Pri2, assigned-to-author, cba, connectivity/tech, doc-bug, sql/prod

**Comment by David-Engel** [comment] 2020-08-01 00:23
It's a publishing issue. I'm on it.

**Comment by rsyring** [comment] 2020-08-01 00:35
@David-Engel thank you for working on this.  Should I still file a new issue in SQL Server Feedback?

**Comment by David-Engel** [comment] 2020-08-01 00:42
No need. It should be fixed now. Testing...

**Comment by David-Engel** [comment] 2020-08-01 00:58
Works for me now. If it doesn't work for you, try again in a little while. It might take some time to sync to various replica servers.

**Comment by rsyring** [comment] 2020-08-01 22:24
Confirmed this is now fixed.  I have to say, it's really cool to see Microsoft so responsive to such issues.  Thanks @David-Engel for getting this resolved quickly!
