### ISSUE TITLE
yum check-update fails on RHEL

### ISSUE THREAD

**Issue by cheenamalhotra** [MicrosoftDocs/sql-docs#2445] opened 2019-07-06 23:09 UTC
Running on RHEL 7.4 image:

$ sudo yum check-update
Loaded plugins: langpacks, product-id, search-disabled-repos
Repository packages-microsoft-com-mssql-server-2017 is listed more than once in the configuration

kernel.x86_64                                 3.10.0-693.50.3.el7                       rhui-rhel-7-server-rhui-eus-rpms
kernel-tools.x86_64                           3.10.0-693.50.3.el7                       rhui-rhel-7-server-rhui-eus-rpms
kernel-tools-libs.x86_64                      3.10.0-693.50.3.el7                       rhui-rhel-7-server-rhui-eus-rpms
libgudev1.x86_64                              219-42.el7_4.16                           rhui-rhel-7-server-rhui-eus-rpms
microcode_ctl.x86_64                          2:2.1-22.23.el7_4                         rhui-rhel-7-server-rhui-eus-rpms
python-perf.x86_64                            3.10.0-693.50.3.el7                       rhui-rhel-7-server-rhui-eus-rpms
systemd.x86_64                                219-42.el7_4.16                           rhui-rhel-7-server-rhui-eus-rpms
systemd-libs.x86_64                           219-42.el7_4.16                           rhui-rhel-7-server-rhui-eus-rpms
systemd-python.x86_64                         219-42.el7_4.16                           rhui-rhel-7-server-rhui-eus-rpms
systemd-sysv.x86_64                           219-42.el7_4.16                           rhui-rhel-7-server-rhui-eus-rpms
Update notice RHBA-2018:0042 (from rhui-rhel-7-server-rhui-eus-rpms) is broken, or a bad duplicate, skipping.
You should **report this problem to the owner of the rhui-rhel-7-server-rhui-eus-rpms repository**.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.

**Comment by MightyPen** [comment] 2019-07-08 09:45
@cheenamalhotra Hello Cheena, Is there a specific article, in GitHub repo= 'sql-docs-pr', under `https://docs.microsoft.com/sql/` or `https://docs.microsoft.com/sql/linux/`, that is closely associated with your product bug report here in Issue 2445?
If yes, I am guessing the article might be the following?:

- H1 Title: "Create and configure an availability group for SQL Server on Linux"
   - GitHub directory path=  docs/linux/sql-server-linux-create-availability-group.md
   - `https://docs.microsoft.com/sql/linux/sql-server-linux-create-availability-group`

@David-Engel Hi David, is this Issue #2445 one that you can help with, by.....
- "..... report this problem to the owner of the rhui-rhel-7-server-rhui-eus-rpms repository." ? 
Please keep @MikeRayMSFT notified as you post Comments here.
 
CC: @MikeRayMSFT Mike, I am co-assigning this Issue #2445 to you. Perhaps all you will need to do is monitor whether @David-Engel can help process this.
. .

**Comment by cheenamalhotra** [comment] 2019-07-08 18:18
I was running commands from here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-2017#install-tools-on-rhel-7

![image](https://user-images.githubusercontent.com/13396919/60832794-a0a42880-a171-11e9-835c-a26462866810.png)

Also I don't think @David-Engel is the right person to contact as we are in the same (SQL Client Drivers) team, whereas this seems to be an issue either for Documentation team or (rhui-rhel-7-server-rhui-eus-rpms) package owners.

**Comment by Kavita-2703** [comment] 2019-07-29 04:48
Hello , I am facing similar error on RHEL 7.4 , while trying to check-update for WALinuxAgent :

root@redhat74 ~]# yum check-update WALinuxAgent --verbose
Not loading "rhnplugin" plugin, as it is disabled
Loading "langpacks" plugin
Loading "product-id" plugin
Loading "search-disabled-repos" plugin
Not loading "subscription-manager" plugin, as it is disabled
Adding en_US.UTF-8 to language list
Config time: 0.061
Yum version: 3.4.3
rpmdb time: 0.000
Building updates object
Setting up Package Sacks
pkgsack time: 0.018
up:Obs Init time: 0.398
up:simple updates time: 0.014
up:obs time: 0.003
up:condense time: 0.000
updates time: 0.857
Duplicate of RHBA-2018:0042 differs in some fields:
<<<<<<< rhui-rhel-7-server-rhui-eus-rpms:version
'3'
=======
'2'
>>>>>>> rhui-rhel-7-server-rhui-eus-optional-rpms:version
Update notice RHBA-2018:0042 (from rhui-rhel-7-server-rhui-eus-rpms) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the rhui-rhel-7-server-rhui-eus-rpms repository.
If you are the owner, consider re-running the same command with --verbose to see the exact data that caused the conflict.
updateinfo time: 1.691

**Comment by David-Engel** [comment] 2019-07-29 18:04
Does the error happen without performing the following command?
`curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/msprod.repo`

Because this appears to be an issue with one of RedHat's servers:
"..... report this problem to the owner of the rhui-rhel-7-server-rhui-eus-rpms repository."

You would need to contact RedHat to have them resolve it. (I don't know exactly where...)

@cheenamalhotra @Kavita-2703 @MightyPen @MikeRayMSFT

**Comment by MikeRayMSFT** [comment] 2019-07-30 16:03
@vin-yu  is this something you can look at with us?

**Comment by MightyPen** [comment] 2019-08-23 19:01
@vin-yu Hi Vinson,  A request:  Can you please add a Comment into this Issue #2445 , to indicate your thoughts for a fix, or to clarify that you cannot help in this particular area.

@MikeRayMSFT Hi Mike, We need to identify Who in the SQL realm knows enough about this particular Issue to help identify a fix.  Maybe you can ask around and help us identify someone?

@rothja This Issue will soon be two months old.  I think this involves an article under docs/linux/.  And it involves Red Hat Enterprise Linux (RHEL), I think.  Any ideas on how to make progress on this would be welcome.

Thanks.

cc: @WilliamAntonRohm

**Comment by MikeRayMSFT** [comment] 2019-09-23 21:49
I haven't been able to repro. Checking.

**Comment by MikeRayMSFT** [comment] 2019-09-23 21:54
This seems to be more of a RHUI (red hat licensing service) issue. Please contact Red Hat support for assistance.

**Closed by MikeRayMSFT** 2019-09-23 21:54 UTC
Labels: Pri3, assigned-to-author, product-feedback
