### ISSUE TITLE
A member of the role db_owner can execute sp_updatestats for Azure SQL Database.

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/sql-docs#8557] opened 2023-02-02 06:06 UTC
The document below says,
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-updatestats-transact-sql.md#permissions
> To run sp_updatestats, the user must be the owner of the database (the dbo, not just member of the role db_owner) or to be member of the sysadmin fixed server role.

However, a member of the role db_owner could execute sp_updatestats for Azure SQL Database. Could you please fix the document for Azure SQL Database?

```
exec sp_helptext sp_updatestats;

 -- Check the user sysadmin, dbo or member of db_owner when the engineedition is 5 which is the edition for SQL Azure  
 if not is_srvrolemember('sysadmin') = 1 and suser_sid() <> @dbsid and not (is_rolemember('db_owner') = 1 and SERVERPROPERTY('engineedition') = 5)  
...
```

**Comment by WilliamAntonRohm** [comment] 2023-02-03 02:42
@LifeRyuto -- Ryuto, thank you for your detailed feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by N-Kannan** [comment] 2023-04-15 14:51
@WilliamAntonRohm can you assisn me this I can work on it. I have good experience in sql.

**Comment by sshen-pcr** [comment] 2023-04-17 20:31
so it has been confirmed that a member of db_owner role can indeed execute this procedure, right?
How do I get the ddl of this procedure?

**Comment by WilliamAntonRohm** [comment] 2023-04-18 18:30
@N-Kannan -- Kannan, thank you again for your offer.  Please see this comment:  https://github.com/MicrosoftDocs/sql-docs/issues/8830#issuecomment-1513620328.

**Comment by N-Kannan** [comment] 2023-04-18 19:58
Thanks @WilliamAntonRohm I will create a pull request once I update all

**Comment by WilliamDAssafMSFT** [comment] 2023-04-25 04:30
> Thanks @WilliamAntonRohm I will create a pull request once I update all

@N-Kannan please issue one pull request per fix.

**Comment by N-Kannan** [comment] 2023-04-25 04:50
@WilliamDAssafMSFT i am working it due to my work schedule little delay I will in 4 days

**Comment by N-Kannan** [comment] 2023-05-02 16:26
@WilliamAntonRohm can you check my pr and close the issue

**Comment by WilliamAntonRohm** [comment] 2023-05-03 23:56
@N-Kannan -- Kannan, thank you for your contributions.

@markingmyname, @WilliamDAssafMSFT -- Mark or William, please review these changes.

**Comment by WilliamDAssafMSFT** [comment] 2023-06-27 17:36
Closing as this Issue has been addressed in another PR.

**Closed by WilliamDAssafMSFT** 2023-06-27 17:36 UTC
Labels: doc-bug, Pri3
