### ISSUE TITLE
Default Localize

### ISSUE THREAD

**Issue by Mnior** [MicrosoftDocs/sql-docs#4838] opened 2020-05-23 19:47 UTC
> If there is no localized version of the message, the U.S. English version is used.

This is wrong.
This is only true if this is a custom message (> 50000) or English localization of Operation System.
For system errors (< 50000), localization of OS will be used.

For example, test this code for two servers:
```
EXEC sp_addmessage 50001,16,'English Message'	,'English'
EXEC sp_addmessage 50001,16,'Русское сообщение'	,'Russian'
--SELECT * FROM sys.messages WHERE message_id IN (23100,50001) AND language_id IN (1033,1049,1025)
SET Language Arabic
RAISERROR(23100,16,1)
RAISERROR(50001,16,1)
EXEC sp_dropmessage 50001,'Russian'
EXEC sp_dropmessage 50001,'English'
```
On Server with English localization:
```
Changed language setting to Arabic.
Msg 23100, Level 16, State 1, Line 5
Invalid input parameter(s).
Msg 50001, Level 16, State 1, Line 6
English Message
```
On Server with Russian localization:
```
Параметры языка изменены на "Arabic".
Msg 23100, Level 16, State 1, Line 5
Недопустимые входные параметры.
Msg 50001, Level 16, State 1, Line 6
English Message
```
As you can see, localization mixes unpleasantly. Users can see messages in three languages (Russian, English, Arabic in this case). For FORMATMESSAGE, this works the same way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a768b81-c094-3a48-a8d5-0697ce6b78d7
* Version Independent ID: 65ae8973-f433-a826-d779-4ac4feb54f1c
* Content: [FORMATMESSAGE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/formatmessage-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/formatmessage-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/formatmessage-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment] 2020-05-26 22:24
@Mnior -- thank you for your feedback.  Please add your concern here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)


@julieMSFT -- please look into this issue.

**Comment by julieMSFT** [comment] 2020-05-28 20:06
@Mnior Hello, thank you for contacting Microsoft. I am looking into this.

**Comment by MashaMSFT** [comment] 2020-05-29 21:56
Hi @mnior, thanks for contacting Microsoft and bringing this to our attention! So, actually, I was unable to reproduce the issue, and I suspect it might be something with your SSMS environment rather than SQL Server. I am using Win10, SQL Server 2017 and SSMS version 15.0.18330.0. Note that my SSMS menus are in English - are yours? And if they're in Russian, did you do anything extra to configure that, or was it always Russian? And what OS and version of SQL Server are you using? 

I set my OS to Russian, set my language to Arabic, and raised the 23000 error - the response was in English (as the doc suggests it would be). However, I noticed a discrepancy between your and my environment, so maybe that's the cause? 

I set my language to Russian in my OS: 
![image](https://user-images.githubusercontent.com/32783170/83308041-d05d8400-a1ba-11ea-8f17-e4b6407ed574.png)

I set my language to Russian in SQL Server: 
Язык изменен на русский.

I then set it to Arabic: 
SET Language Arabic
Changed language setting to Arabic.
(what's interesting to me here is that my message is in English, despite the fact that my OS is in Russian, and your message is in Russian - this is the discrepancy I'd like get a better understanding of). 

When I run the error, it's in English: 
RAISERROR(23100,16,1)
Msg 23100, Level 16, State 1, Line 20
Invalid input parameter(s).

So I was unable to reproduce the behavior you're seeing, my error is in English as the doc indicates. If you can provide me with a better understanding of your environment, I can try to set up a repro with greater parity. 

Thanks!
Masha from the SQL Docs team


@Matteo-T  @markingmyname  fyi

**Comment by Mnior** [comment] 2020-06-02 15:49
Hi, MashaMSFT. Thanks for reply. I will answer your questions.

> I suspect it might be something with your SSMS environment rather than SQL Server.

I`m work from single workspace: Win10 & SSMS 17.9.1 - all are English native.

> And what OS and version of SQL Server are you using?

Many servers use different versions of OS & SQL Server and different localities.
Our solutions using user locality and also custom SQL messages.
In this case, I noticed that Russian version of OS are influence to the logic of the translations.
Our client will install "**Windows Server 2016 Standard Russian**".
In later instalation of "English Language Localization" did not affect the situation.

> I set my language to Russian in my OS:

I think that there is a big difference in how OS is installed.

Image from properties of two servers: 
![DefaultLang](https://user-images.githubusercontent.com/35436626/83540968-afba6480-a501-11ea-88f7-c61d9596bf3e.png)

As you see client locality is English, but servers returns same property (SQL Server Platform) in the same value but different localization. This can be seen by the explicitly called system procedure: `exec master.dbo.xp_msver`
Russian Server return: `Английский (США)`
English Server return: `English (United States)`

**Comment by julieMSFT** [comment] 2020-06-03 18:29
@Mnior Thank you for the additional information. We were able to reproduce the issue. I will update the doc the reflect the current behavior. You can file a feedback item at https://aka.ms/sqlfeedback or we can file it for you. If you file it, you will receive notifications and  can vote and monitor the progress more closely. Please let us know what you prefer. If we don't hear back from you in the next few days, we'll happily submit it on your behalf and link the created request here.

**Comment by julieMSFT** [comment] 2020-06-15 19:34
@Mnior We have updated the FORMAT message article with the current behavior. I have submitted your suggestion. You can view and up vote it at https://feedback.azure.com/forums/908035-sql-server/suggestions/40672060-consistent-user-message-locale-behavior . I will proceed with closing this issue. Thank you for contributing to Microsoft Docs! The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment] 2020-06-15 19:34
assign:MashaMSFT

**Comment by julieMSFT** [comment] 2020-06-15 19:37
#please-close

**Closed by julieMSFT** 2020-06-15 19:37 UTC
Labels: Pri3, assigned-to-author, doc-bug, sql/prod, t-sql/tech
