### ISSUE TITLE
No mention of errors that may occur using this catalog view

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#3814] opened 2019-12-16 11:45 UTC
Unfortunately when a database is in restoring state, this statement aborts.

SELECT * FROM sys.change_tracking_databases

Msg 927, Level 14, State 2, Line 50
Database 'OdysseyFMAPER' cannot be opened. It is in the middle of a restore.

Perhaps this could be fixed, or update the documentation if it is yet again, 'by design'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565cf882-171d-12e9-38bc-3d723fc2aead
* Version Independent ID: 0551f511-2847-4520-184c-332d797065d5
* Content: [sys.change_tracking_databases (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/change-tracking-catalog-views-sys-change-tracking-databases?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-catalog-views/change-tracking-catalog-views-sys-change-tracking-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/change-tracking-catalog-views-sys-change-tracking-databases.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment] 2019-12-16 17:24
Hi @brettshearer , thanks for bringing this to our attention! Let me look into this for you.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment] 2019-12-30 22:05
Hi @brettshearer , thank you for your patience as we looked into this for you!

While it is expected behavior for a database to be inaccessible during a restore operation, we can see how such an error might not be expected for a server-level view. The problem is that this view is querying metadata that exists at the database level, so if any of the databases are inaccessible, the query generates an error. This can be worked around by joining to sys.databases and including only online databases in the result set. Below is a query to return online databases with change tracking enabled.

SELECT 
    DB_NAME(ct.database_id) AS DBName, 
    ct.*
FROM sys.change_tracking_databases ct
INNER JOIN sys.databases d 
    ON d.database_id = ct.database_id
WHERE
    d.state_desc <> 'ONLINE';

We do not feel that documenting this behavior is necessary as it is expected behavior. However, if this behavior is causing you a business issue and/or you feel that it should behave differently, please feel free to file a feedback item at https://aka.ms/sqlfeedback and our engineering team will be happy to triage the issue.

I hope that helps and please let us know if we can be of further assistance. Otherwise, we will proceed with closing out this Git Issue in a few business days. 

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment] 2020-01-03 00:41
Hi @brettshearer , it's been some time since we've heard from you. I'm going to assume that your question was addressed and close out this Git Issue. However, please feel free to comment should you need anything further.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Closed by MashaMSFT** 2020-01-03 00:41 UTC
Labels: Pri2, sql/prod, system-objects/tech
