### ISSUE TITLE
tutorial doesn't work

### ISSUE THREAD

**Issue by Hevgen** [MicrosoftDocs/sql-docs#8521] opened 2023-01-24 12:04 UTC
The section "Prerequisites" includes commands to install python packages that don't install all required packages actually. Package "sklearn" isn't installed correctly in this way.
So the code from the next tutorial page (https://learn.microsoft.com/en-us/sql/machine-learning/tutorials/python-clustering-model-prepare-data?view=sql-server-ver16) just doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8ec2d0-c578-6c0a-72f9-6f76bde73490
* Version Independent ID: 65286e86-1042-bb5f-ce10-a7c20ed07e5b
* Content: [Python tutorial: Categorize customers - SQL machine learning](https://learn.microsoft.com/en-us/sql/machine-learning/tutorials/python-clustering-model?view=sql-server-ver16)
* Content Source: [docs/machine-learning/tutorials/python-clustering-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-clustering-model.md)
* Service: **sql**
* Sub-service: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment] 2023-01-24 20:58
@Hevgen -- thank you again for your considered feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment] 2023-01-30 21:51
Thanks @Hevgen for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to look further into this with the product team and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment.

**Comment by WilliamDAssafMSFT** [comment] 2023-01-30 23:02
@Hevgen-
Some questions:

1. "Package "sklearn" isn't installed correctly in this way."  Can you be specific in what way `pip install sklearn` doesn't install sklearn correctly? Can you provide any error messages or steps to reproduce?
2. What version of SQL Server are you attempting this tutorial on? And Platform (windows, linux, or SQL MI?)
3. What version of Python is installed?

To add, it might be easier for you to create a Pull Request to demonstrate the change or part of the change, instead of trying to describe the change. To give you credit as a contributor to the article, would you like to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself? By opening a pull request, you're collaborating with the authors to add changes directly to the documentation. After the updated article is published, GitHub lists you as an article contributor. Select the "Edit" pencil at the top of the article to begin a pull request on our open source docs. You can reference this issue and my GitHub in your pull request, and I'll personally review and carry it across the finish line. Either way, thanks for your feedback! Closing this issue for now. If you'd rather not create a pull request, we can handle the update.

**Comment by Hevgen** [comment] 2023-02-24 12:53
> 1. "Package "sklearn" isn't installed correctly in this way."  Can you be specific in what way `pip install sklearn` doesn't install sklearn correctly? Can you provide any error messages or steps to reproduce?

I was tried weeks ago. Now i got that result:
_> pip install sklearn
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sklearn in c:\users\hevge\appdata\roaming\python\python39\site-packages (0.0.post1)_
So it installed version _0.0.post1_. I'm not so known at Python. I tried in few ways with the same result: version 0.0.post1 installed.

> 2. What version of SQL Server are you attempting this tutorial on? And Platform (windows, linux, or SQL MI?)
MS SQL Server 2022 Developer edition under Windows 11 Home.

> 3. What version of Python is installed?
3.9 and 3.10. The same result for both.

Here additionally for 3.10:
_C:\Program Files\Python310\Scripts>pip install sklearn                                            Collecting sklearn                                                                                  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)                                                    Preparing metadata (setup.py) ... done                                                          Installing collected packages: sklearn                                                              DEPRECATION: sklearn is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559                                                Running setup.py install for sklearn ... done                                                   Successfully installed sklearn-0.0.post1_  

> To add, it might be easier for you to create a Pull Request to demonstrate the change or part of the change, instead of trying to describe the change. 
I don't know what changes should be done. I'm learning. I just know that I have tried according to the article and it doesn't work properly.

**Comment by WilliamDAssafMSFT** [comment] 2023-03-15 23:09
@Hevgen It looks like [https://pypi.org/project/sklearn/](https://pypi.org/project/sklearn/) has been sunset in December. This is an external open source package not controlled by Microsoft, this stuff is expected over time. We'll need to update our doc samples! That is in flight. Meanwhile, per the same site, use `pip install scikit-learn` rather than `pip install sklearn`. 

Thanks @Hevgen for taking the time to provide this feedback, your suggestions help improve our documentation.

**Closed by WilliamDAssafMSFT** 2023-03-15 23:09 UTC
Labels: doc-bug, assigned-to-author, Pri2, sql/svc, machine-learning/subsvc
