### ISSUE TITLE
Signing an Assembly = Signing with Strong Name Key

### ISSUE THREAD

**Issue by legistek** [MicrosoftDocs/sql-docs#2052] opened 2019-05-03 13:47 UTC
It's not clear from the documentation what kind of assembly signing is required. Through trial and error I determined that the assembly needs to be signed with a strong name key. Signing with SIGNTOOL using a code-signing certificate doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc10b70-11b5-a892-da24-fe25fa86c8c2
* Version Independent ID: 9c95ecb5-175c-d8e7-22d3-a81f1f58f6c3
* Content: [CREATE ASSEMBLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-assembly-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-assembly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-assembly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MikeRayMSFT** [comment] 2019-05-03 22:36
@legistek - thank you for noting this. We'll take a look and get back to you.

**Comment by MightyPen** [comment] 2019-05-03 23:12
@MikeRayMSFT Yes Mike, I will take and fix this Issue 2052.

(https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)

**Comment by legistek** [comment] 2019-05-06 12:30
Thanks both. I want to update this because it's more subtle than I thought. 

It looks like generally speaking assemblies signed with code signing certificates (SIGNTOOL) do qualify for being eligible for UNSAFE. 

Where I was hitting a snag was trying to create the asymmetric key using the assembly.

> CREATE ASYMMETRIC KEY [MyKey]
> FROM EXECUTABLE FILE = 'MyAssembly.dll' 

In that case `MyAssembly.dll` apparently has to be signed with a strong name key - signing using a code signing cert is not sufficient. 

On the other hand, I *can* use a code-signing-cert-signed file with `CREATE CERTIFICATE`.

So in sum, it looks like whether a strong name key or a code-signing cert is required depends on the method used to create the account that will have the `UNSAFE ASSEMBLY` permission. If creating the account from a certificate, you need to use a code signing cert on the assembly., If creating from an asymmetric key, you need to use a strong name key to sign the assembly.

At least that's how it appears now. I could still be missing some subtleties here.  Either way it would be great if the docs were improved on this whole procedure since it's, as a practical matter, mandatory now for using SQL CLR. Thanks!

**Comment by srutzky** [comment] 2019-05-09 23:38
Hi @MightyPen . Please do not make any changes, or at least let me handle them.

@legistek : I am currently working on a post that will explain most of this, but I can add a little to explain all of it. The focus of the post/article is unsupported .NET Framework libraries, but the mechanisms are the same in all cases. Here are the basics:

1. A Strong Name Key is just a public/private key pair (i.e. an asymmetric key).
    1. An assembly can only be signed by one Strong Name Key.
    1. Signing an assembly in Visual Studio uses `sn.exe` which adds the strong name key to the assembly. `sn.exe` can also be executed manually. (see exception below)
    1. Starting in .NET Framework version 4.5 (I think), Strong Naming was updated to include 2 keys and is known as Enhanced Strong Naming. Enhanced Strong Naming is _not_ supported by SQLCLR.
    1. The strong name key can be pulled into SQL Server (public key only) via `CREATE ASYMMETRIC KEY`
        1. From the DLL (this is not ideal as it is external to the install script)
        1. From the SNK file (this is not ideal as it is external to the install script)
        1. From an Assembly already loaded into SQL Server (this is not ideal if it requires enabling `TRUSTWORTHY` in order to get the Assembly into SQL Server before the Asymmetric Key can be created -- please see "Solution 1" link in "General" section below for a work-around)
        1. No ideal mechanism exists – creating the Asymmetric Key from a `VARBINARY` literal – because Microsoft will not implement this: "[Allow Asymmetric Key to be created from binary hex bytes string just like CREATE CERTIFICATE](https://feedback.azure.com/forums/908035-sql-server/suggestions/32896978-allow-asymmetric-key-to-be-created-from-binary-hex)" (so **_please_** up-vote it!!!)
1. A Certificate is a public/private key pair (i.e. an asymmetric key) with additional meta-data to capture the originator, valid dates, brief description, etc.
    1. An assembly can be signed by multiple Certificates.
    1. Signing an assembly with a Certificate requires `signtool.exe` (see exception below)
    1. The Certificate can be pulled into SQL Server (public key + _optionally_ also private key) via `CREATE CERTIFICATE`
        1. From the DLL (this is not ideal as it is external to the install script)
        1. From the CER file (public key) (this is not ideal as it is external to the install script)
        1. From the PVK file (optional private key) (this is not ideal as it is external to the install script)
        1. From an Assembly already loaded into SQL Server (this is not ideal if it requires enabling `TRUSTWORTHY` in order to get the Assembly into SQL Server before the Certificate can be created)
        1. From a `VARBINARY` literal (i.e. hex bytes) (this _IS_ ideal as it is pure T-SQL)
        1. For more details on creating / restoring Certificates, please see: "[Can a Certificate’s Private Key be Imported / Restored From a Binary Literal / Hex Bytes ?](https://sqlquantumleap.com/2019/04/22/can-a-certificates-private-key-be-imported-restored-from-a-binary-literal-hex-bytes/)"
    1. Certificates _probably_ require using an SHA1 hash of the key and not anything better / stronger due to SQL Server only supporting SHA1 hashes (I believe, but I haven't confirmed yet). Meaning, if an Assembly is signed only with a Certificate using an SHA2_256 hash, this _might_ not be recognized for the purposes of SQLCLR security (but again, I have _not_ confirmed this).
1. General
    1. Whether you have an Asymmetric Key or Certificate, you simply create a Login from it and grant `UNSAFE ASSEMBLY` to that signature-based Login.
    1. You _can_ sign assemblies with either an Asymmetric Key or Certificate _after_ they have been loaded into SQL Server, but the only reason to use this is to get previous unsigned Assemblies that were loaded prior to SQL Server 2017 (or newer) but existing in a database that was upgraded to SQL Server 2017 (or newer). Please see "[SQLCLR vs. SQL Server 2017, Part 4: “Trusted Assemblies” – The Disappointment](https://sqlquantumleap.com/2017/08/28/sqlclr-vs-sql-server-2017-part-4-trusted-assemblies-the-disappointment/)" for details.
    1. For instructions on how to automate setting up ideal security, in a way that can be done manually or even via Visual Studio / SSDT, using both an Asymmetric Key and a Certificate (used to load the Asymmetric Key because it is currently the only way to create the security via a `VARBINARY` literal), please see: "[SQLCLR vs. SQL Server 2017, Part 2: “CLR strict security” – Solution 1](https://sqlquantumleap.com/2017/08/09/sqlclr-vs-sql-server-2017-part-2-clr-strict-security-solution-1/)".
    1. For instructions on how to automate setting up ideal security, in a way that can be done manually or even via Visual Studio / SSDT, using only a Certificate, please see: "[SQLCLR vs. SQL Server 2017, Part 3: “CLR strict security” – Solution 2](https://sqlquantumleap.wordpress.com/2017/08/16/sqlclr-vs-sql-server-2017-part-3-clr-strict-security-solution-2/)".

**Comment by MightyPen** [comment] 2019-05-10 17:46
@srutzky Thank you very much for your thoughtful and detailed response. I voted for your feature request.

**Comment by MightyPen** [comment] 2019-05-29 09:23
Closing. Thanks.

**Closed by MightyPen** 2019-05-29 09:23 UTC
Labels: assigned-to-author, product-question, sql/prod, t-sql/tech, triaged

**Comment by srutzky** [comment] 2019-05-29 20:54
@MightyPen Your are welcome. And thank you for supporting my request to allow for creating asymmetric keys from a varbinary literal 😺 .
