### ISSUE TITLE
F1 help on @@VERSION fails to access Docs site

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/sql-docs#7794] opened 2022-07-13 03:29 UTC
Issue: Access Denied 403 when search for @@VERSION

Issue 95689(https://github.com/MicrosoftDocs/azure-docs/issues/95689) has also opened on Docs root, as the following is not an SSMS issue but a firewall/route issue.

A warning on this Docs page is required while it is being fixed.

Add warning that:
searching on ```@@VERSION``` will show an error 403 page. Edit the URL manually to remove the query string and you will be able to access the Docs page https://docs.microsoft.com/en-us/sql/t-sql/functions/version-transact-sql-configuration-functions

Is OK if search for @@IDENTITY etc

**Comment by WilliamAntonRohm** [comment] 2022-07-13 18:58
@OzBob -- thank you for your well-researched feedback.

@MikeRayMSFT -- please look into this issue.

**Comment by rwestMSFT** [comment] 2022-07-18 22:03
Thanks @OzBob. I've closed the other issue because it's better suited to this repository. We'll definitely look into it, but we also have a backlog so it may take some time to resolve.

**Comment by rwestMSFT** [comment] 2023-03-20 19:57
@markingmyname Would you be able to assist with this?

**Comment by MikeRayMSFT** [comment] 2023-04-11 20:42
@OzBob - I've reproduced the problem. Will file a defect with the product group. 

I don't think this is really a documentation issue. Closing for now. WIll update with the defect identifier when it's filed.

**Closed by MikeRayMSFT** 2023-04-11 20:42 UTC
Labels: doc-bug, assigned-to-author, Pri3, sql/svc
