### ISSUE TITLE
SSMS F1 shortcut doesn't lead to sys.dm_hadr_cluster

### ISSUE THREAD

**Issue by zikato** [MicrosoftDocs/sql-docs#9659] opened 2024-02-08 12:56 UTC
Similar problem to #7068

The F1 keywords for that page are correct but redirect still doesn't work
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-hadr-cluster-transact-sql.md

SSMS version info:

SQL Server Management Studio						15.0.18390.0
SQL Server Management Objects (SMO)						16.100.46521.71
Microsoft Analysis Services Client Tools						15.0.19714.0
Microsoft Data Access Components (MDAC)						10.0.19041.3930
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19045

**Comment by rwestMSFT** [comment] 2024-02-09 19:02
Hi @zikato, we'll look into this, thanks! We have a project coming up where we're investigating all the existing and missing F1 tags, but no timeline promised.

**Comment by markingmyname** [comment] 2024-04-22 22:55
@zikato 

I tried the F1 and it seems to work.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/22989000/cddad0b1-6364-4827-9bb7-b47695d3f4ad)

When i highlighted the SPROC it directed me to the right page.

Are you still experiencing this?

**Comment by rwestMSFT** [comment] 2024-04-23 21:04
@zikato SSMS 18.x is no longer supported, since the release of 20.x. We didn't test this in SSMS 18, but in 19 and 20 it worked as expected. Can you try on a supported version of SSMS?

If we don't hear from you by the end of this week, I will close this issue, but you're welcome to continue the conversation below.

**Comment by zikato** [comment] 2024-04-23 21:18
Same behaviour in 18.x, 19 preview and 20.1.

Highlighting both schema and object works (`sys.dm_hadr_cluster`)
Highlighting just the object name doesn't work `dm_hadr_cluster`

**Comment by rwestMSFT** [comment] 2024-04-23 23:25
Thanks for the prompt reply, we'll keep digging.

**Comment by markingmyname** [comment] 2024-04-24 04:43
The experience is the entire Stored Procedure must be highlighted for the "F1" functionality to work as expected.

If you highlight just a portion of it (without the schema) it does not work.

I'll discuss with our product group to see if this behavior is by design and get back to you.

Thank you for being so passionate about our documentation.

**Comment by markingmyname** [comment] 2024-04-24 23:25
@zikato 

I've consulted with the engineers, and this is a bug.  in fact, we are discussing restructuring the entire F1 functionality process.

Unfortunately, I don't have an ETA to offer or even when we will start on this, but we do acknowledge it's a bug and now is on the radar to be reviewed.

We sincerely appreciate you bringing this to our attention.

However, this area is primarily for doc issues. To report product issues, the best way to reach out to the SSMS Team is at [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0).  Please submit a comment and have others vote on it so it gets more attention.

**Comment by markingmyname** [comment] 2024-04-24 23:25
As such, i am moving forward with closing this Issue.

Again, we apologize for not offering a better solution currently.

**Closed by markingmyname** 2024-04-24 23:25 UTC
Labels: sql/prod, assigned-to-author, Pri3
