### ISSUE TITLE
Logon Triggers: this is not the triggers overview page you are looking for 🙃

### ISSUE THREAD

**Issue by srutzky** [MicrosoftDocs/sql-docs#5027] opened 2020-06-22 20:40 UTC
The title, content, and even filename for this page all specify "Logon Triggers". Yet, the left-nav believes this page is the general "Triggers" overview page. In fact, there is no general triggers overview page.

What should happen:
1. Find and link actual trigger overview page to "Triggers" in the left-nav. If no general triggers page exists, create it and change the "Triggers" link to reference it.
2. Create new left-nav item, also under Triggers, for "Logon Triggers" and link this page to it.

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603be1d4-6a0c-7f06-b1f3-2c91c3414fd2
* Version Independent ID: 09928345-e61e-218c-bfcf-f08a830250b8
* Content: [Logon Triggers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/logon-triggers?view=sql-server-ver15)
* Content Source: [docs/relational-databases/triggers/logon-triggers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/logon-triggers.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment] 2020-06-23 18:33
@srutzky This does seem like a serious problem with the triggers documentation. I'll take a look and try to find the best solution. Thanks for raising this, Solomon. Your help with the documentation and customer issues is really apprecaited!

**Comment by rothja** [comment] 2020-06-23 18:33
@WilliamAntonRohm Can you add the appropriate labels and assign this to me? Thank you!

**Comment by rothja** [comment] 2020-06-30 18:53
@srutzky Solomon, I'm going to create a folder for Logon Triggers and put the two logon trigger articles in that folder. I'm going to move the trigger security article below these folders. There is no triggers overview although there is an overview for DDL and DML triggers in their respective folders. But I think this will help, and you definitely identified a confusion caused by the content architecture here. Thank you.

**Closed** 2020-06-30 20:01 UTC
Labels: /tech, Pri2, assigned-to-author, doc-bug, sql/prod

**Comment by srutzky** [comment] 2020-06-30 21:31
@rothja Hi Jason. Sounds good, though shouldn't there still be a general "Triggers" overview page, even if it's fairly minimal? I'm pretty sure I've seen that in many other places, where it's mainly a list of links to the sub-pages, in this case:
* DML
* DLL
* Logon

There can even be a generic statement along the lines of:

"Triggers are procedural code that is executed upon one or more events occurring. The various types of triggers are:"

**Comment by rothja** [comment] 2020-07-01 21:21
@srutzky It's a tough call. In the past in the SQL documentation, we had those types of index pages all over the place (and we still do). "The following section covers..." and it was a list of links. The current best practice is to make sure that any article is useful on its own, because people find the info through search. Ideally, we would have a more rich article on Triggers and the different types with some orientation of when-to-use-which. We can consider this type of improvement in the future. Thanks!
