### ISSUE TITLE
v19 is now at Preview 4, label should be updated -- link does not need to change

### ISSUE THREAD

**Issue by MikeFarrington** [MicrosoftDocs/sql-docs#8404] opened 2022-12-20 20:39 UTC
[Enter feedback here]
v19 is now at Preview 4, not Preview 3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by WilliamAntonRohm** [comment] 2022-12-20 20:56
@MikeFarrington -- Mike, thank you for catching this.  I am updating the article.

**Comment by rwestMSFT** [comment] 2022-12-22 18:30
#please-close

I believe this is a duplicate of a previous PR.

**Closed by rwestMSFT** 2022-12-22 18:30 UTC
Labels: doc-bug, Pri1, sql/svc, ssms/subsvc
