### ISSUE TITLE
Server object browsing dies on periods

### ISSUE THREAD

**Issue by razgrim** [MicrosoftDocs/sql-docs#2537] opened 2019-07-16 20:51 UTC
If the path has a period in it, this CMDLET dies. 
"dir SQLSERVER:\SQL\$servername\DEFAULT\Databases\testDB" will work great.
"dir SQLSERVER:\SQL\$servername\DEFAULT\Databases\test.DB" errors out wildly:
"Cannot retrieve the dynamic parameters for the cmdlet. SQL Server PowerShell provider error: The number of keys specified does not match the number of keys required to 
address this object. The number of keys required are: Name."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a81f1f-28a2-f627-d009-040452d50de2
* Version Independent ID: 15979469-7b3b-a154-3180-06ff33436954
* Content: [Navigate SQL Server PowerShell Paths - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/navigate-sql-server-powershell-paths?view=sql-server-2017#feedback)
* Content Source: [docs/powershell/navigate-sql-server-powershell-paths.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/navigate-sql-server-powershell-paths.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by razgrim** [comment] 2019-07-16 20:56
The following script demonstrates the issue well:

$servername="dev-sql01"
$databases=Get-ChildItem -Path "SQLSERVER:\SQL\$servername\DEFAULT\Databases"


foreach ($db in $databases){
    echo "-----$db-----"
    Get-ChildItem $db
}

![image](https://user-images.githubusercontent.com/43814950/61329131-9bd31a80-a7ea-11e9-9384-d6a8057e9328.png)

**Comment by msebolt** [comment] 2019-07-17 20:37
@razgrim Thank you for the feedback.

This definitely constitutes a product bug.

@markingmyname Do you have a reference for SQL Server Powershell issues?

**Comment by markingmyname** [comment] 2019-08-01 16:46
Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

In the meantime, can you please visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to submit your issue?

**Comment by markingmyname** [comment] 2019-08-01 18:57
Thanks for your comment, @[github person who posted]. This looks like a support request rather than documentation feedback.

Please visit one of the following pages depending on your product or service.

[On Prem users](https://support.microsoft.com/en-us/supportforbusiness/productselection)
[SQL on Azure](https://ms.portal.azure.com/#home)
[Services Hub (Unified/premier customers)](https://serviceshub.microsoft.com/support/create/097a91e3-084a-46a8-b385-d5b07ffedcfe)

**Comment by markingmyname** [comment] 2019-08-06 19:36
@razgrim 

The behavior is by design, at least in the current design (. needs to be escaped because it is a special char).

**Comment by markingmyname** [comment] 2019-08-06 19:37
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Closed by markingmyname** 2019-08-06 19:37 UTC
Labels: Pri2, product-feedback, scripting/tech, sql/prod

**Comment by mkarpuk** [comment] 2021-04-15 11:38
Could you provide some clue on how '.' should be escaped? The only information I found was https://docs.microsoft.com/en-us/sql/powershell/escape-sql-server-identifiers?view=sql-server-ver15, but using '`' didn't help me to deal with dots unfortunately.

Thank you
