### ISSUE TITLE
FK Not Backwards

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#3066] opened 2019-09-27 16:25 UTC
SQL Server has a requirement for creating foreign key constraints that is not documented in this topic.
For a mulitple column foreign key, the "( ref_column [ ,...n ] )" reference column specification must list the columns in the order they were listed to create the referenced primary key on the primary key table.

The script below gets an error in the "backwards key" batch. However, the sp_help output shows that the foreign key from the "forwards key" batch gets added (SQL 2017 CU13).

--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--

use tempdb
;
GO
create table dbo.tPrimary (
  aaa int, bbb int, ccc int
, primary key clustered (aaa, bbb)
);
create table dbo.tForeign (
  bbb int, aaa int, ddd int, eee int
, primary key clustered (aaa, bbb, ddd)
);
GO
raiserror(N'Before backwards key', 10 , 1) with nowait
;
alter table dbo.tForeign add
  foreign key (bbb, aaa) references dbo.tPrimary (bbb, aaa)
;
raiserror(N'After backwards key', 10 , 1) with nowait
;
GO
raiserror(N'Before forwards key', 10 , 1) with nowait
;
alter table dbo.tForeign add
  foreign key (aaa, bbb) references dbo.tPrimary (aaa, bbb)
;
raiserror(N'After forwards key', 10 , 1) with nowait
;
GO
exec sp_help N'dbo.tForeign'
;
GO
drop table dbo.tForeign
;
drop table dbo.tPrimary
;
GO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be5dfc7-5496-f8ec-072f-81132fe92054
* Version Independent ID: 634e3c60-d717-92ba-dd93-e3773edf2816
* Content: [CREATE TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment] 2019-09-27 23:30
@JediSQL -- Dan, thank you for your feedback.

@CarlRabeler -- Carl, please look into updating the documentation.

Related issue https://github.com/MicrosoftDocs/sql-docs/issues/3065

**Comment by rothja** [comment] 2019-10-10 14:11
@JediSQL Thank you for this feedback and for the test code. @CarlRabeler is out of the office for the next few weeks. @VanMSFT can you please take a look at this feedback and see if we need to clarify the article? Thank you! #reassign:@vanmsft

**Comment by rothja** [comment] 2019-10-10 14:12
#reassign:vanmsft

**Comment by VanMSFT** [comment] 2019-10-10 14:31
Following up with engineering.

**Comment by jgmreyes** [comment] 2019-11-10 16:41
Hi there, I am using SQL Dev Edition 140, according to a note section:

"When you partition a non-unique, clustered index, the Database Engine by default adds the partitioning column to the list of clustered index keys, if it is not already specified. When partitioning a non-unique, nonclustered index, the Database Engine adds the partitioning column as a non-key (included) column of the index, if it is not already specified."

So I tried to prove both parts and it is not working, it is not getting into the clustered index keys or as an included column in the non clustered indexes.

Sample create table statement that I used is this:
USE [WideWorldImportersDWMine]
GO

/****** Object:  PartitionFunction [QuadrillionLeft_PF]    Script Date: 11/11/2019 12:39:50 am ******/
CREATE PARTITION FUNCTION [QuadrillionLeft_PF](bigint) AS RANGE LEFT FOR VALUES (99999999999999, 199999999999999)
GO
/****** Object:  PartitionScheme [SingleFilegroupBigInt_PS]    Script Date: 11/11/2019 12:40:16 am ******/
CREATE PARTITION SCHEME [SingleFilegroupBigInt_PS] AS PARTITION [QuadrillionLeft_PF] TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])
GO

CREATE TABLE [dbo].[SampleTable](
	[TheDate] [date] NOT NULL,
	[AnotherDate] [date] NOT NULL,
	[ABigInt] [bigint] NOT NULL,
  INDEX IDX_SampleTable_TheDate CLUSTERED (TheDate) ON SingleFilegroupBigInt_PS(ABigInt)
);

Can you please verify, maybe I needed a 2019 engine instead of 2017?

**Comment by VanMSFT** [comment] 2020-03-16 23:11
This is a duplicate of https://github.com/MicrosoftDocs/sql-docs/issues/3065. Closing

**Closed by VanMSFT** 2020-03-16 23:11 UTC
Labels: Pri1, assigned-to-author, doc-bug, sql/prod, t-sql/tech
