### ISSUE TITLE
ODBC Error Number:42000 [You can only perform a full backup of the master database]

### ISSUE THREAD

**Issue by MuthuramanD** [MicrosoftDocs/sql-docs#5207] opened 2020-07-20 04:40 UTC
[The master database records all the system-level information for a SQL Server system. This includes instance-wide metadata such as logon accounts, endpoints, linked servers, and system configuration settings

It is by design that SQL Server is designed to allow only FULL backup of the master database, But why? The reason is that to apply partial, or differential backups to a database, the database has to be in No recovery (Recovering) state. However, SQL Server does not allow the master database to be restored without recovery. For this reason, the master database has to be in Recovered state always

Hence it is best to add a caption stating that Under " Master DB can only be backed up as FULL Backup

A place to add this information

https://docs.microsoft.com/en-in/sql/relational-databases/databases/master-database?view=sql-server-ver15

Under Restriction -> the above verbatim can be added.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ba00-bb98-1076-118f-9133acc496c6
* Version Independent ID: 6ea8ec5a-7f33-45b5-68fa-ccc18dcc4d81
* Content: [master Database - SQL Server](https://docs.microsoft.com/en-in/sql/relational-databases/databases/master-database?view=sql-server-ver15)
* Content Source: [docs/relational-databases/databases/master-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/master-database.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment] 2020-07-20 22:34
Duplicate of #5171

**Closed by WilliamAntonRohm** 2020-07-20 22:34 UTC
Labels: /tech, Pri2, assigned-to-author, doc-bug, duplicate, sql/prod
