### ISSUE TITLE
syntax - repo a mistake

### ISSUE THREAD

**Issue by peoplefive** [MicrosoftDocs/sql-docs#7903] opened 2022-08-07 03:19 UTC
Syntax
line4:
 table_or_view_name [ FOR SYSTEM_TIME <system_time> ] [ AS ] table_alias ]   
lack a [ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3553153e-f6bf-2bc7-288c-ee03a3ba0781
* Version Independent ID: b4e3cfdf-aad7-e8a6-ffd7-acba7571de5c
* Content: [FROM clause plus JOIN, APPLY, PIVOT (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16)
* Content Source: [docs/t-sql/queries/from-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/from-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment] 2022-08-08 23:36
@peoplefive -- thank you for catching this.  I updated this article the day before you raised this issue; please check again today.

Duplicate of #7897 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Closed by WilliamAntonRohm** 2022-08-08 23:36 UTC
Labels: duplicate, sql/prod, t-sql/tech, doc-bug, cba, Pri1
