### ISSUE TITLE
"Best practice recommendations" part has been repeated twice in the page

### ISSUE THREAD

**Issue by hyamchi** [MicrosoftDocs/sql-docs#9385] opened 2023-10-04 23:36 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b98be9d-e69f-7a59-a927-8b97126bc92e
* Version Independent ID: d9b888ee-f2cb-953f-2594-eb3c1c91b16c
* Content: [Back Up and Restore of SQL Server Databases - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/back-up-and-restore-of-sql-server-databases?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/back-up-and-restore-of-sql-server-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/back-up-and-restore-of-sql-server-databases.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by rwestMSFT** [comment] 2023-10-05 00:28
This has already been resolved and will be visible in a future update.

Duplicate of https://github.com/MicrosoftDocs/sql-docs/pull/9380.

**Closed by rwestMSFT** 2023-10-05 00:28 UTC
Labels: Pri1, sql/svc, backup-restore/subsvc
