### ISSUE TITLE
mi.<managed_instance> should be <managed_instance>.<DNS zone> in the sample.

### ISSUE THREAD

**Issue by masank** [MicrosoftDocs/sql-docs#9391] opened 2023-10-06 09:22 UTC
Regarding the sample below in the section [I. Create SQL Managed Instance linked server with pass-through Azure AD authentication]

EXEC master.dbo.sp_addlinkedserver
    @server = N'MyLinkedServer',
    @srvproduct = N'',
    @provider = N'MSOLEDBSQL',
    @datasrc = N'mi.<managed_instance>.database.windows.net,1433';

@datasrc = N'mi.<managed_instance>.database.windows.net,1433
should be
@datasrc = N'<managed_instance>.<DNS zone>.database.windows.net,1433

**Comment by masank** [comment] 2023-10-06 09:23
correction: managed_instance.dns_zone.database.windows.net

**Comment by rwestMSFT** [comment] 2023-10-06 17:51
Duplicate of https://github.com/MicrosoftDocs/sql-docs/pull/9390.

**Closed by rwestMSFT** 2023-10-06 17:51 UTC
Labels: Pri3

**Comment by rwestMSFT** [comment] 2023-11-15 21:32
We will have an updated article published in the next day or so, with the correction. Thank you for your contribution.
