### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by Dmitry-Eremeev** [MicrosoftDocs/sql-docs#5248] opened 2020-07-27 10:20 UTC
Hi,

documentation does not mention ubuntu 20.04

By searching  I found directory for ubuntu 20.04
https://packages.microsoft.com/config/ubuntu/20.04/

Did some steps:
- curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
-  sudo apt update
- sudo apt search msodbcsql17
Sorting... Done
Full Text Search... Done
msodbcsql17/now 17.5.2.1-1 amd64 [residual-config]
  (none)

- sudo apt install msodbcsql17
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package msodbcsql17 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'msodbcsql17' has no installation candidate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by RGoodmanAxioma** [comment] 2020-07-27 12:15
Did the exact same steps today. When will the msodbcsql software be available for Ubuntu Focal?

**Comment by David-Engel** [comment] 2020-07-27 16:45
Duplicate of #4678 

The next release is targeting Friday.

#please-close

**Closed by David-Engel** 2020-07-27 16:45 UTC
Labels: Pri2, connectivity/tech, sql/prod
