### ISSUE TITLE
I still have an issue with converting python float to decimals. I have this error message: 

### ISSUE THREAD

**Issue by mouradbka** [MicrosoftDocs/sql-docs#6124] opened 2021-02-25 10:16 UTC
[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 6ea22367-9924-edb3-c65a-66a1cb4181fa
* Version Independent ID: cef2a17a-d363-3042-e585-4c9184637eb4
* Content: [Convert Python and SQL data types - SQL Server Machine Learning Services](https://docs.microsoft.com/da-dk/sql/machine-learning/python/python-libraries-and-data-types?view=sql-server-2017)
* Content Source: [docs/machine-learning/python/python-libraries-and-data-types.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/python/python-libraries-and-data-types.md)
* Product: **sql**
* Technology: **machine-learning-services**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by WilliamAntonRohm** [comment] 2021-02-25 18:12
Duplicate of #6125

**Closed by WilliamAntonRohm** 2021-02-25 18:12 UTC
Labels: cba, duplicate, machine-learning-services/tech, sql/prod
