### ISSUE TITLE
Example with OPENJSON seems to not work, requires AdventureWorks db?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#2669] opened 2019-08-06 14:53 UTC
@OneLonelly commented on [Mon Aug 05 2019](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/54)

Hi!
The example doesn't work.
-- Example begin: 
DECLARE @jsonVariable NVARCHAR(MAX)

SET @jsonVariable = N'[  
        {  
          "Order": {  
            "Number":"SO43659",  
            "Date":"2011-05-31T00:00:00"  
          },  
          "AccountNumber":"AW29825",  
          "Item": {  
            "Price":2024.9940,  
            "Quantity":1  
          }  
        },  
        {  
          "Order": {  
            "Number":"SO43661",  
            "Date":"2011-06-01T00:00:00"  
          },  
          "AccountNumber":"AW73565",  
          "Item": {  
            "Price":2024.9940,  
            "Quantity":3  
          }  
       }  
  ]'
  
INSERT INTO SalesReport  
SELECT SalesOrderJsonData.*  
FROM OPENJSON (@jsonVariable, N'$.Orders.OrdersArray')  
           WITH (  
              Number   varchar(200) N'$.Order.Number',   
              Date     datetime     N'$.Order.Date',  
              Customer varchar(200) N'$.AccountNumber',   
              Quantity int          N'$.Item.Quantity'  
           )  
  AS SalesOrderJsonData;  
-- Example is finish.
If you comment " INSERT INTO SalesReport " , your example return empty table.  

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Работа с данными JSON в SQL Server - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/json/json-data-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

---

@srvbpigh commented on [Mon Aug 05 2019](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/54#issuecomment-518444456)

Hello, @OneLonelly
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-08-06 14:54
Hi team, 
I'm moving this here because the user reports the example doesn't work
best

**Comment by MightyPen** [comment] 2019-08-07 06:19
@msebolt Hi Matthew, can you please test this code example (from the article) in the context of `USE AdventureWorks;`.

Also, please assess whether AdventureWorks is a _prerequisite_ for some or all of the code examples in this article. If it is a prereq, can you please edit the article to create a `## Prerequisites` section explaining the prereqs.
(I think the very idea of requiring customers to pre-install AdventureWorks just makes these code example unnecessarily harder to run. If you examine A.W. db, I wonder whether a couple of short simple CREATE TABLE statements could be added to `## Prerequisites` to eliminate the need for A.W.?)

I conclude that the customer, @OneLonelly , must have run `USE AdventureWorks;` because he did Not mention a gross error like Table-Not-Found etc.

At some point you will decide whether you can deflect this Issue #2669 .  If you ultimately decide you cannot deflect, you would then need to assign this to Jovan P.
Thanks a lot.  (GeneMi)

@jovanpop-msft

**Comment by msebolt** [comment] 2019-08-21 18:19
@MightyPen  `AdventureWorks` is not a prerequisite for the page samples, although the example referenced above had separate issues.

The documentation has been updated.

**Comment by msebolt** [comment] 2019-08-21 18:21
@MightyPen  Please see validation issue, https://github.com/MicrosoftDocs/sql-docs-pr.ru-ru/pull/9.  

The `sql-analysis-services-2016` moniker is not present in the main repo and is now causing issues.

Is it safe to remove this moniker?

**Comment by MightyPen** [comment] 2019-08-21 18:31
@msebolt Matthew, I need more specificity of what is being asked.  For instance, where is the moniker 'sql-analysis-services-2016' mentioned or used presently?

**Comment by msebolt** [comment] 2019-08-21 18:39
@MightyPen  Sure, the issue occurs in PR https://github.com/MicrosoftDocs/sql-docs-pr.ru-ru/pull/9 specifically in file [.openpublishing.publish.config.json](https://github.com/msebolt/sql-docs-pr.ru-ru/blob/patch-1/.openpublishing.publish.config.json).

The repo admin has already responded that the issue is being assessed.

**Comment by msebolt** [comment] 2019-08-30 17:26
The issues have been resolved, changes merged.

**Closed by msebolt** 2019-08-30 17:26 UTC
Labels: /tech, Pri1, doc-bug, sql/prod
