### ISSUE TITLE
Parameter Sensitive Plan optimization title

### ISSUE THREAD

**Issue by rgward** [MicrosoftDocs/sql-docs#7863] opened 2022-07-27 02:36 UTC
The title of this is Parameter Sensitivity Plan optimization. I recommend we use the term Parameter Sensitive Plan optimization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d912455d-8d09-0b74-0f8e-9de4d8777b26
* Version Independent ID: d912455d-8d09-0b74-0f8e-9de4d8777b26
* Content: [Parameter Sensitivity Plan optimization - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/parameter-sensitivity-plan-optimization?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance/parameter-sensitivity-plan-optimization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/parameter-sensitivity-plan-optimization.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @thesqlsith
* Microsoft Alias: **derekw**

**Comment by thesqlsith** [comment] 2022-07-27 02:49
Thanks Bob, the title has been fixed in the CTP 2.1 documentation.  Part of the problem is that when the original markdown was published, the "sensitivity" name was part of the file so this has to be corrected as well to fully mitigate the problem.  I can do a quick edit for now but it may cause a merge conflict with Mike's changes later on tomorrow.

**Comment by thesqlsith** [comment] 2022-07-28 00:03
#please-close

**Closed by thesqlsith** 2022-07-28 00:03 UTC
Labels: sql/prod, performance/tech, doc-bug, assigned-to-author, Pri2
