### ISSUE TITLE
Docker demo's iframe page is missing

### ISSUE THREAD

**Issue by doggy8088** [MicrosoftDocs/sql-docs#7472] opened 2022-04-11 13:51 UTC
The Docker demo's iframe page is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash&WT.mc_id=DT-MVP-4015686)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment] 2022-04-11 20:41
@doggy8088 -- Will, thank you for your feedback.  

@amvin87 -- please look into this potential documentation issue.

**Comment by amvin87** [comment] 2022-04-12 12:57
Can you please give more details what iframe page are we talking about?

**Comment by rwestMSFT** [comment] 2022-04-12 20:11
I cannot reproduce this issue. The video is playing correctly for me.

#please-close

**Comment by doggy8088** [comment] 2022-04-13 06:29
@rwestMSFT Please check this way:

1. Open https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

2. Scroll down to the bottom.

    ![image](https://user-images.githubusercontent.com/88981/163113900-b12d39db-7120-4983-9f3d-62d67f3ed752.png)

3. Scroll the iframe page down a bit. You can see 404 Not Found message.

    ![image](https://user-images.githubusercontent.com/88981/163113995-7f20d9db-9377-4a19-ba11-d23a892f5ae2.png)

**Comment by doggy8088** [comment] 2022-04-13 06:36
I also checked the HTML source.

![image](https://user-images.githubusercontent.com/88981/163114298-59cdb4b7-5bfe-4d72-8303-2bfa69f49bb6.png)

The iframe link: [https://channel9.msdn.com/Events/Connect/2017/T152/player?nocookie=true](view-source:https://channel9.msdn.com/Events/Connect/2017/T152/player?nocookie=true). If I open this link, it works, but it seems do too much redirection.

![image](https://user-images.githubusercontent.com/88981/163114852-40938312-7433-41af-8972-4a2d42730e8e.png)

I think it's a localization issue. Please don't close it. It only happen in `non-English` locale.

**Comment by doggy8088** [comment] 2022-04-13 06:43
@WilliamAntonRohm @rwestMSFT

I also tested with Microsoft Edge. See this:

![image](https://user-images.githubusercontent.com/88981/163115952-3ec8f25a-98b6-4e9e-8220-80f49764789e.png)

**Comment by rwestMSFT** [comment] 2022-04-13 07:35
@doggy8088 Unfortunately this is not the correct forum to report your issue, and while I understand you may not be happy with this response, there is nothing I can do. Please direct your bug report to Microsoft Support.

I am once again closing this issue.

#please-close

**Closed by rwestMSFT** 2022-04-13 07:36 UTC
Labels: sql/prod, linux/tech, doc-bug, assigned-to-author, Pri2

**Comment by supersonictw** [comment] 2022-04-13 12:31
When the cookie `MarketplaceSelectedLocale` is unset, or set it as `zh-tw` / `zh-hk`, the issue will be reproduced.

**Comment by rwestMSFT** [comment] 2022-04-13 17:31
I have reported this internally, but I can make no promises that it will be addressed. All I can suggest for now is clearing your browser cookies for `docs.microsoft.com` and replacing the region code in the URL with `en-us`.

**Comment by supersonictw** [comment] 2022-04-13 17:42
I think that the cookie `MarketplaceSelectedLocale` seems having no default value, and `zh-tw`, `zh-hk` are not included in the value validator.
It's better to set the fallback one to resolve the problem.
Anyway, thanks you very much. :smile:
