### ISSUE TITLE
Ubuntu - unable to locate package

### ISSUE THREAD

**Issue by BrianKrohn** [MicrosoftDocs/sql-docs#2358] opened 2019-06-21 17:42 UTC
The apt-get install step for Ubuntu returns "Unable to locate package mssql-server-polybase".

---
(ERROR: **abiolao96** is his correct GitHub name!  GeneMi)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0547d262-0e0b-1c3c-66de-b45458fd40b3
* Version Independent ID: b0f7235c-9439-7be5-eb18-f343861a0159
* Content: [Install PolyBase on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-linux-setup?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-linux-setup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-linux-setup.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @aboke
* Microsoft Alias: **aboke**

**Comment by MightyPen** [comment] 2019-06-21 21:35
@abiolao96 Abiola, This Issue 2358 might indicate a bug of omission in the cited "PolyBase on Linux" article. Perhaps a Prerequisite should be added (just my guess)?

Can you please process this Issue 2358, and enter an informative Comment into the Issue.
After we have a good reply to the customer, we can then Close this issue as addressed.
SQL Linux Writer Jason Roth can assist you if you ask him.

CC: @rothja

**Comment by BrianKrohn** [comment] 2019-06-24 12:12
If it helps, I followed the instructions in the link below to add the Linux software repo for Microsoft products after PolyBase failed to install the first time.  Adding the repo did not resolve the issue.
https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software

**Comment by rothja** [comment] 2019-06-28 16:49
@BrianKrohn Sorry for the delayed response! I'm going to try this out and let you know if I can reproduce. BTW, are you installing SQL Server 2019 preview on your machine? I'm not sure this will work to add the package to SQL Server 2017 at this time. I'll investigate that part too. Thanks for your patience.

**Comment by rothja** [comment] 2019-07-22 16:50
@BrianKrohn I tested this, and it works with the SQL Server 2019 preview installation. So I think the problem is that the article does not mention this 2019 requirement. I will fix the article and then this git issue will automatically close. I am very sorry for the confusion! Thanks!

**Closed** 2019-08-08 13:55 UTC
Labels: Pri2, assigned-to-author, doc-bug, linux/tech, sql/prod
