### ISSUE TITLE
Adding keys via apt-key deprecated in Debian 11

### ISSUE THREAD

**Issue by lgonzalezsa** [MicrosoftDocs/sql-docs#7695] opened 2022-06-17 02:05 UTC
For Debian installation, in particular for Debian 11, the way the keys are added generates a warning:
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment] 2022-06-17 21:12
@lgonzalezsa -- Luis, thank you for your feedback.

@David-Engel -- David, please look into this issue.

**Comment by GunArm** [comment] 2022-07-12 16:42
This is what I did:
```
sudo su
key=/usr/share/keyrings/microsoft.gpg
debianVer=$(sed -r 's|^Debian GNU/Linux ([[:digit:]]+) .*|\1|' /etc/issue | head -n1)
echo "Debian verison = '$debianVer'"
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o "$key"
curl -fsSL https://packages.microsoft.com/config/debian/${debianVer}/prod.list | sed 's|]| signed-by='"$key"']|' > /etc/apt/sources.list.d/mssql-release.list
apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18
```

**Comment by David-Engel** [comment] 2022-07-26 22:52
Closing as duplicate of #6706 

#please-close

**Closed by David-Engel** 2022-07-26 22:52 UTC
Labels: sql/prod, connectivity/tech, doc-bug, assigned-to-author, Pri1
