### ISSUE TITLE
Public key issue when installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by chris43123** [MicrosoftDocs/sql-docs#9546] opened 2023-12-11 20:10 UTC
[Enter feedback here]

Was trying to install using the 22.04 tab of the tutorial and had an issue about public keys when tryin to install the package, solved it by using the 20.04 method of installing the public keys

`curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2204)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2023-12-11 20:59
Hi @chris43123, can you be more specific about the error message you received?

**Comment by chris43123** [comment] 2023-12-11 21:24
Hi @rwestMSFT !
I was following the instructions for installing MSSQL on Ubuntu 22.04 as it is the version I'm using, the issue came when i ran the commands
```
sudo apt-get update
sudo apt-get install -y mssql-server
```
It displayed this error: 
```
Error https://packages.microsoft.com/ubuntu/22.04/mssql-server-2022 jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
```
I suposse was wrong when trying to add the GPG Keys with the the command
```
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
```
Ran it several times to make sure it wasn't my mistake but it made no changes
Eventually solved it by importing the public repository GPG keys using the Ubuntu 20.04 method instead
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
```

**Comment by rwestMSFT** [comment] 2023-12-13 17:26
@chris43123 We've done some more digging, and you did nothing wrong. We're escalating internally to our partners at Canonical. In the meantime, using the 20.04 method was fine as you discovered.

**Comment by rwestMSFT** [comment] 2023-12-21 00:25
Duplicate of #9504.

**Closed by rwestMSFT** 2023-12-21 00:25 UTC
Labels: doc-bug, assigned-to-author, Pri2, sql/svc, linux/subsvc

**Comment by rwestMSFT** [comment] 2023-12-21 01:11
We have created a workaround in the article, which will be published in the next day or so, that should resolve the issue. Please let us know if it doesn't work.

**Comment by warrenb-onware** [comment] 2024-02-14 17:54
I don't see the workaround mentioned - I'm assuming it would follow the `sudo apt-get update` instruction as that's where the error occurs.

However, I was able to apply the workaround described above.
