### ISSUE TITLE
Does specifying the field terminator need quoting ? 

### ISSUE THREAD

**Issue by steveculshaw** [MicrosoftDocs/sql-docs#2258] opened 2019-06-05 09:24 UTC
In the section https://docs.microsoft.com/en-us/sql/relational-databases/import-export/create-a-format-file-sql-server?view=sql-server-2017#a-creating-an-xml-format-file-for-character-data where the field terminator is specified with the -t option, I can only get it to work if I quote the comma, i.e. -t"," or -t','

Yet when importing or exporting it's fine to use it "raw", i.e. -t,

So what am I doing wrong  :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb964ca8-e683-9fab-1933-a12ec6e50a05
* Version Independent ID: 8d024f19-8ce5-5bc4-d45a-5bf39e17a6d7
* Content: [Create a Format File (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/create-a-format-file-sql-server?view=sql-server-2017#a-creating-an-xml-format-file-for-character-data)
* Content Source: [docs/relational-databases/import-export/create-a-format-file-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/create-a-format-file-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment] 2019-06-05 09:41
@steveculshaw Hi Steve, When you wrote - "I can only get it to work if I quote the comma" - what did you mean by "it"?  (Can you please add a new Comment here to clarify?)
I gather that "it" does Not mean either importing or exporting, based on your subsequent sentence.

We would like to fix the documentation item that you have noticed, but we need to be sure we understand first.
Thank you.

**Comment by MightyPen** [comment] 2019-06-05 09:42
@MashaMSFT Hi Masha, I have assigned this Issue 2258 to you.

**Comment by steveculshaw** [comment] 2019-06-06 08:37
Sorry, not clear in my original post.

I can use the `-t,` option when I import or export, e.g. `bcp myDb.dbo.mytable IN C:\Repos\Spike-bcp\Spike-bcp\myTable.bcp -c -t, -T`

But I have to wrap the comma in single or double quotes to get it to work when I attempt to create a format file, e.g. `bcp myDb.dbo.myTable format nul -c -f C:\Repos\Spike-bcp\Spike-bcp\myTable.fmt -t"," -T`

**Comment by MashaMSFT** [comment] 2019-06-13 16:17
Hi @steveculshaw , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment] 2019-06-24 17:59
Hi @steveculshaw , 
Unfortunately, we were  unable to reproduce the issue :( At this point, we would recommend either opening a case up with support, or submitting a [bug](https://aka.ms/sqlfeedback) with repro instructions and environment details (like OS, SQL, version of BCP etc).

My apologies that the SQL Docs team was unable to assist you further with your issue, but please let us know if there is anything more we can do for you from the documentation standpoint? If not, we will proceed with closing out this Git Issue in a few business days.

Thanks!

**Closed** 2019-06-27 20:00 UTC
Labels: assigned-to-author, data-movement/tech, sql/prod
