### ISSUE TITLE
Concurrency control in SQL Server -  snapshot isolation

### ISSUE THREAD

**Issue by Ellisseee** [MicrosoftDocs/sql-docs#7929] opened 2022-08-11 08:09 UTC
Hi All,
For an environment which service concurrent requests involving a mix of reads and writes, we have implemented snapshot isolation - Read Committed, but still encountering DB tables are getting in exclusive locks. SQL server uses shared read locks to avoid dirty reads and will hold new reads until a writer completes, can I check if this is the product design of SQL server?
Thanks.

**Comment by WilliamAntonRohm** [comment] 2022-08-11 19:27
@Ellisseee -- please see my answer in #7921.

Duplicate of #7921

**Closed by WilliamAntonRohm** 2022-08-11 19:27 UTC
Labels: duplicate, cba, Pri3
