### ISSUE TITLE
Bulk Insert Azure SQL from Storage Account - Only working if the Storage Account firewall setting is "All Networks"

### ISSUE THREAD

**Issue by me2unni** [MicrosoftDocs/sql-docs#4800] opened 2020-05-17 10:37 UTC
Trying to do Bulk upload from Storage Account Excel to Azure SQL Database:

[https://docs.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?view=sql-server-ver15](url)

The code is working when firewall setting for Storage Account is "All Networks".

But if we specify IPs in the firewall including the local IP of the machine (SSMS is accessed) and the Region IPs of the SQL Server, the code is failing with "Access Denied".

Please confirm, whether this is a limitation for Azure SQL Bulk load from Storage Account?

Or any tips for handling this?

**Comment by WilliamAntonRohm** [comment] 2020-05-18 21:38
@me2unni -- thank you for your feedback.  I am closing this issue as a duplicate of #4801, which will be addressed shortly.

**Closed by WilliamAntonRohm** 2020-05-18 21:38 UTC
Labels: Pri3
