### ISSUE TITLE
SQL Server - remote query timeout default value

### ISSUE THREAD

**Issue by AkshaySanadhya** [MicrosoftDocs/sql-docs#6524] opened 2021-06-21 09:05 UTC
[Enter feedback here]
As per Microsoft documentation the remote query timeout the default time out setting is 600 seconds, but when we install sql server and check the connection and sp_configure, the default value is 0 (no timedout). Which is correct documentation or the sql server setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25fe07f-aad6-ad1d-8645-5a15b55c4a0a
* Version Independent ID: 3cf2c9b2-8a73-cea6-4da2-3677d5076725
* Content: [Configure the remote query timeout Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-remote-query-timeout-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment] 2021-06-21 22:22
@AkshaySanadhya -- the correct value is zero (0).  I am updating this article.

Closing this issue as a near-duplicate of #6523

**Closed by WilliamAntonRohm** 2021-06-21 22:22 UTC
Labels: cba, configuration/tech, duplicate, sql/prod
