### ISSUE TITLE
sys.dm_hadr_database_replica_cluster_states is displayed as sys.availability_databases_cluster

### ISSUE THREAD

**Issue by tcna** [MicrosoftDocs/sql-docs#1834] opened 2019-03-29 14:57 UTC
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions.md

In some language page (Japanese, Chinese, Korea, etc.), sys.dm_hadr_database_replica_cluster_states is displayed as sys.availability_databases_cluster.

**Comment by MightyPen** [comment] 2019-03-29 19:24
DIAGNOSIS:

The following link to the JA-JP edition of our private repo DOES show the correct markdown.
Therefore, it seems that a subsequent Build or Publish phase did not occur or did not succeed.

(Following link does show the correct link and text, in the Japanese source.)

https://raw.githubusercontent.com/MicrosoftDocs/sql-docs-pr.ja-jp/live/docs/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions.md?token=AJNpVoxYwWSVw8dNOzN0vD_uQNNko6BCks5cp6nrwA%3D%3D

---

SCREENSHOTS, showing the difference between English vs Japanese.

![Issue-1834 a Japanese](https://user-images.githubusercontent.com/9660758/55256984-cc7f4c00-521b-11e9-8f4e-a8f5e97f0775.PNG)

![Issue-1834 a English](https://user-images.githubusercontent.com/9660758/55256985-cd17e280-521b-11e9-9bd5-420928ec9bf4.PNG)

---

JA-JP:
https://docs.microsoft.com/ja-jp/sql/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions?view=sqlallproducts-allversions 

EN-US:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions?view=sqlallproducts-allversions 

---

I will inform Nobuko K., and she will have to file a DevOps bug for this Issue 1834.

@nokura Hi Nobuko, I think you will want to file a DevOps bug to fix this Issue 1834.  Then, can you please put the DevOps item number into a new Comment here in Issue 1834.

Thanks.  GeneMi.   2019/03/29

**Comment by nokura** [comment] 2019-04-05 23:08
Hello @tcna 
Thank you for your feedback. We will publish the fixed topics next week. I appreciate your time and effort to improve our localized document.
Kind regards,
Microsoft DOCS International Team

**Comment by nokura** [comment] 2019-04-05 23:09
Internal ticket: 80006

**Comment by MightyPen** [comment] 2019-04-06 18:46
@tcna 
The fix for this Issue 1834 is only days away.  I will let internal ticket 80006 handle the final fix from here.
I am now Closing this Issue 1834 as Fixed.
Thank you for reporting this localization flaw to us.

**Closed by MightyPen** 2019-04-06 18:46 UTC
Labels: Issue-Outcome-42-Fixed

**Comment by nokura** [comment] 2019-04-12 01:31
Hello @tcna
Just to follow up on this thread. The issue is solved in Asian languages /ja-jp/, /ko-kr/, /zh-cn/, and /zh-tw/.
https://docs.microsoft.com/ja-jp/sql/relational-databases/system-dynamic-management-views/always-on-availability-groups-dynamic-management-views-functions?view=sql-server-2017

Thank you again for your feedback.
FYI @MightyPen
Kind regards,
Microsoft DOCS International Team
