### ISSUE TITLE
Availability group dashboard stuck on healty state

### ISSUE THREAD

**Issue by baleng** [MicrosoftDocs/sql-docs#2775] opened 2019-08-21 10:53 UTC
hello, i set up an AG with 2 replica and a configuration only instance (ubuntu 16.4, .mssql 2017)  i understand that this is an external managed cluster, but i expect the dashboard to work: now my 3 servers are switched off, and the ag state is healty, the synch state synchronized,  there is only a message in the title bar "an error occurred on the always on dashboard"  (failed to connect to server) , why this state is not reflected to the replica synch status / health? anfter some minutes ssms crashed (Application: Ssms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76df1cf-a234-3768-3c94-b7270d249829
* Version Independent ID: 1235d9a1-8c44-2a11-a213-a1ced144616a
* Content: [Configure SQL Server Always On Availability Group for high availability on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-configure-ha?view=sql-server-2017#add-a-database-to-the-availability-group)
* Content Source: [docs/linux/sql-server-linux-availability-group-configure-ha.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-configure-ha.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment] 2019-08-21 15:22
@baleng  Thank you for the question.

A similar issue was [posted on the StackOverflow](https://dba.stackexchange.com/questions/234876/an-error-occurred-on-the-always-on-dashboard). 

Please try [upgrading your SSMS client](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017) to see if the issue is resolved.

**Comment by baleng** [comment] 2019-08-21 15:38
@mseblot thank you for your input.
i have ssms 17.7 and my issue is bit different, my dashboard opens perfectly all is green but it seems to be a jpg image frozen on a "all ok" state after the servers are switched off. 
by the way i'll try with the latest ssms version 18.2 and keep you posted.
thank you

**Comment by msebolt** [comment] 2019-08-21 15:56
@baleng  Sounds good, no problem.

If this is a new issue, we should move this to the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server).

**Comment by baleng** [comment] 2019-08-22 09:44
Hi @msebolt  , i installed ssms 18.2 , i have the same behaviour.
i have 3 replica (one two and three) , one is primary, two secondary , three configuration only.
if i make three unavailable (witness node), the dashboard reflects the critical situation.

if i make two unavailable the dashboard works as expected

if a make one (primary) unavailable the dashboard says
![image](https://user-images.githubusercontent.com/41946901/63502242-6dbdb600-c4cd-11e9-85e0-3bfb8d59e339.png)
i would expect the green round on the left of one to be red and not synchonizing, and the availability group state to be NOT healty (with the red button)

and two times ssms crashed due unhandled exception
Application: Ssms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Drawing.Region.GetHrgn(System.Drawing.Graphics)
   at System.Windows.Forms.Control.GetHRgn(System.Drawing.Region)
   at System.Windows.Forms.Control.Invalidate(System.Drawing.Region, Boolean)
   at System.Windows.Forms.LinkLabel.InvalidateLink(Link)
   at System.Windows.Forms.LinkLabel.OnGotFocus(System.EventArgs)
   at System.Windows.Forms.Control.WmSetFocus(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Label.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.LinkLabel.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

thanks

**Comment by msebolt** [comment] 2019-08-22 16:33
@baleng  Thank you for the details.  I've submitted this as a bug at https://feedback.azure.com/forums/908035-sql-server/suggestions/38432464-availability-group-dashboard-stuck-on-healty-state.

Also assigning the author.

**Comment by baleng** [comment] 2019-08-23 14:28
Thank you for your interest 
best regards!

**Comment by rothja** [comment] 2019-09-10 16:15
@baleng At this time, I don't think that there is anything we can do from a documentation standpoint. And it looks like @msebolt added this as a bug/feedback-item. I am going to close the issue at this time. I apologize you ran into this experience, and please let me know if you have any other questions. Thank you!

**Closed by rothja** 2019-09-10 16:15 UTC
Labels: Pri2, linux/tech, sql/prod, support-request
