### ISSUE TITLE
Windows Server 2022 - Supported SQL Server Versions

### ISSUE THREAD

**Issue by micoolpaul** [MicrosoftDocs/sql-docs#6721] opened 2021-08-21 06:19 UTC
Can we please have clarified support for the now GA Windows Server 2022 please?

Thanks,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09beb1a-92a9-4335-511c-395ba64c875b
* Version Independent ID: 8f43fca3-43d7-a2e4-1469-bf17f14d9ac8
* Content: [SQL Server 2019: Hardware & software requirements - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15?view=sql-server-ver15)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by WilliamAntonRohm** [comment] 2021-08-23 19:49
Duplicate of #6722

**Closed by WilliamAntonRohm** 2021-08-23 19:49 UTC
Labels: duplicate, sql/prod, release-landing/tech, cba
