### ISSUE TITLE
Link to User Install wrong

### ISSUE THREAD

**Issue by jimhess** [MicrosoftDocs/sql-docs#4356] opened 2020-03-17 18:24 UTC
The link points to VSCode's user installer.
One might guess this page was copied from that documentation and not tested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment] 2020-03-18 20:36
@jimhess -- thank you for your feedback.

@markingmyname -- please look into this issue #4356.

**Comment by markingmyname** [comment] 2020-03-20 19:42
@jimhess 

I am finding the User Installer to download Azure Data Studio.

Are you not being prompted to download this file - azuredatastudio-windows-user-setup-1.16.0.exe?

**Comment by jimhess** [comment] 2020-03-20 20:21
"Get Azure Data Studio for Windows" section has a link which points to VSCode page "User setup for Windows", which in turn has a link to VSCodes user mode installer, not Azure Data Studio's.

**Comment by markingmyname** [comment] 2020-03-21 03:24
@jimhess 

Thank you for clarifying.

We are looking into this.

Thank you for bringing this to our attention.

**Comment by markingmyname** [comment] 2020-03-23 14:14
@jimhess 

It's by design as it explains why someone would use user setup.

**Comment by markingmyname** [comment] 2020-05-11 19:11
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit Azure Data Studio repo(https://github.com/microsoft/azuredatastudio)

**Closed by markingmyname** 2020-05-11 19:11 UTC
Labels: Pri1, assigned-to-author, azure-data-studio/tech, doc-bug, sql/prod
