### ISSUE TITLE
Debian 12 procedure doesn't work

### ISSUE THREAD

**Issue by Sparviero-Sughero** [MicrosoftDocs/sql-docs#9562] opened 2023-12-20 16:51 UTC
Regarding [Download ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=debian18-install%2Cdebian17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline), apt-get update command return this error

```
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 https://packages.sury.org/php bookworm InRelease
Get:5 https://packages.microsoft.com/debian/12/prod bookworm InRelease [3617 B]
Err:5 https://packages.microsoft.com/debian/12/prod bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/debian/12/prod bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/debian/12/prod bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I've tried 
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF`

but the error is the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc3da20-7ab2-d20f-4d29-4664d3183b57
* Version Independent ID: 986d25d9-5d2e-5154-39ea-3b683faf2264
* Content: [Install the Microsoft ODBC driver for SQL Server (Linux) - ODBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline)
* Content Source: [docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by rwestMSFT** [comment] 2023-12-21 00:24
Duplicate of #9504.

**Closed by rwestMSFT** 2023-12-21 00:24 UTC
Labels: Pri2, sql/svc, connectivity/subsvc

**Comment by rwestMSFT** [comment] 2023-12-21 01:11
We have created a workaround in the article, which will be published in the next day or so, that should resolve the issue. Please let us know if it doesn't work.
