### ISSUE TITLE
"Build Tools for Visual Studio" workloads do not install localdb

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/sql-docs#8122] opened 2022-09-27 16:41 UTC
The documentation states:

> Alternatively, you can install LocalDB through the [Visual Studio Installer](https://visualstudio.microsoft.com/downloads/), as part of the Data Storage and Processing workload, the ASP.NET and web development workload, or as an individual component.

While this works for me for the standard Visual Studio Installer, it does _not_ work when choosing the corresponding workloads on "Build Tools for Visual Studio 2022".  It might be helpful to note this on the documentation.  When installing "Build Tools for Visual Studio" it appears that there are no workloads which will install it, so for build servers, you currently have to install localdb separately if it is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea66ca27-e0b1-cd1e-a8ef-55911169c71a
* Version Independent ID: f2340ce9-9771-851e-60a7-237c6e55f085
* Content: [SQL Server Express LocalDB - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/sql-server-express-localdb.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/sql-server-express-localdb.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2022-09-27 17:40
@davisnw Thank you. We are discussing the LocalDB experience in a separate internal conversation, so this is valuable feedback.

**Comment by Matteo-T** [comment] 2022-09-30 06:25
@rwestMSFT - this looks like a bug in the SSDT/VS installer for that SKU, rather than a documentation issue. A VSFeedback ticket would be more appropriate, I think, so the SSDT Team can look into it and see what can be done about it. There might be a slim chance that this is "by design", in which case it would make sense to update the documentation.

**Comment by rwestMSFT** [comment] 2022-09-30 16:08
Thank you @Matteo-T. In that case I will close this issue.

@davisnw: please open a feedback item so the team can investigate further. You can do so from within Visual Studio.

**Comment by rwestMSFT** [comment] 2022-09-30 16:08
#please-close

**Closed by rwestMSFT** 2022-09-30 16:08 UTC
Labels: sql/prod, configuration/tech, doc-bug, assigned-to-author, Pri1
