### ISSUE TITLE
Add Caveats when using FOR JSON

### ISSUE THREAD

**Issue by KSib** [MicrosoftDocs/sql-docs#1501] opened 2019-01-07 15:44 UTC
When using a query with FOR JSON in it, I'd note that if the query is too long when using SSMS then right clicking the results and clicking copy will not copy the whole result set and additionally selecting "Results to File" will add a bunch of CRLF line breaks in the resulting file. Using a C# DataReader doesn't have this problem. I don't know if this is a bug in SSMS or what, but it tripped me up for a while trying to test a query outside of the code first.

SQL Server version 14.0.3048 (Express)
SQL Server Management Studio Version: v17.9.1

**Comment by LarnuUK** [comment] 2019-01-08 16:52
This isn't because of your Maximum Characters Retrieved setting (Tools > Options > Query Results > SQL Server > Results to Grid) is it @KSib ? The Maximim value is 65535 for Non XML data, however it's unlimited. As, I assume, the JSON is treated as a `varchar`, and the White Space would be included as a character, this could likely easily make the JSON appear truncated. The fact that the issue isn't replicated with a `DataReader` strongly implies this is likely the case.

**Comment by MightyPen** [comment] 2019-01-09 01:43
@KSib , @LarnuUK 
This useful information or solution has now been merged into our 'master' branch. By end of day tomorrow, the change will likely be visible on our live website, in the following SQL Server documentation article.
.
https://docs.microsoft.com/sql/t-sql/queries/select-for-clause-transact-sql?view=sql-server-2017#for-xml
.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/8696
( `https://github.com/MicrosoftDocs/sql-docs-pr/pull/8696` )
.
Thank you for bringing this idea to our attention.
With this success, I will now Close this Issue 1501.  However, if further communication on this is needed, the @ notification mechanism will continue to work here.

**Closed by MightyPen** 2019-01-09 01:43 UTC
Labels: Issue-Status-2-Author-will-triage
