### ISSUE TITLE
Database Engine Tuning Advisor does not support Azure SQL Database. 

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/sql-docs#6337] opened 2021-04-24 01:04 UTC
The statement “Applies to: yesSQL Server (all supported versions)” is misleading.
According to https://stackoverflow.com/questions/51495477/how-to-measure-the-performance-of-the-azure-sql-db

Database Engine Tuning Advisor does not support Azure SQL Database. 

It will be good to have a highlighted note for it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be91e580-4f7c-ff6f-902f-6109e4f1cbde
* Version Independent ID: c50ec4ee-d133-6bad-964b-d039459e0c01
* Content: [Tutorial: Database Engine Tuning Advisor - SQL Server](https://docs.microsoft.com/en-us/sql/tools/dta/tutorial-database-engine-tuning-advisor?view=sql-server-ver15)
* Content Source: [docs/tools/dta/tutorial-database-engine-tuning-advisor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/dta/tutorial-database-engine-tuning-advisor.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment] 2021-04-26 16:55
Duplicate of #6336.

**Closed by WilliamAntonRohm** 2021-04-26 16:55 UTC
Labels: Pri2, cba, duplicate, sql/prod, tools-other/tech
