### ISSUE TITLE
SHORTEN_PATH with different node (table) over the same edge (table)?

### ISSUE THREAD

**Issue by Elloudo** [MicrosoftDocs/sql-docs#4970] opened 2020-06-14 19:13 UTC
Hello!

in all the provided example of SHORTEN_PATH usage, the same node_alias "Person" is always used.

I am not sure to understand the usage and limitation of SHORTEN_PATH with different Node (table) using the same edge (table).

e.g, following relationship using the same edge table "likes" but with different Node tables:
- Person (Node) -> likes (Edge) -> Influencer(Node)
- Influencer(Node) -> likes (Edge) -> Song(Node)

Is it possible to get the list of all Songs liked by an Influencer liked by a Person using MATCH / SHORTENPATH

I have tried the following, but is does not what I had expected:

SELECT 
	P.Name As Person
	LAST_VALUE(S.Name) WITHIN GROUP (GRAPH PATH) AS [Song]
FROM
	Person P,
	Song S,
	likes FOR PATH as L
WHERE 
	MATCH(SHORTEST_PATH(P(-(L)->S)+))

   Thanks for your support
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d0352c-3838-e788-f99e-ba6171fe2acc
* Version Independent ID: 22c33c5e-8e6d-7bf8-cace-f59af7b5cc7f
* Content: [SHORTEST PATH (SQL Graph) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver15)
* Content Source: [docs/relational-databases/graphs/sql-graph-shortest-path.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-shortest-path.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @shkale-msft
* Microsoft Alias: **shkale**

**Comment by shkale-msft** [comment] 2020-06-15 18:38
> Hello!
> 
> in all the provided example of SHORTEN_PATH usage, the same node_alias "Person" is always used.
> 
> I am not sure to understand the usage and limitation of SHORTEN_PATH with different Node (table) using the same edge (table).
> 
> e.g, following relationship using the same edge table "likes" but with different Node tables:
> 
> * Person (Node) -> likes (Edge) -> Influencer(Node)
> * Influencer(Node) -> likes (Edge) -> Song(Node)
> 
> Is it possible to get the list of all Songs liked by an Influencer liked by a Person using MATCH / SHORTENPATH
> 
> I have tried the following, but is does not what I had expected:
> 
> SELECT
> P.Name As Person
> LAST_VALUE(S.Name) WITHIN GROUP (GRAPH PATH) AS [Song]
> FROM
> Person P,
> Song S,
> likes FOR PATH as L
> WHERE
> MATCH(SHORTEST_PATH(P(-(L)->S)+))
> 
> Thanks for your support
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 44d0352c-3838-e788-f99e-ba6171fe2acc
> * Version Independent ID: 22c33c5e-8e6d-7bf8-cace-f59af7b5cc7f
> * Content: [SHORTEST PATH (SQL Graph) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-shortest-path?view=sql-server-ver15)
> * Content Source: [docs/relational-databases/graphs/sql-graph-shortest-path.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-shortest-path.md)
> * Product: **sql**
> * Technology: ****


Hi @Elloudo, 
To find all Person who like an Influencer who like Songs, you can write following MATCH query:

create table Person(id integer, name varchar(20)) as node;
create table Influencer(id integer, name varchar(20)) as node;
create table Song(id integer, title varchar(500)) as node;
create table likes as edge;

insert into Person values(1,'Bob'),(2,'Alice'), (3,'Mike');
insert into Influencer values (1,'Alice'),(2,'Bob');
insert into Song values(1,'Heal the World'), (2,'Black or White'),(3,'Earth song');

insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Influencer where id=1));
insert into likes values((select $node_id from Person where id = 3),(Select $node_id from Influencer where id=2));
insert into likes values((select $node_id from Influencer where id = 1), (select $node_id from Song where id = 1));
insert into likes values((select $node_id from Influencer where id = 2), (select $node_id from Song where id = 2));
insert into likes values((select $node_id from Influencer where id = 1), (select $node_id from Song where id = 3));

select Person.name, Influencer.name, title
from 
	Person,
	Influencer,
	Song,
	likes l,
	likes l1
where match(Person-(l)->Influencer-(l1)->song)

You don't need Shortest_path to write this query. You will get a list of all songs liked by an Influencer by using a simple MATCH query.

Hope this helps.

Thanks,
shreya

**Comment by Elloudo** [comment] 2020-06-15 20:00
Hi Shreya,

thanks for your answer. Unfortunately this does not help, but because I have not formulated my example correctly, my mistake. Here a second try: I'd like to get the list of all songs liked by a person directely or indirectly: songs liked by a liked person, as well as the songs liked by a liked influencer. e.g: 

create table Person(id integer, name varchar(20)) as node;
create table Influencer(id integer, name varchar(20)) as node;
create table Song(id integer, title varchar(500)) as node;
create table likes as edge;

insert into Person values(1,'Bob'),(2,'Alice'), (3,'Mike');
insert into Influencer values (1,'Tibo'),(2,'Jack');
insert into Song values(1,'Heal the World'), (2,'Black or White'),(3,'Earth song');

-- Bob (Person)-> Heal the World (Song) 
--   | 
--    -> Alice (Person) -> Black or White (Song)
--   |
--    -> Tibo (Influencer) -> Earth song (Song)
insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Song where id=1));
insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Song where id=2));
insert into likes values((select $node_id from Person where id = 2),(Select $node_id from Influencer where id=2));
insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Influencer where id=1));
insert into likes values((select $node_id from Influencer where id = 1), (select $node_id from Song where id = 3));

select Person.name, title
from
Person,
Song,
likes l
where match(Person-(l)->Song)

-- Expected:

-- Bob	Heal the World
-- Bob	Black or White
-- Bob      Earth song


-- Actual:

-- Bob	Heal the World
-- Bob	Black or White
=> songs liked by a liked influencer missing

I hope this time, this is more clear. How can the expected results be achieved ?

Thanks
Ludo

**Comment by shkale-msft** [comment] 2020-06-16 00:48
Hi Ludo,

Thanks for clarification. Here is how you can implement that query:

select person.name, title
from 
	person,
	song,
	likes
where match(person-(likes)->song)
UNION ALL
select person.name, title
from
	person,
	song,
	influencer,
	likes,
	likes l1
where match(person-(likes)->influencer-(l1)->song)

You can replace UNION ALL with UNION if you need unique records. 

Shortest path can be used to search a pattern recursively in a graph/tree. For your usecase, however, you are just trying to find all nodes that satisfy a given condition and that can be done using a simple MATCH query. 

Hope this helps.

Thanks,
shreya

**Comment by Elloudo** [comment] 2020-06-16 20:56
Hi Shreya,

thanks. One step further, but still not there yet because the "UNION ALL" solution implies to know the complete internal sequence of the graph. 
Actually what I need, is a way to recursively go through the graph, independently of the node type ("Person" or "Influencer) using the "likes" edge, starting from a give node. That's why I thought first that "SHORTEST_PATH" would be appropriate. See the new example below. I have managed to get the expected results using a "UNION ALL" for each combination in the database. But if the new sequence is added (e.g Person1-likes->Person2->likes->Person3-likes->Influencer1->likes-Person4-likes->Influencer2->likes->Song1), I would not get the relation between Person1  and Song1.

Is there a way to get exactely the same results as the example below, using recursive parsing of the graph and without the UNION ALL of all possible combinations ?

create table Person(id integer, name varchar(20)) as node;
create table Influencer(id integer, name varchar(20)) as node;
create table Song(id integer, title varchar(500)) as node;
create table likes as edge;

insert into Person values(1,'Bob'),(2,'Alice'), (3,'Mike'), (4, 'Thomas');
insert into Influencer values (1,'Tibo'),(2,'Jack');
insert into Song values(1,'Heal the World'), (2,'Black or White'),(3,'Earth song'),(4,'Ocean'),(5,'My Lighthouse'),(6,'Relentless');

insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Person where id=2));
insert into likes values((select $node_id from Person where id = 2),(Select $node_id from Person where id=3));
insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Song where id=1));
insert into likes values((select $node_id from Person where id = 2),(Select $node_id from Song where id=2));
insert into likes values((select $node_id from Person where id = 3),(Select $node_id from Song where id=3));

insert into likes values((select $node_id from Person where id = 1),(Select $node_id from Influencer where id=1));
insert into likes values((select $node_id from Influencer where id = 1),(Select $node_id from Influencer where id=2));
insert into likes values((select $node_id from Influencer where id = 1),(Select $node_id from Song where id=4));
insert into likes values((select $node_id from Influencer where id = 2),(Select $node_id from Song where id=5));
insert into likes values((select $node_id from Influencer where id = 2),(Select $node_id from Person where id=4));
insert into likes values((select $node_id from Person where id = 4),(Select $node_id from Song where id=6));

select person.name, title
from
person,
song,
likes
where match(person-(likes)->song)
and person.ID = '1'
UNION ALL
select person.name, title
from
person,
person person1,
song,
likes,
likes l1
where match(person-(likes)->person1-(l1)->song)
and person.ID = '1'
UNION ALL
select person.name, title
from
person,
person person1,
person person2,
song,
likes,
likes l1,
likes l2
where match(person-(likes)->person1-(l1)->person2-(l2)->song)
and person.ID = '1'
UNION ALL
select person.name, title
from
person,
influencer,
song,
likes,
likes l1
where match(person-(likes)->influencer-(l1)->song)
and person.ID = '1'
UNION ALL
select person.name, title
from
person,
influencer,
influencer influencer1,
song,
likes,
likes l1,
likes l2
where match(person-(likes)->influencer-(l1)->influencer1-(l2)->song)
and person.ID = '1'
UNION ALL
select person.name, title
from
person,
person person1,
influencer,
influencer influencer1,
song,
likes,
likes l1,
likes l2,
likes l3
where match(person-(likes)->influencer-(l1)->influencer1-(l2)->person1-(l3)->song)
and person.ID = '1'

Thanks!
Ludo

**Comment by Elloudo** [comment] 2020-06-24 09:05
Hey Shreya, any news on this topic ? Merci

**Comment by shkale-msft** [comment] 2020-06-25 00:43
Hi @Elloudo ,

Sorry for the late reply. Here is a shortest path query that you can use. There are few things to note here:

0. This query is failing on Azure due to a regression right now, will be fixed soon. You can try this on SQL Server 2019 RTM release. Let me know if you are running your application on Azure. We can enable the fix on your server, so that you can test it there. 
1. The view definition PIn, which combines both Person and Influencer node types into one view. 
2. Use of view Pin in the shortest path query, as opposed to Person/Influencer.
3. Use of LAST_NODE() function to read the last node value, that is received from the pin-likes->pin recursion. We take that last node received and check if they like a song. 
4. The shortest path query begins from person 'Bob', you can change it to any person or remove that filter completely to get all person who like another person/influencer, who like a song. 
5. We need that UNION query in the end, to get all person who like a song directly. Since MATCH does not support OR, I am reading those results with the help of UNION. You can also implement it in other ways. 

CREATE VIEW PIn AS
SELECT * FROM Person
UNION ALL
SELECT * FROM Influencer
GO

select 
	title, 
	pin2.name,
	string_agg(pin1.name,'->') within group (graph path) 
from
	Song as Song,
	PIn for path as pin1,
	PIn as pin2,
	likes for path as likes1,
	likes as likes2
where
	match(shortest_path(pin2(-(likes1)->pin1)+) AND last_node(pin1)-(likes2)->song) 
	and pin2.name = 'Bob'
UNION
select
	title,
	name,
	''
from
	song,
	person,
	likes
where match(person-(likes)->song)
and person.name='Bob'


Let me know if you have any questions.

Thanks,
shreya

**Comment by Elloudo** [comment] 2020-06-25 19:25
Thank you very much. The proposed solution looks great. I am now clarifying with the admins of my company if they allow that you install the fix on our server. I'll go back to you soon. 

Regards,
Ludo

**Comment by Elloudo** [comment] 2020-06-30 21:23
Hi Shreya,

Here the detail about the server version we are using:
Product Version: 12.0.2000.8
Product Level: RTM
Edition: SQL Azure
Engine Edition: 5
Major Version: 12
version: Microsoft SQL Azure (RTM) 12.0.2000.8 May 15... 

Is it possible for you to contact my admin directly to discuss the details on how to patch the fix on our company server ?

Contact
Shahid Mukadam
Email: Shahid.Mukadam@harman.com
Availability: Shahid is in IST time zone and is available for meeting after 2:30 PM IST (Mon-Fri).

Thank you very much!
Ludo

**Comment by shkale-msft** [comment] 2020-06-30 21:26
Hi @Elloudo ,

I will reach out to Shahid over email and ask him to keep you in loop.

Thanks,
shreya

**Comment by shkale-msft** [comment] 2020-07-03 07:21
Hi @Elloudo ,

I did reach out to Shahid over email, but have not heard back from them yet. If you share your emailID, I can forward the email to you.

thanks,
shreya

**Comment by Elloudo** [comment] 2020-07-03 09:57
Thanks. Yes of course I forgot to add it: ludovic.weber@harman.com

**Comment by rothja** [comment] 2020-09-24 18:35
@Elloudo It looks like you are working with @shkale-msft outside of this issue, so I will be closing this now. Thank you!

**Closed by rothja** 2020-09-24 18:35 UTC
Labels: /tech, Pri2, assigned-to-author, doc-bug, sql/prod
