### ISSUE TITLE
"SQL Server Previous Versions Documentation" page contains dead links for most prior SQL Server versions

### ISSUE THREAD

**Issue by SimonEData** [MicrosoftDocs/sql-docs#9211] opened 2023-08-03 21:48 UTC
This page contains a link to online documentation for versions of SQL Server prior to SQL Server 2016: "SQL Server previous versions documentation", https://learn.microsoft.com/en-us/previous-versions/sql/.  That page contains dead links for SQL Server versions 2005 to 2012.  Only the link to SQL Server 2014 is still active.  

If the only way to obtain documentation for SQL Server 2005 to 2012 is to download offline documentation please state that rather than give us false hope by directing us to a page which turns out to be dead links.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 444e750b-2eb3-722c-bd43-16963e35248a
* Version Independent ID: b4351b94-6403-4efa-9e8f-3738211ce849
* Content: [Previous versions of SQL Server documentation - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/previous-versions-sql-server?view=sql-server-2016#offline-documentation)
* Content Source: [docs/sql-server/previous-versions-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/previous-versions-sql-server.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by rwestMSFT** [comment] 2023-08-03 22:08
Duplicate of https://github.com/MicrosoftDocs/sql-docs/issues/9193.

**Closed by rwestMSFT** 2023-08-03 22:08 UTC
Labels: Pri1, sql/svc, install/subsvc
