### ISSUE TITLE
Steps do not work on Windows 10 1809 and Docker 18.X LCOW or 19.X LCOW

### ISSUE THREAD

**Issue by watfordgnf** [MicrosoftDocs/sql-docs#2414] opened 2019-07-01 15:24 UTC
These steps are not possible to follow on Windows 10 1809 and Docker 18.X LCOW or 19.X LCOW. Under prerequisites it notes: 
"...on any supported Linux distribution or **Docker for Mac/Windows**..."

1. You cannot follow these steps on Windows 10 1809 with Docker 18.X LCOW because you cannot launch Linux containers with the `-m` flag. You then install Docker Engine 19.X (edge).
2. You cannot follow these steps on Windows 10 1809 with Docker 19.X LCOW because when you mount a storage volume with `-v`, SQL Server crashes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd398c1-ed8b-911b-f11a-3739d80b3f32
* Version Independent ID: dc3d55ff-3b55-a686-81f9-f4188054e381
* Content: [Restore a SQL Server database in Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-2017#feedback)
* Content Source: [docs/linux/tutorial-restore-backup-in-sql-server-container.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-restore-backup-in-sql-server-container.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment] 2019-07-01 17:46
@watfordgnf -- thank you for your feedback.  We will look into this issue.

@rothja -- please process this Issue 2414.

**Comment by watfordgnf** [comment] 2019-07-01 17:52
For point (2) above I'm unable to copy out the core dumps because the container never finishes writing them before stopping. I've added what details I do have to https://github.com/microsoft/mssql-docker/issues/441

**Comment by rothja** [comment] 2019-07-02 14:01
@watfordgnf Thank you for this feedback. I'll see if I can reproduce this. We want the documentation to be accurate. I'll try to get back to you within a few business days. Thank you for your patience.

**Comment by rothja** [comment] 2019-07-15 16:46
@watfordgnf Thanks for reporting this. I just went through the steps on my Windows 10 machines with the latest 18 version of LCOW, and it worked without any errors. I'm not sure what the difference might be. At this point, the best course of action might be to open a support case with Microsoft to investigate. I'm sorry I can't reproduce, and I apologize for the delay in my test and response. At this time, I am going to close this git issue, but you can reply with any new information. I also will keep a lookout if other customers report the same issues. Thank you!

**Comment by watfordgnf** [comment] 2019-07-15 17:07
Alright, I'll follow https://github.com/microsoft/mssql-docker/issues/441 for the fix then I guess. Thanks.

**Comment by rothja** [comment] 2019-07-15 17:12
@watfordgnf It does look to be an issue, so my configuration must not be right for reproducing. I'll forward this to our product team directly as well. Sorry that I don't have an answer right now for you.

**Comment by mirsaeedi** [comment] 2019-07-23 17:38
I have this problem too with **_mcr.microsoft.com/mssql/server:2017-latest_** and **_mcr.microsoft.com/mssql/server:2019-CTP3.1-ubuntu_** on Windows Server 2019 version 1809.

I cannot mount a data volume using the -v flag. docker logs give me following error:

```
This program has encountered a fatal error and cannot continue running at Tue Jul 23 17:30:19 2019
The following diagnostic information is available:

       Reason: 0x00000006
      Message: Kernel bug check
      Address: 0x6b448190
   Parameters: 0x10861f670
   Stack Trace:
               000000006b5344ce
               000000006b4481eb
               000000006b4344f6
               000000006b443622
               000000006b5327fc
               000000006b531019
               000000006b575331
        Process: 7 - sqlservr
         Thread: 11 (application thread 0x4)
    Instance Id: 43329e1c-dbf3-42a8-a284-44fbea6ae8c8
       Crash Id: 56a5abba-136b-42c7-9ab2-91dbec5b08ed
    Build stamp: 4a92842108074d858c9f7d8bbbc88360b2a93d7fe17df31bdef8b95495870f81
   Distribution: Ubuntu 16.04.6 LTS
     Processors: 3
   Total Memory: 6227410944 bytes
      Timestamp: Tue Jul 23 17:30:19 2019
     last_errno: 2
last_errno_text: No such file or directory

Ubuntu 16.04.6 LTS
Capturing core dump and information to /var/opt/mssql/log...
dmesg: read kernel buffer failed: Operation not permitted
No journal files were found.
No journal files were found.
Tue Jul 23 17:30:19 UTC 2019 Capturing program information
Tue Jul 23 17:30:20 UTC 2019 Attempting to capture a dump with paldumper
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper
WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.7.temp/log/paldumper-debug.log for details
Tue Jul 23 17:30:20 UTC 2019 Attempting to capture a dump with gdb
WARNING: Unable to capture crash dump with GDB. You may need to
allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
run as root.
Tue Jul 23 17:30:20 UTC 2019 Capturing program binaries
Tue Jul 23 17:30:20 UTC 2019 Compressing the dump files
```

**Comment by simonpinn** [comment] 2019-09-11 02:14
+1 same issue here Windows 10 1803 docker desktop 2.1.2.0

**Comment by rothja** [comment] 2019-09-11 14:15
@mirsaeedi @simonpinn Thanks for the additional configuration details. I'll try to look into this more and reply on this thread.

**Comment by simonpinn** [comment] 2019-09-12 00:53
@rothja I had some success changing the volume mount to include */data* so:
```
    docker run `
        -e 'ACCEPT_EULA=Y' `
        -e '!VeryStrongPwd01' `
        -p 1433:1433 `
        --name 'sqlserver' `
        --rm `
        -m 4GB `
        -v 'c:/data/mssql:/var/opt/mssql/data/' `
        -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
```
However this only mounts the data dir, which as it happens is enough for me, as I want to persist the *mdf/*.ldf's - however it isn't as describe in documentation, and logs etc are not mounted.

thanks

**Comment by SeanFeldman** [comment] 2019-12-06 08:25
When a LinuxVM host is used and a volume name is specified, this approach works.
When using Windows Desktop Docker and mounting to a Windows path, `data` has to be added to the Linux path (`-v /d/mssql-data/tcenergy-gsmos:/var/opt/mssql/data`) for the container to start. Otherwise, SQL Server crashes with an error "file not found".

**Comment by SeanFeldman** [comment] 2019-12-06 08:29
@rothja could you please re-open the issue as it still holds true. The sample fails if commands are executed as-is on Windows 10 1909 as well.

**Comment by rothja** [comment] 2019-12-06 16:28
@SeanFeldman Yes. I'll reopen and thanks for the additional information. We'll investigate and update the documentation (and if it is a bug, we'll make sure to get it reported). Thank you!

**Comment by rothja** [comment] 2020-01-07 15:09
@SeanFeldman @simonpinn @watfordgnf I reproduced the problems described here. When the data directory is mapped to, you can successfully map to a volume on your Windows machine. But the entire mssql directory results in a crashed container. However, it is possible to follow the tutorial when you use a data volume (named and not mapped to a local path). I know that is not what is wanted here and not the problem being reported. I'll report this problem and get the articles updated with a note before closing the issue again. For now, I think the solution is named data volumes with docker OR mapping a specific directory like data. You can still get to the files in the container with `docker exec -it` commands for other data if needed. I'm sorry for the inconvenience of this though! I hope we can get it fixed in the future.

**Closed** 2020-01-07 15:58 UTC
Labels: Pri2, assigned-to-author, linux/tech, sql/prod, support-request

**Comment by SeanFeldman** [comment] 2020-01-07 18:44
> I'll report this problem and get the articles updated with a note before closing the issue again.

Could you please provide a link to track that work?

**Comment by rothja** [comment] 2020-01-07 21:49
Thanks, @SeanFeldman. I have updated the articles, which should publish soon. On the reporting side, I've spoken with the PM who owns Linux containers, and he is actively researching the issue to see what the solution should be. I don't have a link to share for that work though, sorry.
