### ISSUE TITLE
mssql-server on Ubuntu linux 22.04 doesn't start, system databases missing.

### ISSUE THREAD

**Issue by programingfrik** [MicrosoftDocs/sql-docs#9529] opened 2023-12-04 19:24 UTC
A few days ago, I followed all the steps in the article guide and during the installation there were no error messages or anything wrong, as far as I know.

After the installation, I ran the "sudo /opt/mssql/bin/mssql-conf setup" everything fine no error, no complains.

When I ran "systemctl status mssql-server" the result is :

    - date/time server systemd[1]: mssql-server.service: Failed with result 'exit-code'.
    - date/time server systemd[1]: mssql-server.service: Consumed 3.526s CPU time.
    - date/time server systemd[1]: mssql-server.service: Scheduled restart job, restart counter is at 3.
    - date/time server systemd[1]: Stopped Microsoft Sql Server Database Engine.
    - date/time server systemd[1]: mssql-server.service: Consumed 3.526s CPU time.
    - date/time server systemd[1]: mssql-server.service: Start request repeated too quickly.
    - date/time server systemd[1]: mssql-server.service: Failed with result 'exit-code'.
    - date/time server systemd[1]: mssql-server.service: Failed to start Microsoft SQL Server Database Engine

If I try to connect to the database with "sqlcmd -S .\" it says "Login timeout expired" and "TCP Provider: Error code 0x2743". I suposse that it can't connect because the service is not runnig.

On the log "/var/opt/mssql/log/errorlog" there are some errors, I think that the main thing is some database files that it says it "could not open".

    - ...
    - Starting up database 'msdb'.
    - Starting up database 'mssqlsystemresource'.
    - The resource database build version is 16.00.4095. This is an informational message only. No user action is requerierd.
    - Failed to get the volume information, -1073741772
    - Failed to get the volume information, -1073741772
    - Error 17204, Severity: 16, State: 1
    - FCB::Open failed: Could not open file D:\dbs\sh\el1q\0921_171548\cmd\e\obj\x64retail\sql\mkmastr\databases\mkmastr.proj\MSDBData.mdf for file number 1. OS error: 2 (The system cannot find the file specified.)"
    - [3]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1. ConcurrentGAMUpdate: 1. ConcurrentSGAMUpdate: 1, CleanupUnderUserTransaction: 0. TransLevelPVS: 0
    - Error: 5120, Severity: 16, State: 101.
    - Unable to open the physical file "D:\dbs\sh\el1q\0921_171548\cmd\e\obj\x64retail\sql\mkmastr\databases\mkmastr.proj\MSDBData.mdf". Operating system error 2: "2(The system cannot find the file specified.)"
    - Starting up database 'model'.
    - Failed to get the volume information, -1073741772
    - Failed to get the volume information, -1073741772
    - Failed to get the volume information, -1073741772
    - Error 17204, Severity: 16, State: 1.
    - FCB::Open failed: Could not open file D:\dbs\sh\el1q\0921_171548\cmd\e\obj\x64retail\sql\mkmastr\databases\mkmastr.proj\model.mdf for file number 1. OS error: 2 (The system cannot find the file specified.)"
    - ...

The errors continue with the other system database files.

I was reading that when the system database files are missing or corrupted, on windows, one is supposed to "rebuild the system database files", but I haven't found any way to do this with the files on the linux installation packages.

Hope this information is useful, I'd like to see mssql-server running on my linux machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver16&tabs=ubuntu2004)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2023-12-04 19:46
I am closing this issue because we do not offer support in this repository. Thanks for stopping by.

**Closed** 2023-12-04 19:45 UTC
Labels: Pri1, sql/svc, linux/subsvc

**Comment by rwestMSFT** [comment] 2023-12-04 23:41
We are going to add an entry to the **Known issues** section of the SQL Server 2022 release notes, and I have escalated this issue internally.

**Comment by programingfrik** [comment] 2023-12-05 02:38
I understand that I'm not supposed to get support on the issues of the article / guide. I just wanted to inform that following the instructions on this article might not lead to the desired result, that maybe, there is a problem with the instruction on the page, maybe with the packages, maybe with my OS and with others. I thought it was relevant. To be honest I´m not sure where I must ask for support, maybe that could be something to include in the article "if you have any problem post to this or that page".

Thanks for the single user tip, the database engine doesn't start not even in single user mode. I'll keep trying thank you.

**Comment by rwestMSFT** [comment] 2023-12-05 17:01
Is this using a VM or container?

**Comment by programingfrik** [comment] 2023-12-10 01:07
No, not a virtual machine, not a container. A real computer, a system 76 pangolin 12 laptop with Pop OS linux 22.04 that is supposed to be compatible with ubuntu 22.04. I mean, I use Ubuntu repositories without any issues. I followed the instructions on the article because I wanted to install mssql-sever directly on my system.

**Comment by rwestMSFT** [comment] 2023-12-11 16:18
Thanks for confirming. We need as much information as you can provide to help us reproduce this problem.
