### ISSUE TITLE
Error following SQL Server Installation On Linux

### ISSUE THREAD

**Issue by jcastiblanco** [MicrosoftDocs/sql-docs#9530] opened 2023-12-04 21:52 UTC
[Enter feedback here]
I had the following error trying to install SQL server 2022 on Ubuntu 2204 following the steps in the document:
Configuring SQL Server...

/opt/mssql/bin/sqlservr: error while loading shared libraries: liblber-2.4.so.2: cannot open shared object file: No such file or directory
Setup has completed successfully. SQL Server is now starting.
azureuser@sqlsvronlinux:~$ systemctl status mssql-server --no-pager
× mssql-server.service - Microsoft SQL Server Database Engine
     Loaded: loaded (/lib/systemd/system/mssql-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-12-04 21:48:41 UTC; 15s ago
       Docs: https://docs.microsoft.com/en-us/sql/linux
    Process: 7238 ExecStart=/opt/mssql/bin/sqlservr (code=exited, status=127)
   Main PID: 7238 (code=exited, status=127)
        CPU: 2ms

Dec 04 21:48:41 sqlsvronlinux systemd[1]: mssql-server.service: Scheduled restart job, restart counter is at 4.
Dec 04 21:48:41 sqlsvronlinux systemd[1]: Stopped Microsoft SQL Server Database Engine.
Dec 04 21:48:41 sqlsvronlinux systemd[1]: mssql-server.service: Start request repeated too quickly.
Dec 04 21:48:41 sqlsvronlinux systemd[1]: mssql-server.service: Failed with result 'exit-code'.
Dec 04 21:48:41 sqlsvronlinux systemd[1]: Failed to start Microsoft SQL Server Database Engine.
azureuser@sqlsvronlinux:~$

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-ver16&preserve-view=true&tabs=ubuntu2004)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2023-12-04 23:12
This is a duplicate of https://github.com/MicrosoftDocs/sql-docs/issues/9529.

> It looks like you might have to start the service in single user mode, and tell the `master` database where your database files are actually located, using `ALTER DATABASE ... MODIFY FILE` for all the databases affected, then restart the service again.

I am closing this because it is a support issue, not a Docs issue.

**Closed by rwestMSFT** 2023-12-04 23:12 UTC
Labels: Pri1, sql/svc, linux/subsvc

**Comment by rwestMSFT** [comment] 2023-12-04 23:41
We are going to add an entry to the **Known issues** section of the SQL Server 2022 release notes, and I have escalated this issue internally.
