### ISSUE TITLE
syntax and error thrown

### ISSUE THREAD

**Issue by emad-almousa** [MicrosoftDocs/sql-docs#7941] opened 2022-08-15 17:05 UTC
Hi,
when you execute a statement like the below:

RESTORE DATABASE dummydb
FROM DISK='D:\snapshot_backup\db.bkm'
WITH METADATA_ONLY, FILE=3, DBNAME='testdb1', --> restores testdb3 database
MOVE 'testdb1' TO 'D:\snapshot_backup\testdb1.mdf',
MOVE 'testdb1_log' TO 'D:\snapshot_backup\testdb1_log.ldf'

the following error is thrown:

**Msg 3102, Level 16, State 1, Line 1
RESTORE cannot process database 'dummydb' because it is in use by this session. It is recommended that the master database be used when performing this operation.
Msg 3013, Level 16, State 1, Line 1
RESTORE DATABASE is terminating abnormally.**

you need to add at the beginning of the script:
**use [master]**

can you kindly check ?
Regards,
Emad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Version Independent ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Content: [Create a T-SQL Backup - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @perrysk-msft
* Microsoft Alias: **peskount**

**Comment by rwestMSFT** [comment] 2022-08-15 20:07
Prior to that example, you'll see the following text:

> If testdb1 already exists on the server, include the REPLACE clause.

Does that resolve your issue?

**Comment by emad-almousa** [comment] 2022-08-18 16:53
Different Error:
Msg 3287, Level 16, State 1, Line 1
The file ID 3 on device 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\dummydb.bkm' is incorrectly formed and can not be read.
Msg 3013, Level 16, State 1, Line 1
RESTORE DATABASE is terminating abnormally.

i would recommend if someone from Microsoft goes through the SQL Scripts provided again to verify they are working fine with MSSQL 2022 CTP release.
Thanks for your feedback.

**Comment by rwestMSFT** [comment] 2023-04-24 22:54
@emad-almousa I am unable to reproduce your issue. Please can you check again. In the meantime I am closing this issue. Feel free to respond below if you have anything new to share.

**Closed by rwestMSFT** 2023-04-24 22:54 UTC
Labels: sql/prod, backup-restore/tech, needs-more-info, assigned-to-author, Pri2, sql/svc, backup-restore/subsvc
