### ISSUE TITLE
[Question] Should code examples be self-contained?

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#2042] opened 2019-05-01 15:55 UTC
@MightyPen Wondering if there is any style guideline with regards to code examples in sql-docs?

For example, https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-sql-referenced-entities-transact-sql.md has an Example E that extends Example D.  Example E requires clicking the copy button for Example D, pasting it into SSMS, then click the copy button for Example E, pasting that into SSMS, and then clicking execute.

In my 2 cents, I think examples that combine multiple concepts should become _samples_.  I realize overly restrictive rules like these can create burdens and be counter-productive, but as a developer, I just want to immediate copy-paste something and play with it.

Further, in this example, it is using AdventureWorks2012 database, but I don't see why it can't just create a database called Test instead, so that the example is immediately runnable.  Long-term, with C# moving to more interactive examples you can execute online in your browser (without an IDE), it would be nice if the SQL examples became self-contained so they could run in http://www.sqlfiddle.com/ or equivalent in the future.

**Comment by MightyPen** [comment] 2019-05-01 18:02
@jzabroski Hi John, There is a perpetual debate about making small-to-medium size T-SQL examples dependent on AdventureWorks db (or dependent on WideWorldImporters db, etc). Certainly the majority of our SQL examples to Not rely on A.W. db, and that is very unlikely to change. As you implied, the use of A.W. db for routine SQL examples would present a barrier to quick testing by customers.

In the specific T-SQL examples 'D' and 'E' that you cited (and 'A-C'), it seems that their initial uses of the 'USE AdventureWorks2012' statement are pointless, because the rest of their T-SQL code uses nothing in A.W. db. Perhaps those two 'USE...' lines should simple be removed.
Example 'F' might be odd, because it might rely on A.W. db for the return data that would match the data shown in the article; yet 'F' lacks the 'USE AdventureWorks2012' statement.
At least those are my impressions from a quick first glance.

Our team discussed this exact question about the use of A.W. db on April/19, so we are aware of the situation. Feedback on this question, such as this feedback from you today, helps inform our discussions. I am forwarding your comments onward to the relevant documentation team.

And thanks for your mention of SqlFiddle.com.

So, you points are noted, well-taken, and have been sent to the whole SQL documentation team.  I'll think about whether/how to edit the article.
I am now Closing this Issue 2042.
(The @ notification system continues to work regardless of whether the Issue is Closed.)

CC: @stevestein

**Closed by MightyPen** 2019-05-01 18:02 UTC
Labels: doc-idea

**Comment by MightyPen** [comment] 2019-05-01 22:36
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10100

**Comment by jzabroski** [comment] 2019-05-01 22:41
@MightyPen Thanks for fixing this and all the additional context.  [You're my docu-hero](https://teesgreat.site/-all-hail-the-technical-writer---unisex-t-shirt/).

> And thanks for your mention of SqlFiddle.com.

My personal favorite is actually SqlBolt.  If you go to, https://sqlbolt.com/lesson/select_queries_introduction , at the bottom of the page there is a live example.  If you add a "WHERE Year = 1995", the data grid instantly refreshes.  It's like typing on a piano, which, as Peter Norvig mentions in [Teach Yourself Programming in 10 Years](http://norvig.com/21-days.html), is quite essential to mastery.
