### ISSUE TITLE
Mention of shortcoming?

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#8163] opened 2022-10-09 22:28 UTC
IS it worth calling out specifically that you cannot have a filtered index on a computed column?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1a74397-d56d-27dc-5264-3f2a96a905d0
* Version Independent ID: e6d4eb37-e5d1-4adc-b5e9-9dbbd0f8eb2f
* Content: [Indexes on Computed Columns - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/indexes-on-computed-columns?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/indexes-on-computed-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/indexes-on-computed-columns.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment] 2022-10-10 08:04
@brettshearer -- Brett, thank you for your suggestion.

@MikeRayMSFT -- Mike, please look into this issue.

**Comment by rwestMSFT** [comment] 2022-10-14 19:55
Duplicate of https://github.com/MicrosoftDocs/sql-docs/issues/7916.

#reassign:rwestMSFT

**Comment by rwestMSFT** [comment] 2022-10-14 19:57
This isn't an exact duplicate, but it's worth calling out and I'll address it in an internal PR.

#please-close

**Closed by rwestMSFT** 2022-10-14 19:57 UTC
Labels: sql/prod, table-view-index/tech, doc-bug, assigned-to-author, Pri2
