### ISSUE TITLE
Minor correction regarding the use of RECONFIGURE

### ISSUE THREAD

**Issue by SQLSteinar** [MicrosoftDocs/sql-docs#8409] opened 2022-12-21 09:32 UTC
In this section: https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver16#categories-of-configuration-options 
the following text 
"After performing the above actions and restarting the instance of SQL Server." 
should be changed to 
"Restarting the instance of SQL Server."

In my tests, if I run for example "exec sp_configure 'remote access', 0" without running RECONFIGURE, then restart the server, the "remote access" value_is_use column is still updated to 0
I also tested this using the example in https://learn.microsoft.com/en-us/sql/t-sql/language-elements/reconfigure-transact-sql?view=sql-server-ver16 , and it still behaves the same way for options that require RECONFIGURE WITH OVERRIDE. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32e9c4f8-ec32-ff5f-93a4-8f07b664db5f
* Version Independent ID: 2111d777-a999-dc99-a3e5-cc7e7877c9b8
* Content: [Server Configuration Options (SQL Server) - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/server-configuration-options-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/server-configuration-options-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/server-configuration-options-sql-server.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2022-12-21 20:52
@SQLSteinar Thank you. If you don't mind, it would be really helpful if you make this change in a pull request, using the pencil icon on the top right of the article in question.

**Comment by SQLSteinar** [comment] 2022-12-22 08:02
Done!

**Comment by rwestMSFT** [comment] 2022-12-23 23:42
@SQLSteinar I'm revisiting this. The wording is correct as currently written, which you have confirmed in your assertion. In other words, before you restart, you still need RECONFIGURE.

I'm going to close this, but I will review the wording to be less ambiguous in a future update.

**Comment by rwestMSFT** [comment] 2022-12-24 00:10
@SQLSteinar I'm revisiting this. The wording is correct as currently written. In other words, before you restart, you should still run RECONFIGURE.

I'm going to close this, but I will review the wording to be less ambiguous in a future update.

**Closed** 2022-12-24 00:20 UTC
Labels: doc-bug, assigned-to-author, Pri1, sql/svc, configuration/subsvc

**Comment by SQLSteinar** [comment] 2022-12-29 10:45
Hello [rwestMSFT](https://github.com/rwestMSFT) In my tests RECONFIGURE was not needed before restart. RECONFIGURE is needed for settings to take effect immedeately, without restart.

**Comment by rwestMSFT** [comment] 2022-12-29 18:05
I understand what you're saying. What I and the documentation are saying is that you should run RECONFIGURE (or RECONFIGURE WITH OVERRIDE) when making a configuration change, because that's the supported way of doing so. Restarting the SQL Server instance just to make a change take effect shouldn't be a regular thing, so it doesn't make sense to encourage that.

**Comment by SQLSteinar** [comment] 2023-01-02 08:12
Ah, thanks for the explanation and your time! Makes sense
