### ISSUE TITLE
Bad link for SQL Docker for Windows Containers

### ISSUE THREAD

**Issue by briglx** [MicrosoftDocs/sql-docs#7081] opened 2021-12-02 23:00 UTC
[Enter feedback here]

The link in the paragraph "The Windows image is not covered, but you can learn more about it on the mssql-server-windows-developer Docker Hub page." is a bad link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-powershell)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment] 2021-12-03 20:02
@briglx -- Brig, thank you for bringing this to our attention.  I am updating the article.

**Comment by WilliamAntonRohm** [comment] 2021-12-20 03:14
Duplicate of #7069.

**Closed by WilliamAntonRohm** 2021-12-20 03:14 UTC
Labels: duplicate, sql/prod, linux/tech, doc-bug, cba, Pri2
