### ISSUE TITLE
The "Create Database" section shouldn't be in this tutorial

### ISSUE THREAD

**Issue by edfreeman** [MicrosoftDocs/sql-docs#6187] opened 2021-03-16 16:29 UTC
The "[Create Database](https://docs.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-azure-synapse-analytics?view=sql-server-ver15#create-a-database)" section of this quickstart has been copied from the other quickstarts (e.g. https://docs.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-sql-server?view=sql-server-ver15), but it doesn't apply to Synapse SQL Dedicated Pool since there's currently a 1-1 relationship between a pool and a database. Having this section there is confusing and misleading, and should probably be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44dfd531-9137-f316-7cc3-9dd4bb8ca157
* Version Independent ID: a3f715bb-bad4-d722-84c5-9dc54ed4d53a
* Content: [Connect and query a dedicated SQL pool in Azure Synapse Analytics with SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/quickstarts/ssms-connect-query-azure-synapse-analytics?view=sql-server-ver15)
* Content Source: [docs/ssms/quickstarts/ssms-connect-query-azure-synapse-analytics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/quickstarts/ssms-connect-query-azure-synapse-analytics.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment] 2021-03-16 20:57
@edfreeman -- Ed, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment] 2021-03-23 02:07
@edfreeman,

Thank you for your contribution.

I went through the tutorial myself to verify that the script and "creating the database" work as intended.

 Are you explaining that when creating this particular sample database it does not work with Synapse?
 
 @julieMSFT for reference.

**Comment by markingmyname** [comment] 2021-03-23 17:10
@edfreeman 

also to add, we kept the section to show a full experience on how to connect to a Synapse pool after creating a database.

**Comment by markingmyname** [comment] 2021-03-23 18:01
@azaricstefan for assistance

**Comment by azaricstefan** [comment] 2021-03-23 18:14
@edfreeman this is correct, thanks for creating an issue, we will update the docs.
@nanditavalsan for awareness.

**Comment by julieMSFT** [comment] 2021-04-30 21:19
#assign:julieMSFT

**Comment by julieMSFT** [comment] 2021-04-30 21:23
Hi @edfreeman Thank you for contacting Microsoft. You are correct in stating that the create database section does not belong. Thank you for bringing this to our attention. I am updating the article and you should see the updates in the next day or so. I will go ahead with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment] 2021-04-30 22:16
#please-close

**Closed by julieMSFT** 2021-04-30 22:16 UTC
Labels: Pri1, assigned-to-author, doc-bug, sql/prod, ssms/tech
