### ISSUE TITLE
Official support for ubuntu 18.04

### ISSUE THREAD

**Issue by ali-syria** [MicrosoftDocs/sql-docs#1803] opened 2019-03-20 22:07 UTC
Hi

Any news about release time of version that supports ubuntu 18.04

**Comment by stevestein** [comment] 2019-03-22 17:46
@ali-syria - thanks for opening a doc issue! Can you provide some additional information as to what type of ubuntu support you're interested in?  

-Thanks

**Comment by robinwilson16** [comment] 2019-03-24 18:27
I have just seen this now but have just logged an issue about exactly the same thing here:
#1816

@stevestein the issue is that the documentation and the product only officially support Ubuntu 16.04 released 3 years ago and not even the most recent long term servicing release which is 18.04 released April 2018.

**Comment by stevestein** [comment] 2019-04-08 17:45
@robinwilson16 - thanks!
Closing this because the issue is being tracked with the specific article in #1816

**Closed by stevestein** 2019-04-08 17:45 UTC
Labels: Issue-Status-10-New-need-more-info
