### ISSUE TITLE
sys.query_store_wait_stats needs clarification on threadpool waits

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#6444] opened 2021-05-27 18:55 UTC
There is an asterisk for `RESOURCE_SEMAPHORE_QUERY_COMPILE` noting that compilation waits are not actually tracked:

![image](https://user-images.githubusercontent.com/2136037/119880807-9c668d00-befa-11eb-9764-561f554946f0.png)

As much as I'd love to have that, I understand why it's not in there. However, I think this also applies to `THREADPOOL` waits, since they are _pre-compilation_. 

![image](https://user-images.githubusercontent.com/2136037/119880906-bb651f00-befa-11eb-8e33-c7b1ea2b0912.png)

I've experimented by running a workload that generates a good amount of `THREADPOOL` waits in a database that has Query Store turned on, with wait stats collection enabled. During that workload, ~700 queries hit `THREADPOOL` waits, but none of the worker waits ended up in `sys.query_store_wait_stats`. 

Over the course of the workload, these queries did complete, so there should have been some trace of the waits. I can see the queries in Query Store, and I can see other waits for them, but no worker thread waits.

Thanks!

**Comment by WilliamAntonRohm** [comment] 2021-05-27 20:11
@erikdarlingdata -- Erik, thank you for your considered feedback.  It looks like you're referring to the article [sys.query_store_wait_stats (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-wait-stats-transact-sql).

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by erikdarlingdata** [comment] 2021-05-27 20:13
@WilliamAntonRohm yes, thank you.

@WilliamDAssafMSFT so we meet again 😘

**Comment by WilliamDAssafMSFT** [comment] 2021-05-27 23:14
Hi @erikdarlingdata- So what you're suggesting for the change here is that Worker Thread category waits are ALSO not captured by sys.query_store_wait_stats, right? And you were able to confirm that the queries in your workload encountered `THREADPOOL` waits via `sys.dm_os_waiting_tasks`? Or were you seeing the waits via `sys.dm_exec_session_wait_stats`?



2 | Worker Thread | THREADPOOL
-- | -- | --

**Comment by erikdarlingdata** [comment] 2021-05-28 01:55
Hi there @WilliamDAssafMSFT!

Well that's the tricky thing. Threadpool waits can't show up in `sys.dm_exec_session_wait_stats` because when they happen, they don't even have a spid yet.

![image](https://user-images.githubusercontent.com/2136037/119917872-61ce1600-bf35-11eb-9a0c-1df3b7f8a35f.png)

They really only show up in `sys.dm_os_waiting_tasks` without a spid, and then in `sys.dm_os_wait_stats` after the fact. What I end up with is a whole bunch of stuff in `wait_stats` with threadpool waits, but nothing in `query_store_wait_stats` with them:

![image](https://user-images.githubusercontent.com/2136037/119918172-f5074b80-bf35-11eb-95d1-14ca670e3f81.png)

```
SELECT
    *
FROM sys.dm_os_wait_stats AS dows
WHERE dows.wait_type = 'THREADPOOL';

SELECT
    qsws.*
FROM StackOverflow2013.sys.query_store_wait_stats AS qsws
WHERE qsws.wait_category = 2;
```

I've ruled out obvious issues, like making sure that the workload is taking place in the database that I'm checking for the waits in, etc. 

Thanks!

**Comment by erikdarlingdata** [comment] 2021-05-28 17:12
I have recorded a supplemental video: https://www.youtube.com/watch?v=-9466N57rUE

**Comment by WilliamDAssafMSFT** [comment] 2021-06-01 14:43
Hi @erikdarlingdata, I've confirmed with the product team that this is the case. Worker thread wait category stats are not captured by the Query Store. We would need to just add the same asterisk * to the article for that row 2. 

Would you like to [create the PR](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-wait-stats-transact-sql) by clicking the Edit button on the article, add the asterisk, and get contributor credit for the article? Otherwise, I can handle the change.

Closing this ticket as we will resolve one way or another.

**Closed by WilliamDAssafMSFT** 2021-06-01 14:43 UTC
Labels: Pri3, assigned-to-author, doc-bug, sql/prod

**Comment by erikdarlingdata** [comment] 2021-06-01 16:52
@WilliamDAssafMSFT I have proposed a change!

**Comment by WilliamDAssafMSFT** [comment] 2021-06-07 21:55
@erikdarlingdata I don't see a PR for this. Link?

**Comment by erikdarlingdata** [comment] 2021-06-07 22:22
@WilliamDAssafMSFT you're right. not sure what happened there. i'll cook up a new one.

**Comment by erikdarlingdata** [comment] 2021-06-11 16:15
Sorry, I'm not going to be able to get to this. Can you please make the changes? Thanks.
