### ISSUE TITLE
COUNT() and COUNT_BIG() are considered possibly-NULL-returning by SQL Server, but their documentation doesn't mention this at all.

### ISSUE THREAD

**Issue by Jehoel** [MicrosoftDocs/sql-docs#7088] opened 2021-12-04 08:00 UTC
* Articles:
  * https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/count-transact-sql.md
  * https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/count-big-transact-sql.md

* Confusion in the community:
  *  https://stackoverflow.com/questions/46162230/why-does-sql-server-2005-think-count-is-nullable
      * The accepted-answer here is "just wrap it in `ISNULL`" but does not give any explanation beyond "computed columns _can_ be `NULL`-able".

---------------

Repro steps (run this in SSMS):

```
CREATE TABLE dbo.Table1 ( IntPK int NOT NULL IDENTITY(1,1) PRIMARY KEY );

GO

CREATE VIEW dbo.CountsView AS SELECT COUNT(*) AS CountStar FROM dbo.Table1;

GO

SELECT [COLUMN_NAME], [DATA_TYPE], [IS_NULLABLE] FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CountsView';
```

![image](https://user-images.githubusercontent.com/1693078/144702162-a815fb5b-e8ba-43d4-8fce-f6e87fc56db9.png)

Notice that the `CountStar` column is reported as `IS_NULLABLE = 'YES'`.

Similarly in SSMS's Object Explorer:

![image](https://user-images.githubusercontent.com/1693078/144702495-0eb1ecf5-4c5d-4c84-9088-eccd52ac0a19.png)

--------------

Based on [my reading of `COUNT()`'s documentation](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/count-transact-sql.md) I'm led to understand that when a query includes a trivial `COUNT(*)` expression the result should always be `int NOT NULL`.

* Given this behaviour has been consistent in every version of SQL Server I've used going back to SQL Server 7.0 would I be correct in assuming this is not a bug, but by-design?
* If it's by-design...
  *  _Why_ is `COUNT(*)` (when used alone)'s type always considered `int NULL` instead of `int NOT NULL`?
    * Currently, both the behaviour and any explanation for it are absent from the documentation.
  * Are there any circumstances where `COUNT(*)` (when used alone) _can_ return `NULL`?
    * If there are any, they aren't documented.
* If it's a bug...
  * Why has it persisted for 20+ years?

**Comment by WilliamAntonRohm** [comment] 2021-12-06 22:37
@Jehoel -- Dai, thank you for your thorough feedback.

@markingmyname -- Mark, please look into this issue.

**Comment by markingmyname** [comment] 2021-12-27 19:41
@Jehoel 

Thank you for bringing this to our attention.

May I ask you to reach out to the product team directly with feedback about this -  https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) - I'd appreciate it.

However, at the same time, I will discuss with the parties involved to find a more definitive answer to your question.

Thank you.

**Comment by Jehoel** [comment] 2021-12-27 21:54
@markingmyname Done: https://feedback.azure.com/d365community/idea/f0406d75-5f67-ec11-a819-0022484e8090

**Comment by jzabroski** [comment] 2021-12-27 22:47
@Jehoel Why Are we being asked to post this to some weird voting website?  I got the same feedback.  This seems like some new corporate policy Microsoft is enacting, and it feels like it is reversing the awesomeness that was the Satya Nadella era where Microsoft was more open and collaborative. CC @markingmyname

**Comment by martinsmith123456** [comment] 2022-01-03 14:51
I added an answer to your "Confusion in the community" link demonstrating that `COUNT()` can return `NULL` in the event that 

1. Number of rows counted is > 2147483647
2. Session options `SET ANSI_WARNINGS, ARITHABORT OFF;` are on.

**Comment by jzabroski** [comment] 2022-01-03 15:13
@martinsmith123456 It would be beneficial for this to be in the official documentation, not some lame voting website.  We used to submit stuff to a voting website (Microsoft Connect) years ago, and all the content and reproduction of issues we spent years creating got wiped off the face of the earth in a flash when Microsoft decided to use a different forum.  No thanks.  Feels like SAP to me.

**Comment by jzabroski** [comment] 2022-01-03 15:15
@MightyPen Is there any chance we can get an explanation for why we are being encouraged to submit documentation-related issues to this voting website?  @markingmyname isn't giving us the context behind such directions.

**Comment by martinsmith123456** [comment] 2022-01-03 18:35
> @martinsmith123456 It would be beneficial for this to be in the official documentation, not some lame voting website. We used to submit stuff to a voting website (Microsoft Connect) years ago, and all the content and reproduction of issues we spent years creating got wiped off the face of the earth in a flash when Microsoft decided to use a different forum. No thanks. Feels like SAP to me.

I've no idea why you are complaining to me about all this, I don't work for Microsoft and am not happy about the loss of all the useful info when Connect was closed either. 

But questions like "Are there any circumstances where COUNT(*) (when used alone) can return NULL?" should clearly be addressed in a Q and A site not in comments on the documentation.

The answer to that _is_ in the documentation though. See the documentation for `SET ARITHABORT`. 

It is also mentioned in the `CREATE TABLE` documentation in the context of computed columns

> The result of most expressions is considered nullable even if only nonnullable columns are present, because possible underflows or overflows also produce NULL results. 

A bit unfortunate that this information is buried there though as it also applies more generally to columns that are the result of expressions.

Personally I don't see the need to additionally spell this out in every possible function in the product that might overflow though, as there will be a lot of them.

**Comment by jzabroski** [comment] 2022-01-03 19:14
> I've no idea why you are complaining to me about all this

Sorry, I was not complaining to you. Apologies.  I reached out to MightyPen in the following reply to hopefully get an explanation as to what we should expect going forward regarding some product documentation.

> Personally I don't see the need to additionally spell this out in every possible function in the product that might overflow though, as there will be a lot of them.

That's fair - but we probably shouldn't also push it to some voting site. We should just close it as unnecessary and explain why.

**Comment by markingmyname** [comment] 2022-01-03 23:11
Thanks for your patience.

Let me take these specific questions (below) to the engineers and get back to all of you.

---------------------------------------
> Based on my reading of COUNT()'s documentation I'm led to understand that when a query includes a trivial COUNT(*) expression the result should always be int NOT NULL.
> 
> Given this behaviour has been consistent in every version of SQL Server I've used going back to SQL Server 7.0 would I be correct in assuming this is not a bug, but by-design?
> If it's by-design...
> Why is COUNT(*) (when used alone)'s type always considered int NULL instead of int NOT NULL?
> Currently, both the behaviour and any explanation for it are absent from the documentation.
> Are there any circumstances where COUNT(*) (when used alone) can return NULL?
> If there are any, they aren't documented.
> If it's a bug...
> Why has it persisted for 20+ years?
------------------------------------------

**Comment by uc-msft** [comment] 2022-01-04 21:37
Good discussion & I think some folks got side-tracked on the suggestion about submitting a feedback item. To the issue at hand, the reason why COUNT(*) is marked as NULLable is due to legacy SQL Server behavior. Try:

```
exec('
set ansi_warnings off;

select count(*)
from sys.all_objects as o1, sys.all_objects as o2, sys.all_objects as o3;
');

```

As per ANSI SQL standard, COUNT(*) returns the cardinality of the table or query when used without grouping. So, it can only return a numeric value or error in case of overflow. This is the default behavior in SQL Server but since the legacy setting makes it possible for the query containing COUNT(*) to return a NULLable or non-NULLable column for the COUNT(*) expression. Compile time decision only looks at the expression or schema to perform type derivation. Hence, we can have to mark COUNT(*) as NULLable. Even the trivial case below:

`select COUNT(*);`

We can only mark COUNT(*) as NULLable in many cases if we remove ANSI_WARNINGS OFF behavior from SQL Server which will never happen for backward compatibility reasons. For now, the only guaranteed way to make an expression non-NULLable is to wrap the expression or column reference in a ISNULL call. The ANSI_WARNINGS topic does call out the NULL result in case of overflow with the setting OFF. But I guess we could make it more explicit in the aggregate function topic too or cross-reference it. Hope this helps.

Below is quote from ANSI_WARNINGS topic:

> When set to ON, the divide-by-zero and arithmetic overflow errors cause the statement to be rolled back and an error message is generated. When set to OFF, the divide-by-zero and arithmetic overflow errors cause null values to be returned. 

The standard rules are below for reference:

> Syntax Rules
> 
> 4) If COUNT is specified,then the declared type of the result is an implementation-defined exact numeric
> type with scale 0 (zero).
> 5) If COUNT(*) specified and is contained in <row pattern measures> or <row pattern definition search
> condition>, then let URPV be the universal row pattern variable. AF is equivalent to
> COUNT (URPV.*)
> 
> General Rules
> 
> 3) If, during the computation of the result of AF, an intermediate result is not representable in the
> declared type of the site that contains that intermediate result, then
> Case:
> a) If the most specific type of the result of AF is an interval type, then an exception condition is
> raised: data exception — interval value out of range (2200P).
> b) If the most specific type of the result of AF is a multiset type, then an exception condition is
> raised: data exception — multiset value overflow (2200Q).
> c) If the most specific type of the result of AF is an array type, then an exception condition is raised:
> data exception — array data, right truncation (2202F).
> d) If the most specific type of the result of AF is a character string type, then an exception condition
> is raised: data exception — string data, right truncation (22001).
> e) Otherwise, an exception condition is raised: data exception—numeric value out of range (22003).
> 
> 5) If COUNT(*) is specified, then the result is the cardinality of T1.

**Comment by markingmyname** [comment] 2022-01-05 22:44
Thank you, @uc-msft, for this reply.

**Comment by Jehoel** [comment] 2022-01-06 07:19
@uc-msft 

The problem with using `ISNULL` is that it sweeps some error conditions under-the-rug: _if_ there is an error condition such that `COUNT(*)` does return `NULL`, then `ISNULL` will simply hide the problem without bubbling it up.

> We can only mark `COUNT(*)` as non-`NULL`able in many cases if we remove `ANSI_WARNINGS OFF` behavior from SQL Server **which will never happen for backward compatibility reasons**

If the behaviour is part of a future Compatibility Level, couldn't it be done then? At some point though, engineers can't let bad decisions from the distant past continue to compromise a modern, well-maintained product - and isn't that the point of Compatibility Levels?

For example, in a future hypothetical Compatibility Level 160 or 170 where `ANSI_WARNINGS ON` cannot be disabled and all other strict ISO SQL features are enabled, _then_ will `COUNT()` expressions be typed as `NOT NULL`?

**Comment by uc-msft** [comment] 2022-01-06 19:55
Yes, if we outlaw ANSI_WARNINGS, ARITHABORT, ARITHGINORE  & other related settings in a new release of SQL Server then we can change the COUNT(*) expression to indicate NOT NULL under various circumstances. But remember that settings like ARITHABORT affects not just COUNT(*) but other expressions and functions too. This is a much bigger undertaking. I had an idea many years back about introducing a stricter T-SQL compiler level that will disallow such settings (like the ANSI options in C++ compilers) or other behavior. But we need to prioritize this change with other feature requests. Hopefully, we can get there in a future release. Many of the T-SQL syntax is stuck from the Sybase days unfortunately.

Also, ANSI_WARNINGS has been set to ON by default by drivers for more than a decade now. The issue is that many SET options are execution time options that can be inherited from a connection context or database or modified. by the application.  Unlike QUOTED_IDENTIFIER which is persisted with the modules for example, this particular SET option is known only at execution time. We don't know if there are old apps with legacy code or settings connecting to SQL Server and running queries. I have been on customer calls where they ask about migrating apps for which there is no source code and changes can't be made. So, backward compatibility is a big deal for SQL Server and unfortunately this introduces some seams in the surface area.

**Comment by markingmyname** [comment] 2022-03-23 16:17
As per @uc-msft response, we will move forward to close this.

**Comment by markingmyname** [comment] 2022-03-23 16:17
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.

**Closed by markingmyname** 2022-03-23 16:17 UTC
Labels: sql/prod, docs-experience, assigned-to-author, Pri3

**Comment by Jehoel** [comment] 2022-09-10 13:32
@uc-msft So I tried to reproduce the `COUNT(*) returns NULL` behaviour in SQL Server 2022 RC0 (Compatibility Level 160) and I can't seem to.

I used this script to insert ~4bn rows into a table:

```sql
CREATE TABLE dbo.FourBillionRows (
    "RowNumber" bigint NOT NULL PRIMARY KEY,
    SomeText    varchar(50) NOT NULL DEFAULT('')
);
GO

-- Running this from 1 to 65536 iterations (to generate 2^32 rows: ~4bn rows) took 4 hours, 3 minutes on my machine.
DECLARE @n bigint = 1;
DECLARE @msg varchar(50);
DECLARE @nFloat float;
DECLARE @perc float;

WHILE ( @n > 0 AND @n <= 65536 )
BEGIN

	WITH
	t0(i) AS (SELECT 0 UNION ALL SELECT 0), -- 2
	t1(i) AS (SELECT 0 FROM t0 a, t0 b), -- 4
	t2(i) AS (SELECT 0 FROM t1 a, t1 b), -- 16
	t3(i) AS (SELECT 0 FROM t2 a, t2 b), -- 256
	t4(i) AS (SELECT 0 FROM t3 a, t3 b), -- 65536
	--t5(i) AS (SELECT 0 FROM t4 a, t4 b), -- 4bn

	n(i) AS (SELECT ROW_NUMBER() OVER(ORDER BY (SELECT 0)) FROM t4)
	INSERT INTO dbo.FourBillionRows ( SomeText )
	SELECT '' FROM n;

	--

	SET @perc = STR( ( 100E0 * CONVERT( float, @n ) ) / 65535E0, 10, 2 );
	SET @msg = CONCAT( CONVERT( varchar(10), @n ), '/65536 - ', @perc );
	RAISERROR ( @msg, 0, 1 ) WITH NOWAIT;

	SET @n = @n + 1;

END;
GO
```

After that completed I tried various `COUNT` queries:

| Query | Expected Result | Actual Result |
|--------|--------- |-------------|
| `SELECT COUNT_BIG(*) FROM dbo.FourBillionRows;` | `4295032833` | `4295032833` |
| `SET ANSI_WARNINGS ON; SELECT COUNT(*) FROM dbo.FourBillionRows;` | > Msg 8115, Level 16, State 2, Line 1    |  > Msg 8115, Level 16, State 2, Line 1  |
| `SET ANSI_WARNINGS OFF; SELECT COUNT(*) FROM dbo.FourBillionRows;` | `NULL`  |  > Msg 8115, Level 16, State 2, Line 1  |

...is this new behaviour in SQL Server 2022, or is this a bug, or something else?
