### ISSUE TITLE
Managed Backup not supported on linux, but isn't listed in the Managed Backup documentation

### ISSUE THREAD

**Issue by cyberprune** [MicrosoftDocs/sql-docs#9121] opened 2023-06-30 08:23 UTC
One of the limitations of Managed Backup is it isn't currently supported on Linux. This is documented on https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-editions-and-components-2022?view=sql-server-ver16#unsupported-features-and-services but not anywhere in the Managed Backup documentation.

When trying to use and enable this functionality in linux, it just doesn't do anything, but comes back as Command completed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e601980-b1c6-efcc-337f-70a052b926ec
* Version Independent ID: a39e430c-141b-bd0b-1b91-4814f76e801c
* Content: [SQL Server managed backup to Microsoft Azure - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-managed-backup-to-microsoft-azure?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/sql-server-managed-backup-to-microsoft-azure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/sql-server-managed-backup-to-microsoft-azure.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment] 2023-07-05 07:45
@cyberprune -- Daniel, thank you for your clear feedback.

@MashaMSFT -- Masha, please look into this issue.

**Comment by MashaMSFT** [comment] 2023-08-22 15:01
Hi @cyberprune , thanks again for bringing this to our attention! I just realized this issue is a duplicate of https://github.com/MicrosoftDocs/sql-docs/pull/9122 :) Since we updated the applies to line to indicate this article is intended for Windows only, I'll go ahead and close out this Git Issue as well but please feel free to comment should you need anything further.

Thanks again for helping improve our documentation and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close

**Closed by MashaMSFT** 2023-08-22 15:01 UTC
Labels: doc-bug, assigned-to-author, Pri2, sql/svc, backup-restore/subsvc
