### ISSUE TITLE
WMI namespace incorrect on "Working with the WMI Provider for Configuration Management"

### ISSUE THREAD

**Issue by rrg92** [MicrosoftDocs/sql-docs#1817] opened 2019-03-24 22:47 UTC
On [file working-with-the-wmi-provider-for-configuration-management.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management.md#specifying-a-connection-string) the wmi namespace seems  incorrect...

Doing a little powershell script to return all wmi namespaces, and filtering just which contains "SqlServer" on name, we have following in a computer with SQL Server 2016 and SQL Server 2014 installed:

![image](https://user-images.githubusercontent.com/16887793/54887053-69816400-4e6d-11e9-9329-3a7b3cc7cd4e.png)

The "ComputerManagementXX" dont have childs for the instance...

Just with the "ServerEvents", we have a child with instance name...

**Comment by MightyPen** [comment] 2019-03-25 00:50
@rrg92 Hello, I half understand what your core point is, but I need to be more clearly certain.

_Request:_ Can you please enter another comment to directly state what the problem is that may need fixing? In the comment, please @ notify me MightyPen.

&nbsp;

In many articles that show directory paths, the pathing on our test computer may well differ from the pathing on a customer's computer, due to any number of factors.  Often the articles are giving a plausible example of the pathing to expect, and not necessarily the exact pathing that all computers will have.  I am unsure whether this is part of what this Issue 1817 is directly concerned about?

Thank you.

---

Here is the https URL link to the article in question:
- [https://docs.microsoft.com/sql/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management](https://docs.microsoft.com/sql/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management)

Here is the GitHub branch=master link to the same article:
- [https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/relational-databases/wmi-provider-configuration/working-with-the-wmi-provider-for-configuration-management.md)

**Comment by rrg92** [comment] 2019-03-25 15:36
Hellow @MightyPen!

I will try to be more clear and precise:

I've highlighted the parts needs to be fixed and attached a [modified version](https://github.com/MicrosoftDocs/sql-docs/files/3004141/MicrosoftDocChange_Wmi.md.txt) of this file with proposed changes.

![image](https://user-images.githubusercontent.com/16887793/54927237-89a63700-4ef0-11e9-9a34-17c0ad2f3544.png)

The path mentioned on documentation is not a directory path, but a **WMI namespace**. These namespaces have same structure of a directory path. But some parts dont exists:

* In some tools, namespaces dont start with "\\\\.". It must start with "root\".  This is case of powershell. I guess this must be clear to the reader, because most of SQL Server users with query WMI using powershell:

_When using \\. at start of namespace path, powershell code result in error: INVALID WMI NAMESPACE!_
![image](https://user-images.githubusercontent.com/16887793/54927435-edc8fb00-4ef0-11e9-9862-e78949ee3f83.png)

_Without \\.\ part, it runs successfully_
![image](https://user-images.githubusercontent.com/16887793/54927585-2c5eb580-4ef1-11e9-82d4-f43e1dfb0b3c.png)


* The ComputerManagement12 part of example path can change according SQL Server version installed.  For example, if the computer have installed SQL Server 2016 and SQL Server 2014 with exists following namespaces. I guess documentation must inform this part to users correctly build path according theirs needs:
```
root\Microsoft\SqlServer\ComputerManagement13
root\Microsoft\SqlServer\ComputerManagement12
```
The format is:  

```
root\Microsoft\SqlServer\ComputerManagementXX  
```

where `XX` is the major version of SQL Server tool installed. For example, the major version for SQL Server 2016 is 13, and, because this, there are a namespace `root\Microsoft\SqlServer\ComputerManagement13`.  To keep more precise, you can add following sample powershell code to user get all available namespaces on machine:

```posh
Get-WmiObject -ns 'root\Microsoft\SqlServer' __NAMESPACE | ? { $_.name -match 'ComputerManagement' } | select name
```

Here, a sample output on a computer with just SQL Server 2016 installed:

![image](https://user-images.githubusercontent.com/16887793/54928143-3af99c80-4ef2-11e9-96f6-3ec2ac4b00a0.png)





* The part "\instance" dont exists for namespace `root\Microsoft\ComputerManagementXX` (where XX is version number) in any computer with SQL Server installation.  Current doc mentions the use of "\instance" where instance is the instance name. This part of path dont exists for namespace `root\Microsoft\ComputerManagementXX`. It exists just for namespace root\Microsoft\SqlServer\ServerEvents\`instance_name`

**Comment by MightyPen** [comment] 2019-03-28 08:27
@rrg92 Thanks much for this excellent explanation, and for the referenced commit that shows the specific improvements that you recommend.
I will take a close look at the info you have provided.

**Comment by MightyPen** [comment] 2019-04-12 20:18
Fixed.
Fix should be on live Docs by or before afternoon of Monday April/15.
Private PR =
https://github.com/MicrosoftDocs/sql-docs-pr/pull/9838

@rrg92 Thanks again for your exceptionally good inputs on this problem.  :-) 
I am now Closing this PR 1817.

**Closed by MightyPen** 2019-04-12 20:18 UTC
Labels: Issue-Status-20-Author-will-triage

**Comment by rrg92** [comment] 2019-04-13 23:53
Nice @MightyPen !! I noted that page already updated!!

But, my profile do not appears on "contributors" section, like this article informs. Why?

![image](https://user-images.githubusercontent.com/16887793/56086443-fd6f9b80-5e2d-11e9-99ff-31ae24f24eeb.png)

**Comment by MightyPen** [comment] 2019-04-14 00:21
@rrg92 The 'Contributors' photo circles are taken from Pull Requests that are created when the customer clicks the "Edit"-pencil icon at the top-right of the article - and then if the PR is accepted and merged.
These PRs are created in repo 'MicrosoftDocs/sql-docs'.

One hitch is that we often want to slightly modify the customer's PR before merging it.  Some Writers feel that modification activity is tricky, or they rarely do it and cannot easily remember exactly how it should be done.
Or is the size of the modifications are relatively large, it becomes easier for the Writer to create a new "private repo" PR (in 'sql-docs-pr'), which then does not lead to the photo circle that the public PR would have.
Or sometimes the customer will make a PR that is kinda incomplete or a bit sloppy or inexact.  So again it could be easier for the Writer to create a fresh new private PR.  (We are always swamped with more work than we can ever complete, so speed and ease are major factors.)
No system is perfect.

As I recall, this Issue 1817 referred to a Commit that was something other than a PR created by you by your having clicked the "Edit"-pencil icon.

Thanks.
. .

**Comment by rrg92** [comment] 2019-04-14 00:54
All right @MightyPen !! 
I would like to get my profile appears on official docs!! =)

But, I perfectly understood all you say!
Thanks for explanation!
