### ISSUE TITLE
Transact-SQL snapshot backups: Please share the .cmd script

### ISSUE THREAD

**Issue by glmios** [MicrosoftDocs/sql-docs#9539] opened 2023-12-07 17:56 UTC
[Enter feedback here]

Thanks for the demo. But the critical part was step2 initializing snapshot backup.  I wonder if you could share with us how this implemented in Azure blob with the .cmd script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Version Independent ID: 8840ba86-332c-33fc-509b-9e7e08671c7a
* Content: [Create a Transact-SQL snapshot backup - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup?view=sql-server-ver16#workflow)
* Content Source: [docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/create-a-transact-sql-snapshot-backup.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @perrysk-msft
* Microsoft Alias: **peskount**

**Comment by rwestMSFT** [comment] 2024-01-08 21:26
@glmios I'm closing this issue, as we are tracking it internally.

AB#70883

**Closed by rwestMSFT** 2024-01-08 21:26 UTC
Labels: doc-bug, assigned-to-author, Pri2, sql/svc, backup-restore/subsvc

**Comment by rwestMSFT** [comment] 2024-01-15 17:39
Duplicate of #9235.

**Comment by rwestMSFT** [comment] 2024-01-16 17:44
@glmios This is the response from the product group for now.

> Thank you all for your interest in T-SQL Snapshot Backup!
> 
> With T-SQL snapshot backup in SQL Server 2022 we provide commands to freeze and thaw the database and not commands to perform the actual snapshot. Taking the actual snapshot of the disk still falls under the responsibility of the customer. Customers can use 3rd party tools of their choice or implement their own solution to take the snapshot of the disk.
> 
> In the video, we are using an internal SQL trace flag that allows copying the .mdf and .ldf files to another disk (simulating a disk snapshot backup) while SQL is still running. The TF is used only for demo purposes, and we are not exposing that TF externally.
> 
> An alternative to testing T-SQL Snapshot Backup is by using an Azure VM and this PS script:
https://github.com/microsoft/sql-server-samples/blob/master/samples/features/t-sql-snapshot-backup/snapshot-backup-restore-azurevm-single-db.ps1 might be the best option.

Given that what you likely saw was the use of an undocumented trace flag, this is as far as I can take the resolution of this issue. I appreciate your patience while I got the information, even if it isn't what you wanted to hear.
