### ISSUE TITLE
Footnote rather than being Squared

### ISSUE THREAD

**Issue by airtank20** [MicrosoftDocs/sql-docs#6898] opened 2021-10-01 21:14 UTC
The notation around the mathematical formula for Workers per CPU is fairly close to being "squared" rather than to indicate it being a footnote that needs to be noticed.  I'm not sure the best way to identify this being a foot note rather than a mathematical operation but it tripped me up for about 10 minutes.  =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90f494da-8888-13e8-0fcc-187242579039
* Version Independent ID: 01bd6647-777e-8c62-f865-6831469b4924
* Content: [Configure the max worker threads Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan
![2021-10-01_17-01-33](https://user-images.githubusercontent.com/8907695/135686787-29db9037-e18f-4c5e-90dc-20577fc9e083.png)
**

**Comment by WilliamAntonRohm** [comment] 2021-10-01 21:33
@airtank20 -- John, thank you for your feedback.  I am updating this article to clarify "note 2" rather than an exponent.

Duplicate of #6734

**Closed** 2021-10-01 21:55 UTC
Labels: sql/prod, configuration/tech, doc-enhancement, cba
