### ISSUE TITLE
Requirements conflict between this page and the download page for SQL 2016 Express

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/sql-docs#2961] opened 2019-09-12 00:37 UTC
The download page ([Download Microsoft® SQL Server® 2016 Service Pack 2 Express](https://www.microsoft.com/en-us/download/details.aspx?id=56840&WT.mc_id=rss_alldownloads_all&wa=wsignin1.0&lc=1033)) says SQL 2016 Express is supported on Windows Server 2008 R2, but this page does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b411a1-f282-d77e-a497-83d08a963549
* Version Independent ID: f896a7f4-f08a-4b67-6d98-c14a0e1a969e
* Content: [Hardware and Software Requirements for Installing SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/install/hardware-and-software-requirements-for-installing-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment] 2019-10-07 17:10
Hi @mdell-seradex , just wanted to let you know I'm still looking into updating this :)

Thanks!
Masha from the SQL Docs team

**Comment by tjmk40040** [comment] 2019-10-11 06:34
Is this just a matter of updating the document that SQL 2016 Standard is supported on Server 2008 R2, or is that not confirmed yet?

**Comment by mdell-seradex** [comment] 2019-10-11 14:14
I have done some further testing recently and it appears that the latest available does not support Seradex 2008 R2.  It seems like the download page is wrong.

**Comment by MashaMSFT** [comment] 2019-10-14 18:51
@tjmk40040 The docs page is correct - SQL Server 2016 is not supported on Windows Server 2008 R2. We are changing the requirements on the download page. 
@mdell-seradex , thank you for testing this for us!

**Comment by MashaMSFT** [comment] 2019-12-16 17:05
@tmichael-ms , I am assigning this Git Issue to you. Would you mind updating it once the download page has been updated appropriately? 

Thank you!
Masha from the SQL Docs team

**Comment by yogeshsn08** [comment] 2019-12-19 16:51
Dear MashaMSFT, I see that Windows Server 2008 R2 conflict issue was reported 3 months ago and still it is not corrected. Kindly note that this will have a major production impact in customer sites because of the false information. Hence, please notify your documentation team to update the info in priority.

**Comment by rothja** [comment] 2020-03-14 13:07
@yogeshsn08 @mdell-seradex I sincerely apologize for the delay in responding to this. I will escalate this request internally and track it. #assign:rothja

**Comment by tmichael-ms** [comment] 2020-03-14 16:36
"Windows Server 2008 R2" was removed from SQL Server 2016 SP2 Express DLC page OS listing.  Update published on 1/10/2020.

**Comment by rothja** [comment] 2020-03-16 13:02
@mdell-seradex  @yogeshsn08 We removed the "Windows Server 2008 R2" but left "Windows Server 2008 R2 SP1". I'm going to close this issue now, but please comment on this thread if you have any questions. Thank you!

**Closed by rothja** 2020-03-16 13:02 UTC
Labels: Pri1, assigned-to-author, doc-bug, install/tech, sql/prod
