### ISSUE TITLE
What supported VERSION of SQL?!?

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/sql-docs#4476] opened 2020-04-03 16:21 UTC
Saying that it is supported by SQL Server is like saying that the bumper for a pickup truck "fits F-150".
Will it work on SQL 2000? Not likely.
2005? Probably not there either.
2008? 2008 R2? Nope
2012? 2014? Sorry.
2016? Ooh, now there's a nice modern version of the product. And.......nope, Not RTM. SP1?
2017? Maybe. I don't know.

Please consider putting this info at the TOP of the article in the Applies To section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ad0688-dc8f-4141-5347-434101794dbc
* Version Independent ID: 0e45b49f-32ca-3733-a46f-9f5f93419b5d
* Content: [DBCC CLONEDATABASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-clonedatabase-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/database-console-commands/dbcc-clonedatabase-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/database-console-commands/dbcc-clonedatabase-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @bluefooted
* Microsoft Alias: **pamela**

**Comment by bluefooted** [comment] 2020-04-03 16:54
Hi @ToddChitt ! It actually does work in 2014, but there was a strange issue with one version of Management Studio where it wasn't parsing the command correctly. We never sorted out that issue because I was the only one who could reproduce it, but perhaps that is what you are facing? Try upgrading SSMS and see if that helps. Regarding the versioning, we know this is an issue across all our documentation, but the current documentation is applicable to 2016 and later unless otherwise specified. If you are looking for documentation for older versions of SQL Server, there is a dropdown on the upper left hand corner above the TOC that will allow you to choose the version. If the document you are looking at doesn't exist for the version you choose, you'll see that you are redirected to the current version. In this case, we didn't document DBCC CLONEDATABASE until 2017 which is why no versioning other than special cases is listed.

**Comment by ToddChitt** [comment] 2020-04-03 17:02
Hello Pam, and thanks for the quick response! I am using a SQL Server 2016 Standard (does that matter?) Version 2016 (RTM-GDR) ( KB4019088) - 13.0.1742.0 (x64) Jul 5 2017SSMS is the latest available download, v18.4, or 15.0.18206.0 Curious to know a work around. I *really* want to get this going.  Thanks. -Todd C From: Pam LahoudSent: Friday, April 3, 2020 12:54 PMTo: MicrosoftDocs/sql-docsCc: ToddChitt; MentionSubject: Re: [MicrosoftDocs/sql-docs] What supported VERSION of SQL?!? (#4476) Hi @ToddChitt ! It actually does work in 2014, but there was a strange issue with one version of Management Studio where it wasn't parsing the command correctly. We never sorted out that issue because I was the only one who could reproduce it, but perhaps that is what you are facing? Try upgrading SSMS and see if that helps. Regarding the versioning, we know this is an issue across all our documentation, but the current documentation is applicable to 2016 and later unless otherwise specified. If you are looking for documentation for older versions of SQL Server, there is a dropdown on the upper left hand corner above the TOC that will allow you to choose the version. If the document you are looking at doesn't exist for the version you choose, you'll see that you are redirected to the current version. In this case, we didn't document DBCC CLONEDATABASE until 2017 which is why no versioning other than special cases is listed.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bluefooted** [comment] 2020-04-03 17:43
Was the server upgraded from SQL Server 2008? There was a hotfix released in SQL Server 2016 SP1 CU1 for this. https://support.microsoft.com/kb/3212214

**Comment by ToddChitt** [comment] 2020-04-03 17:52
I don’t think it’s on SP1. I think it’s RTM.  Looks like SP1 is needed? Which is frustrating. They released it for 2014 in a service pack, but couldn’t get it in RTM for the next version? -Todd C From: Pam LahoudSent: Friday, April 3, 2020 1:43 PMTo: MicrosoftDocs/sql-docsCc: ToddChitt; MentionSubject: Re: [MicrosoftDocs/sql-docs] What supported VERSION of SQL?!? (#4476) Was the server upgraded from SQL Server 2008? There was a hotfix released in SQL Server 2016 SP1 CU1 for this. https://support.microsoft.com/kb/3212214—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bluefooted** [comment] 2020-07-28 16:41
#please-close

**Closed by bluefooted** 2020-07-28 16:41 UTC
Labels: Pri2, doc-bug, sql/prod, t-sql/tech
