### ISSUE TITLE
docker: invalid reference frame 

### ISSUE THREAD

**Issue by Hyypeer** [MicrosoftDocs/sql-docs#2608] opened 2019-07-28 08:31 UTC
When running the command:

sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=&lt;YourStrong!Passw0rd&gt;" \
   -p 1433:1433 --name sql1 \
   -d mcr.microsoft.com/mssql/server:2017-latest

I get the error: invalid  reference format do anyone know how til solve this ? running it on an mac command prompt 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server Linux containers on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by rothja** [comment] 2019-08-05 20:19
@Hyypeer Thank you for reaching out to us with this question. We're looking into it to make sure that the instructions in the article are correct. Thank you for your patience.

**Comment by msebolt** [comment] 2019-08-05 21:15
@Hyypeer Can you try the above command without new-lines and a weak password (no special characters)?

```
sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<weakpassword>" -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest
```

The error suggests something wrong with the syntax.

**Comment by msebolt** [comment] 2019-08-06 22:30
New lines were not of issue, for whatever reason it was the `!` in the password.  

Document has been updated.

**Comment by ivanlopezmolina** [comment] 2019-09-06 02:31
I was having issues with the same ! on Mac but the problem was the double quotation (") I replaced them by single and worked.

**Comment by msebolt** [comment] 2019-09-06 17:35
Also noticed `!` in password needs to be replaced throughout.

**Comment by msebolt** [comment] 2019-09-10 17:01
@ivanlopezmolina Can you reference a command in particular?  The double quotes seem to be working for me on Mac.

**Comment by rothja** [comment] 2019-09-17 16:55
@ivanlopezmolina Thanks, again, for reaching out. As @msebolt can not reproduce, we'll close this for issue for now. However, if you can provide more information that would help us recreated the problem, we might be able to figure out what the caveats are to put in the documentation to address the issue you're seeing. Thank you!!

**Closed by rothja** 2019-09-17 16:55 UTC
Labels: Pri1, assigned-to-author, linux/tech, sql/prod, support-request
