### ISSUE TITLE
SA_PASSWORD or not?

### ISSUE THREAD

**Issue by antman2** [MicrosoftDocs/sql-docs#8107] opened 2022-09-22 23:06 UTC
This page, https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-containers-ad-auth-adutil-tutorial, has the note against `docker run` usage:

>  Important
> 
> The SA_PASSWORD environment variable is deprecated. Please use MSSQL_SA_PASSWORD instead.

Yet the Dockerhub page, https://hub.docker.com/_/microsoft-mssql-server, makes no mention whatsoever of `MSSQL_SA_PASSWORD`, only demonstrating usage of `SA_PASSWORD`. Which documentation is correct? Which documentation needs to be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff5e98ff-22b5-4b3c-61f4-d08d9028fe8d
* Version Independent ID: 17b9b0a5-e97a-eb00-9432-41ac45e6a330
* Content: [Configure Active Directory authentication with SQL Server on Linux-based containers using adutil - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-containers-ad-auth-adutil-tutorial?view=sql-server-ver16)
* Content Source: [docs/linux/sql-server-linux-containers-ad-auth-adutil-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-containers-ad-auth-adutil-tutorial.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment] 2022-09-22 23:21
@antman2 -- Anthony, thank you for your feedback.  Please see this comment:  https://github.com/MicrosoftDocs/sql-docs/issues/7869#issuecomment-1199954845.  Both pages are correct.

Duplicate of #7869.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.


cc @amvin87 for awareness

**Closed by WilliamAntonRohm** 2022-09-22 23:21 UTC
Labels: duplicate, sql/prod, linux/tech, cba, Pri2
