### ISSUE TITLE
Update to reflect case 117020315270200 findings

### ISSUE THREAD

**Issue by martinbherbener** [MicrosoftDocs/sql-docs#5235] opened 2020-07-23 12:52 UTC
Hi,

It would be helpful to include the information I obtained through  MS Support Case 117020315270200

There are two issues uncovered. First SQL 2016 SSM has a product issue that prevents to use GUI to configure replication to non-sql server subscribers. Secondly SQL 2016 doesn’t have proper meta data mapped to oracle 12 C.
Resolution
1.	Use TSQL Script to configure Oracle subscription 
2.	For 12c, extra steps are needed. Below are the steps

Note that these steps assume that you create a table on Oracle yourself without applying snapshot.

1. connect to SQL Server using dedicated admin connection (DAC)
use msdb
go
exec sys.sp_MSrepl_ORAdatatypes 'Oracle', '12'
go
exec sys.sp_MSrepl_MSSQL_ORA_datatypemappings @source_dbms = N'MSSQLSERVER', @destination_dbms = N'ORACLE', @destination_version = '12'

2. on oracle server
a. drop table MSREPL7;
b. create your own table (make sure exact name and schema)

3. create a simple transaction replication publication
4. change publication properties ("subscription options") "Allow no-SQL Server subscribors" to be true
4. use the following script to create subscription and agent job. You need to change oracle instance name, password and publication name

use [dbpub]

exec sp_addsubscription @publication = N'pub_t2', @subscriber = N'ORCLJACKLI', @destination_db = N'(default destination)', @subscription_type = N'Push', @sync_type = N'replication support only', @article = N'all', @update_mode = N'read only', @subscriber_type = 3
exec sp_addpushsubscription_agent @publication = N'pub_t2', @subscriber = N'ORCLJACKLI', @subscriber_db = N'(default destination)', @job_login = null, @job_password = null, @subscriber_security_mode = 0, @subscriber_login = N'SCOTT', @subscriber_password = null, @subscriber_provider = N'OraOLEDB.Oracle', @subscriber_datasrc = N'orcljackli', @subscriber_provider_string = N'orcljackli', @frequency_type = 64, @frequency_interval = 1, @frequency_relative_interval = 1, @frequency_recurrence_factor = 0, @frequency_subday = 4, @frequency_subday_interval = 5, @active_start_time_of_day = 0, @active_end_time_of_day = 235959, @active_start_date = 0, @active_end_date = 0, @dts_package_location = N'Distributor'

5. add some rows in the published table
6. verify in oracle after a few minutes of wait

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0918cd8a-85fe-5106-6b7e-27fbe6c4ee00
* Version Independent ID: c7d665a0-f57f-518c-40ba-e70b5f81933c
* Content: [Non-SQL Server Subscribers - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/non-sql-server-subscribers?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/non-sql/non-sql-server-subscribers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment] 2020-07-23 21:22
Duplicate of #5236

**Closed by WilliamAntonRohm** 2020-07-23 21:22 UTC
Labels: Pri2, cba, duplicate, replication/tech, sql/prod
