### ISSUE TITLE
Arguments section of bcp article isn't rendered to html correctly

### ISSUE THREAD

**Issue by NullEntity** [MicrosoftDocs/sql-docs#1522] opened 2019-01-12 05:08 UTC
Viewing the [live bcp Utility page](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-2017) shows raw markdown below the arguments table. The preview in Github renders it properly so I think something with the table syntax is confusing the markdown renderer that the live site uses.

**Comment by MightyPen** [comment] 2019-01-14 23:36
@NullEntity Bryce, thank you very much for notifying us of this visual display mess.

Today, private PR 8758 fixes this Issue 1522.
The problem is that our upgraded markdown conversion engine sometimes demands blank lines after our `##` headers.    I merely added some blank lines, and the test rebuild no longer shows raw markdown.

(docs/tools/bcp-utility.md)

I am now Closing this completed Issue.

**Closed by MightyPen** 2019-01-14 23:36 UTC
Labels: Issue-Status-3-Will-fix

**Comment by dalee-bis** [comment] 2019-01-15 10:50
This still seems to be an issue. Is this just awaiting release?

**Comment by MightyPen** [comment] 2019-01-26 19:43
DevO = https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1429249
