### ISSUE TITLE
Error while creating External File Format & External Table in SQL Server  2019

### ISSUE THREAD

**Issue by nkumar230** [MicrosoftDocs/sql-docs#3393] opened 2019-10-25 12:57 UTC
Hi Team

Referring multiple issues registered in Forums I just tested myself.
Links - https://social.technet.microsoft.com/Forums/en-US/a376e1cf-aa73-4b56-a86c-825bb1e7ebb6/sql-server-polybase?forum=sqldatabaseengine

Microsoft SQL Server 2019 (RC1) - 15.0.1900.25 (X64)   Aug 16 2019 14:20:53   Copyright (C) 2019 Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows 10 Pro 10.0 &lt;X64&gt; (Build 18362: ) 

In this version I am trying to create a External File Format while I am getting the below error.

--Query - Ran
CREATE EXTERNAL FILE FORMAT [csvformat]
WITH ( 
    FORMAT_TYPE = DELIMITEDTEXT, 
    FORMAT_OPTIONS ( 
        FIELD_TERMINATOR = ','
    ) 
);
--Output
Msg 102, Level 15, State 1, Line 1
Incorrect syntax near 'EXTERNAL'.

By the way I have installed Poly base features too. Please help understand the possible root cause for this issue.

Thanks 
Naveen Thummalapenta 
Microsoft Certified Solutions Expert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72fb8035-306f-ffc1-4159-141ae7b68c77
* Version Independent ID: a202acea-442c-140f-6f39-3f851238a740
* Content: [CREATE EXTERNAL FILE FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-file-format-transact-sql?view=sql-server-ver15#general-remarks)
* Content Source: [docs/t-sql/statements/create-external-file-format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-file-format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment] 2019-10-28 17:39
@nkumar230 Thank you for the feedback.

Unfortunately this sounds like more of an issue for the product team then documentation.

Please start a thread in the [SQL Server forum](https://social.msdn.microsoft.com/Forums/home?forum=sqldocumentation,sqldatabaseengine) and link back to reference this issue.

**Comment by msebolt** [comment] 2019-10-28 18:49
@nkumar230  Just to confirm, running `SELECT SERVERPROPERTY ('IsPolyBaseInstalled') AS IsPolyBaseInstalled;` returns `1`?

I can assign this to the author for review of the example.

In the meantime, please use the [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) to start a thread for the product team to assess with a link back to this issue.

**Comment by MikeRayMSFT** [comment] 2019-11-21 22:47
@nkumar230 - I have not been able to reproduce the issue. I'm going to close it at this time. 

If you can reproduce the issue on the current version of SQL Server 2019, please reopen this issue, or create a new issue.

**Comment by rgosling** [comment] 2019-12-16 15:18
I'm seeing the same thing and yes - it's reporting that Polybase is installed.

**Comment by rothja** [comment] 2019-12-16 21:52
@rgosling I am sorry you're having problems. It looks like @MikeRayMSFT was unable to reproduce the problem, so it is possible that there is some other reason why PolyBase is not working on your configuration. The best thing to do in this case might be to reach out to Microsoft Support to see if they can troubleshoot. I'm sorrry, but we're not sure what the problem might be. However, if more information comes in where we know what to add to the article, we will update the article at that time. Thank you!

**Comment by gurvinderkandhola** [comment] 2020-01-04 00:31
I am also having the same issue, while creating the External File Format on SQL server 2019 , evaluation version.
------------------------------------- 
SELECT SERVERPROPERTY ('IsPolybaseInstalled') AS IsPolybaseInstalled;
GO
Returns 1 
-------------------------------------
CREATE EXTERNAL FILE FORMAT TextFileFormat WITH (  
      FORMAT_TYPE = DELIMITEDTEXT,
      FORMAT_OPTIONS (FIELD_TERMINATOR =',',USE_TYPE_DEFAULT = TRUE))
Returns Incorrect syntax near 'EXTERNAL'

**Comment by rothja** [comment] 2020-01-06 15:22
@gurvinderkandhola Thanks for the additional test. @MikeRayMSFT could you take a look at this one more time with the evaluation version of 2019 (or developer version) just to make sure that we can't reproduce this? I wonder if there are others reporting the problem on the forums too. I'm reopening so we can look one more time. If it is a per configuration problem, then support would still need to be contacted to investigate.

**Comment by gurvinderkandhola** [comment] 2020-01-06 17:36
@rothja I was able to make it work after
---ran the following command 
EXEC sp_configure  'polybase enabled', 1
reconfigure
-----then ran the same command and it worked---

CREATE EXTERNAL FILE FORMAT TextFileFormat WITH (  
      FORMAT_TYPE = DELIMITEDTEXT,
      FORMAT_OPTIONS (FIELD_TERMINATOR =',',USE_TYPE_DEFAULT = TRUE))

Although i had checked earlier that polybase was enabled, so just the EXEC sp_configure made it work.

**Comment by rothja** [comment] 2020-01-06 17:45
@gurvinderkandhola Thank you for the update! I think this might be the issue in other cases. I apologize the docs are not clear on this. @MikeRayMSFT Do you think that in this reference article we should point back to the PolyBase installation article, especially the section on [enabling it](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-ver15#enable). I'm not sure whether this reference article points back to even the overview information when it talks about PolyBase?

**Comment by CarlRabeler** [comment] 2020-01-22 05:03
creating a PR with a note added re: install and enable PolyBase

**Closed** 2020-01-24 11:47 UTC
Labels: Pri2, assigned-to-author, product-feedback, sql/prod, t-sql/tech
