### ISSUE TITLE
Missing information about altering columns in the system versioned table

### ISSUE THREAD

**Issue by Astral100** [MicrosoftDocs/sql-docs#9149] opened 2023-07-11 07:30 UTC
Hello,

This page doesn't mention that altering columns is restricted on system versioned tables. I was caught off guard today when I couldn't rename a column name on the system versioned table (no error was thrown either), and I was sure I didn't see this restriction anywhere in the docs.
I had to switch off system versioning to rename the column in both the main and the history tables, and then turn the system versioning back on.
You should mention this as one of the restrictions, as this is quite a big limitation (consideration) on enabling this feature for existing tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7967cb92-4205-31da-e7a3-6ee76091c9fb
* Version Independent ID: d947240d-76dd-036f-b1b2-814e85ba3e9f
* Content: [Temporal table considerations and limitations - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-considerations-and-limitations?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/temporal-table-considerations-and-limitations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-considerations-and-limitations.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment] 2023-07-11 20:24
@Astral100 Can you please provide a code sample for your scenario, so I can take that back to the product team?

**Comment by Astral100** [comment] 2023-07-12 08:33
Which code do you require? Just try to rename columns in the system versioned table.

**Comment by rwestMSFT** [comment] 2023-07-12 15:15
@Astral100 I'm sure this may seem obvious to you, but I don't know how you did it. Did you use the user interface in SQL Server Management Studio table designer? Did you use `sp_rename`? Please can you provide us information of how you tried to do this, and if it was `sp_rename`, a code sample.

**Comment by Astral100** [comment] 2023-07-12 15:54
Hello, I tried both. That is why I am saying you should just try it.
Here is a code sample: `exec sp_rename 'dbo.AgencyFlags.CreatedTime', 'CreatedOn', 'COLUMN';`

**Comment by rwestMSFT** [comment] 2023-07-12 17:11
Thank you, this is helpful information. If this is unexpected behaviour from the product group's side, it goes deeper than just documenting this, so I appreciate it.

**Comment by rwestMSFT** [comment] 2023-08-21 21:01
Using the sample `WideWorldImporters` database, which contains system-versioned temporal tables, I was able to rename a column in a temporal table without any issue, using both Azure Data Studio's designer and `sp_rename` independently.

I'm not sure what issue you were experiencing, but we cannot reproduce it. I am therefore closing this issue.

**Closed by rwestMSFT** 2023-08-21 21:01 UTC
Labels: needs-more-info, assigned-to-author, Pri2, sql/svc, table-view-index/subsvc
