### ISSUE TITLE
There is an example that does not run.

### ISSUE THREAD

**Issue by sangeun-jo** [MicrosoftDocs/sql-docs#7143] opened 2021-12-25 22:32 UTC
[Enter feedback here]

This example has not been executed in SQL SERVER 2019  
```
USE AdventureWorks2019;  
SELECT
  ProductModelID,  
  Name,  
  Instructions.query(
    'declare namespace MI="https://schemas.microsoft.com/sqlserver/2004/07/adventure-works/ProductModelManuInstructions";
     /MI:root/MI:Location
    ') as ManuWorkCenterInformation  
FROM Production.ProductModel  
WHERE ProductModelID=7  
FOR XML PATH;
```
You should fix this like below.  
```
USE AdventureWorks2019;  

SELECT
  ProductModelID,  
  Name,  
  Instructions.query(
    'declare namespace MI="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/ProductModelManuInstructions";
     /MI:root/MI:Location
    ') as ManuWorkCenterInformation  
FROM Production.ProductModel  
WHERE ProductModelID=7  
FOR XML PATH;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f7ddea-ddb5-dcdd-6a92-b70c8dbbab06
* Version Independent ID: 69f59358-4230-3201-3aa7-08307cba9514
* Content: [Columns with a Name - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/columns-with-a-name?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/columns-with-a-name.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/columns-with-a-name.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment] 2021-12-29 08:17
Possible duplicate of #7142.

**Comment by WilliamAntonRohm** [comment] 2022-01-07 00:20
@MikeRayMSFT -- Mike, please review this change in [private PR 20963](https://github.com/MicrosoftDocs/sql-docs-pr/pull/20963).

**Comment by MikeRayMSFT** [comment] 2023-02-14 22:58
This fix has been completed under a different effort. Change `https:` to `http:`.

**Closed by MikeRayMSFT** 2023-02-14 22:58 UTC
Labels: sql/prod, xml/tech, doc-bug, Pri2, sql/svc
