### ISSUE TITLE
adutil-preview complains about "FQDN of domain must be given to CreateUser" and other errors

### ISSUE THREAD

**Issue by storm49152** [MicrosoftDocs/sql-docs#6131] opened 2021-02-26 15:36 UTC
I'm using EL-8.3 with MSSQL 2019, and I'm trying to follow the documentation on: [Tutorial: Configure Active Directory authentication with SQL Server on Linux using adutil](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15)

The MSSQL host has joined the AD, DNS/RDNS is properly configured, and I have a Kerberos ticket for a privileged user.

When trying to create the AD service user for MSSQL, I'm getting this (output redacted, and with debug to get a clue):

```
# adutil user create -d --name svc_mssql --distname CN=svc_mssql,OU=ServiceUsers,OU=<OU_Name>,DC=CONTOSO,DC=COM --password '<super_secret_password>'
adutil Configuration:
        KeytabDir: '/var/run/secrets/keytabs/adutil'
        UseLdaps: 'false'
        IsWindowsDomain: 'true'
        OUDistinguishedName: ''
        UseDefaultSystemCCache: 'true'
Using configuration file from /root/.adutil/adutil.json
Detected parameters: 
            Debug: true
             Name: svc_mssql
     NameDistName: CN=svc_mssql,OU=ServiceUsers,OU=<OU_Name>,DC=CONTOSO,DC=COM
Failed to lookup default realm from conf file in GetDefaultRealm: Configuration file does not specify default realm
Checking for valid kerberos ticket
UserHasKrb5Credentials: Enumerating credentials in default system CCache
UserHasKrb5Credentials: Found local TGT for realm CONTOSO.COM
UserHasKrb5Credentials: Found valid credentials
Running command: create user
Attempting to get password from --password flag
Creating user account svc_mssql (CN=svc_mssql,OU=ServiceUsers,OU=<OU_Name>,DC=CONTOSO,DC=COM) in 
FQDN of domain must be given to CreateUser
FQDN of domain must be given to CreateUser
```

What I found out that causes this, is that you actually need a fully/correctly configured Kerberos configuration file. I followed Option 1, and configuring Kerberos directly is only documented under Option 2 of [Join SQL Server on a Linux host to an Active Directory domain](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-join-domain?view=sql-server-ver15).

In Option 1 it is stated that `krb5.conf` will be updated but in practice, at least for me, the update does not result in a working configuration.
The `krb5.conf` example in Option 2 does not seem to be complete/working.

For me, a working example `krb5.conf` file looks like:

```
includedir /etc/krb5.conf.d/

[logging]
    default = FILE:/var/log/krb5libs.log
    admin_server = FILE:/var/log/kadmind.log
    kdc = FILE:/var/log/krb5kdc.log

[libdefaults]
    default_realm = CONTOSO.COM
    default_ccache_name = KEYRING:persistent:%{uid}
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 rc4-hmac des-cbc-crc des-cbc-md5
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 rc4-hmac des-cbc-crc des-cbc-md5
    permitted_enctypes = aes256-cts-hmac-sha1-96 rc4-hmac des-cbc-crc des-cbc-md5
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
    spake_preauth_groups = edwards25519

[realms]
    CONTOSO.COM = {
        admin_server = dc1.contoso.com
        kdc = dc1.ocntoso.com
        kdc = dc2.contoso.com
    }

[domain_realm]
    contoso.com = CONTOSO.COM
    .contoso.com = CONTOSO.COM
```

If you only fix the `[realms]` and `[domain_realm]` sections (according to Section 2), you will be bitten by another error about an unsupported enctype, and therefore the `*_enctypes` parameters are required. Apparently newer Linux Kerberos tools do not accept those enctypes anymore, while Windows' Kerberos still relies on them.

If you verify this and come to the same conclusion, can you please enhance the documentation with this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84e4ebac-6e2e-f188-e382-4e8d9940f8fb
* Version Independent ID: c256593c-499f-1cf9-9f6b-eba3516de73a
* Content: [Configure Active Directory authentication with SQL Server on Linux using adutil - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-ad-auth-adutil-tutorial.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment] 2021-02-26 17:58
@storm49152 -- thank you for your detailed feedback.

@amvin87 -- please look into this issue.

**Comment by amvin87** [comment] 2021-02-26 19:09
yes, I will take a look at this sometime next week

**Comment by rfsonders** [comment] 2021-04-01 01:13
I am experiencing the exact same issue. Also RHEL 8.3
@storm49152  Thank you for the detail.

**Comment by storm49152** [comment] 2021-04-01 08:08
In addition to what I wrote before..

In June 2020 we had AD integration working on RHEL 8.2, but we can't get it to work anymore on RHEL 8.3: SQL Studio and logging complain about `The login is from an untrusted domain and cannot be used with Integrated authentication`. I'm pretty sure that I trust the configured  domain, which otherwise seems to work just fine.. And remember, in RHEL8.2 it worked.

Just for fun we checked Ubuntu (never looked at Suse) and that worked, but it would require us to
a) use Ubuntu, which doesn't fit in our automation train since we standardized on RHEL, and
b) both Ubuntu 16.04 and 18.04 are older LTS versions. Even if we were going to use Ubuntu, we're in a green field and we'd want to use the latest LTS, which is currently 20.04. Microsoft should support the latest LTS for this distro.

The state of documentation and the fact that this documentation bug/incompleteness is still around ("sometime next week" has long since passed) makes us believe that SQL Server on Linux is not being taken as seriously as it should if you want to run it in production.

We really wanted to run SQL Server on Linux, but all this made us change our mind. For us, AD integration is a must-have, so we had to install on Windows instead.

**Comment by amvin87** [comment] 2021-04-01 13:54
Hi @storm49152, apologies I could not look into this before. The krb5.conf file that you showed and as documented in the option 2, is the right way to do it. I will check and verify option 1 in our internal labs. Meanwhile, if the issue you face is urgent and needs timely resolutions. I would request you to work with the Microsoft support team to help resolve issues faster. For the other concerns, that you have SQL AD Authentication should work for RHEL 8.3 and if it is failing for you, please work with the Microsoft support so logs can be collected to see, what the issue is. Ubuntu 20.04 will be soon supported and is in our roadmaps.

**Comment by storm49152** [comment] 2021-04-01 16:25
Hi @amvin87. Thanks for letting me know I was on the right track. I don't want to start a support thread here, but I do want the world to know that they may be running into issues when installing on RHEL8.3; maybe someone who already knows the solution stumbles on this and can post the solution here.

We don't necessarily have a pleasant experience in working with support. This is because we're located in EU, and it means we eventually (when reaching the appropriate level of support) encounter a timezone barrier which again makes everything take a long time. It's time we don't have, so we opted to install on Windows instead. Which I think is unfortunate for various reasons.

To me it looks like interoperability issues between an MS and Red Hat product, so maybe this is something that MS can take up with Red Hat, instead of us customers having to battle with support. I understand that the install base for SQL Server on Linux is **much** smaller that on Windows and so the incentive is lower, however, it would be **much** appreciated if you investigate this on RHEL8.3 and update the documentation to your findings. It may still be worth it to us to revisit.

**Comment by VanMSFT** [comment] 2021-04-01 20:27
Hi @storm49152! Thank you for your feedback. We understand your concerns, and appreciate that you have taken the time to offer suggestions. Having said that, the doc forum is not an optimal place to troubleshoot these things. There could be issues between distribution versions, environment related, or often unknown. When an article is published, there are testing that takes place before it goes live. @amvin87 is right that these things should start with Microsoft Support, so that logs and troubleshooting can take place, as well as getting the appropriate people involved that work on the product and could confirm if it's indeed an issue with the product/documentation, or just with individual environments. Once the issue has been confirmed by an appropriate member of the Product Team, we will process a documentation update.

**Comment by amvin87** [comment] 2021-04-07 18:45
Hi @storm49152 we support Ubuntu 20.04 now, you can refer this for more details : https://techcommunity.microsoft.com/t5/sql-server/sql-server-2019-on-ubuntu-20-04-python2-dependency-removed-for/ba-p/2259118

**Comment by storm49152** [comment] 2021-04-07 21:07
Hi @amvin87. Thanks for letting us know. It is really good to see this happening!
Unfortunately, like I mentioned before, because we standardized on RHEL, for us it is not a solution because we'd have to modify our automation train to fully support Ubuntu. We tried Ubuntu just to see if we didn't follow the docs correctly and thereby misconfigured something, or if AD integration just didn't work at all. But it did work on Ubuntu, so I knew we were doing it right according to the docs. Therefore it is my belief that the doc needs an update for RHEL 8.3 specifically.

**Comment by amvin87** [comment] 2021-04-07 21:21
Thanks for the update @storm49152, I would really suggest here that you open a support ticket with Microsoft support team, so we can understand why it is not working. I will be trying this on RHEL 8.3 as well but it may take me some time before I can get to try this. Meanwhile ,it did work for previous versions of RHEL, when I wrote the doc, so I'd expect it to work for RHEL 8.3, but this could be a issue with RHEL 8.3 as you mentioned. Best way to help resolve your issue at this moment imo is if you could reach out to Microsoft support.

**Comment by VanMSFT** [comment] 2021-04-07 21:32
@storm49152 @amvin87 - Thanks for the discussions on here. I'm going to close this issue since there are no document actions, but you are welcome to continue with the discussions.

**Closed by VanMSFT** 2021-04-07 21:32 UTC
Labels: Pri1, assigned-to-author, doc-bug, linux/tech, sql/prod
