### ISSUE TITLE
Usability feedback on setting default values with functions

### ISSUE THREAD

**Issue by CJHarmath** [MicrosoftDocs/sql-docs#8641] opened 2023-02-23 17:43 UTC
Based on the docs it wasn't obvious to me at first that I cannot specify a SQL expression as the default value.
For example I wanted something like this
```sql
DEFAULT MAX(position) + 1
```

But seems like I can't do that and that I first needed to create a user function and then set the default with that function such as

```sql
DEFAULT dbo.getNextPosition()
```

This wasn't a use case where auto increment would have been possible, but a case where there is a list of items in a table with each having a position column which can be changed, while needs to stay unique.
The requirement was that if no position is specified then use MAX(position)+1

an example table could be a race tracking table which has player id's and their positions. if we want to allow reshuffling / reordering the positions with the default to add to the last position what would be similar to my use case.
```sql
CREATE TABLE dbo.race_tracking (
   id INT PRIMARY KEY,
    player_id INT NOT NULL,
    position INT
)
```
So auto increment wouldn't be good when new players can be added, removed and the requirement includes being able to reshuffle positions such that a player on the 10th place can be moved up to the 1st.

This issue is really just about spelling out the fact that yes, you can do SQL expression but you need to move them to a function first. 
That's not obvious on a first read.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ca32e50-c2a3-206a-4362-b00613aab10b
* Version Independent ID: 9699fe54-f01c-6550-4ad4-1962f4147fb9
* Content: [Specify Default Values for Columns - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/specify-default-values-for-columns?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/specify-default-values-for-columns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/specify-default-values-for-columns.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment] 2023-02-23 18:24
@CJHarmath -- CJ, thank you for your thorough feedback.

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment] 2023-02-23 21:07
Thanks @CJHarmath for contacting Microsoft with feedback about our product documentation. It could take from a few business days to a few weeks to look further into this and decide on how to address. We'll contact you if we need further information, and you'll receive an email message each time we mention you in a comment. 
	
Thanks again for this feedback, your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment] 2023-03-17 02:53
Hi @CJHarmath- The answer here is documented in the [CREATE TABLE](https://learn.microsoft.com/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16#:~:text=only%20a%20constant%20value%2C%20such%20as%20a%20character%20string%3B%20a%20scalar%20function%20(either%20a%20system%2C%20user-defined%2C%20or%20clr%20function)%3B%20or%20null%20can%20be%20used%20as%20a%20default.%20) article. 

> Only a constant value, such as a character string; a scalar function (either a system, user-defined, or CLR function); or NULL can be used as a default. 

Your use of a scalar function is exactly as intended.

If you think our docs could be more clear about this, might be easier for you to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself, instead of trying to describe it. By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After your PR is merged, GitHub lists you as an article contributor. Either way, thanks for your feedback!

**Closed by WilliamDAssafMSFT** 2023-03-17 02:53 UTC
Labels: doc-enhancement, assigned-to-author, Pri1, sql/svc, table-view-index/subsvc
