### ISSUE TITLE
No docs for QUIETSIMPLE and QUIET parameters

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/sql-docs#1628] opened 2019-02-09 20:32 UTC
In the doc: sql-docs/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md

There is no documentation for the parameters QUIET and/or QUIETSIMPLE.  These parameters are written to the ConfigurationFile.ini by the SQL Server Setup Wizard and yet there is no mention of either of these values on the Microsoft Docs site -- at least, none that I could pull up utilizing the Search function.

**Comment by MightyPen** [comment] 2019-02-09 23:35
@MashaMSFT Hi Masha, This Issue 1628 is very closely related to your subsequent other Issue 1629 (same .md article).

- _GitHub:_ &nbsp; [https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/database-engine/install-windows/install-sql-server-from-the-command-prompt.md)

- _Docs:_ &nbsp; [https://docs.microsoft.com/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017](https://docs.microsoft.com/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017)

CC: @astrohart

**Comment by MashaMSFT** [comment] 2019-02-11 17:47
Hi @astrohart , thanks for contacting Microsoft and bringing this to our attention! Let me do a little research... Thanks!

**Comment by MashaMSFT** [comment] 2019-02-11 17:56
Hi @astrohart , the explanation for /quiet and /quietsimple can be found in the doc that @MightyPen pasted:   https://docs.microsoft.com/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017

SQL Server Setup Control | /Q | Specifies that Setup runs in a quiet mode without any user interface. This is used for unattended installations.
SQL Server Setup Control | /QS | Specifies that Setup runs and shows progress through the UI, but does not accept any input or show any error messages.

Additionally, there's a note at the top of the same page: 
When installing through the command prompt, SQL Server supports full quiet mode by using the /Q parameter, or Quiet Simple mode by using the /QS parameter. The /QS switch only shows progress, does not accept any input, and displays no error messages if encountered. The /QS parameter is only supported when /Action=install is specified.

Did you have any further questions on these parameters, other than the one from Git Issue [1629](https://github.com/MicrosoftDocs/sql-docs/issues/1629#event-2128967758)? Thanks!

**Comment by astrohart** [comment] 2019-02-11 18:37
Don’t reply to me, update the docs.

The question is whether /Q and /QS have any values (/Q=“True” or just /Q — the docs should say which).

Also, can /Q and /QS both be specified?  Docs do not say, and do not say which has precedence.  

Also, there is no documentation whatsoever for the /QUIET and /QUIETSIMPLE parameters which are present in Config.ini

Regards,
 
Brian C. Hart, Ph.D.
CEO, xyLOGIX, LLC

San Diego:
5663 Balboa Avenue Suite 412
San Diego, California 92111

Washington, DC:
1845 Cain Drive Suite 1
Fort George G. Meade, Maryland 20755

‭(443) 679-8247‬ mobile
www.xylogix.net

**Comment by MashaMSFT** [comment] 2019-02-11 19:18
Hi @astrohart , yes, I am already working on editing the content. 

/quiet and /q are the same parameter, as are /quietsimple and /qs. The parameter  you use is /q, it enables the /quiet installation. I believe both  (/q and /quiet as well as /qs and quietsimple) can be used interchangeably but I'm getting confirmation before updating the docs, as per your request. 

There is an example of how to use it in the same document (you do not need an =true): 

setup.exe /q /ACTION=Install /FEATURES=SQL /INSTANCENAME=MSSQLSERVER 

Also, just an FYI, your PII from your email has been appended to the Git Issue, and is now visible to everyone. I'm not sure if that was intended. You can edit the post to remove it, if not... 

Thanks!

**Comment by astrohart** [comment] 2019-02-11 21:48
Thanks for alerting me about the PII I have removed it.

And as regards the parameters, I think that I myself am very much aware about how they work so it’s not really necessary to explain it to me, however, it would be proper to make sure the documentation is clear.

**Comment by craigg-msft** [comment] 2019-02-12 03:01
Thank you @astrohart  .One of the reasons Masha went into detail is the issues are public and others may read and learn from a complete reposne.  You are also welcome and encouraged to contribute directly to topics by submitting a PR. To do so, you click the Edit button in the upper right of of the tiopic,  More info at https://docs.microsoft.com/en-us/sql/sql-server/sql-server-docs-contribute?view=sql-server-2017  Not everyone has the time I understand, but if you do its a great way to help others. Thank you.

**Comment by MashaMSFT** [comment] 2019-02-21 20:02
Hi @astrohart , thanks for bringing this to our attention! I have added a note indicating that you can use either /Q or /QUIET and /QS or /QUIETSIMPLE as a parameter. I will now proceed with closing out this Git Issue but please feel free to comment here if you feel something further needs to be added. Thanks again!

**Closed by MashaMSFT** 2019-02-21 20:02 UTC
Labels: Issue-Status-20-Author-will-triage

**Comment by astrohart** [comment] 2019-02-26 19:21
thanks
