### ISSUE TITLE
Replication of serveral Schemas

### ISSUE THREAD

**Issue by jaalsuca** [MicrosoftDocs/sql-docs#3932] opened 2020-01-09 03:25 UTC
Hi Team

I am trying to set up transactional replication but my database has several schemas and schema has same name table, here the SQL Server finds an exception because it detects the table name already has been created and an error pop-up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086945e-a60b-31ed-9445-160fed6ea1f1
* Version Independent ID: 2dcdbf33-d5af-b766-dd5c-f477c8b441b7
* Content: [Tutorial: Configure Transactional Replication - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment] 2020-01-09 22:50
@jaalsuca -- Jairo, thank you for your feedback.  You are welcome to note this behavior here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

@MashaMSFT -- Masha, please look into clarifying the documentation on this point.

**Comment by MashaMSFT** [comment] 2020-01-10 02:53
Hi @jaalsuca , thanks for bringing this to our attention! Are you using the AdventureWorks database as the prerequisite states?

Thanks!
Masha from the SQL Docs team

**Comment by jaalsuca** [comment] 2020-01-13 21:46
Good day MashaMSFT

Thanks for your feedback, I am always happy to help. No, I am not using the AdventureWorks database in my case, I am testing with SCOM database on a test environment, indeed the concept of replication works well, but multiple exceptions with tables with the same name but different schema. As soon as I can; will document this on my website.

Regards;
Jairo Suarez
Data Management Team

**Comment by MashaMSFT** [comment] 2020-01-14 00:42
Hi @jaalsuca , ahh, okay I see. Thanks for the additional context! Unfortunately, since the issue is not occurring with the database used in the tutorial, this type of question would be considered outside the scope of this forum - which focuses specifically on documentation. 

To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

I hope that helps and please let us know if we can be of further assistance from the documentation aspect of things? I'm going to move forward with closing out this Git Issue, but please feel free to comment should you need anything further. 

My apologies that the documentation team is unable to help you further this this :( 

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Closed by MashaMSFT** 2020-01-14 00:42 UTC
Labels: Pri1, assigned-to-author, doc-bug, replication/tech, sql/prod

**Comment by jaalsuca** [comment] 2020-01-14 03:00
Hi Masha
Will be fine. Thanks so much for your time and dedication. 

Regards;

Jairo Suarez
